#!/usr/bin/env python

import sys
from scapy import *

interface = sys.argv[1]    
unique = []

def sniffBeacon(p):	
     if unique.count(p.addr2) == 0:
          unique.append(p.addr2)
          if p.haslayer(Dot11Beacon):
               print p.sprintf("%Dot11.addr2%[%Dot11Elt.info%|%Dot11Beacon.cap%]")
          else:
               print p.sprintf("[%Dot11.addr1%][%Dot11.addr2%][%Dot11Elt.info%]")

sniff(iface=interface,prn=sniffBeacon)
