#!/usr/bin/perl

my $pif = $ARGV[0];
if ($pif) {
  print "$pif ";
}

open(CONFIG, "ifconfig -a -u inet 2> /dev/null |")
  || die "Couldn't run ifconfig";

my $intf = 0;
my $addr;
my $bcast;

while (<CONFIG>) {
  if (/^((en|tap|tun)[0-9]):/) {
    if ($1 ne $pif) {
      $intf = $1;
    } else {
      $intf = 0;
    }
  }
  elsif ($intf and /inet (\S+) .* broadcast (\S+)/) {
    $addr = $1;
    @bcast = map { $_ == 255 ? 0 : 255 } split '\\.', $2;
    $bcast = join '.', @bcast;

    print "$intf\@$addr:$bcast ";

    $intf = 0;
  }
}
print "\n";

close(CONFIG);
