#!/bin/bash

intf=$1
addr=$2

sudo tcpdump -i $intf host $addr and \
     not port mmcc and \
     not port 6667 and \
     not port jabber-client and \
     not port msnp and \
     not port aol and \
     not arp and \
     not port ssh
