#!/bin/sh

if [[ -f /tmp/.syncing ]]; then
    exit 0
else
    touch /tmp/.syncing
fi

echo "=== git annex sync"
git annex sync

if [[ $(hostname) =~ [Vv]ulcan ]]; then
    echo "=== git annex sync backblaze --content --all"
    git annex sync backblaze --content --all

    if ssh hermes true ; then
        echo "=== git annex sync tank --content --all"
        git annex sync tank --content --all
        echo "=== git annex sync hermes --content --all"
        git annex sync hermes --content --all

        echo "=== ssh hermes syncit"
        ssh hermes "(cd $PWD; syncit)"
    fi
elif [[ $(hostname) =~ [Hh]ermes ]]; then
    if ssh vulcan true ; then
        echo "=== git annex sync tank --content --all"
        git annex sync tank --content --all
        echo "=== git annex sync vulcan --content --all"
        git annex sync vulcan --content --all

        echo "=== ssh vulcan syncit"
        ssh vulcan "(cd $PWD; syncit)"
    fi
fi

echo "=== git annex sync (done)"

rm -f /tmp/.syncing
