#!/bin/bash

export LC_ALL='UTF-8' 

contacts -f '%n <%e>' -S | grep -v '<>' \
    | sort | uniq > /tmp/addr.$$

sqlite3 Envelope\ Index 'select comment, address from addresses' \
    | sed -e 's/|/ </' -e 's/$/>/' \
    | sort | uniq >> /tmp/addr.$$

cat /tmp/addr.$$ 

rm -f /tmp/addr.$$
