#!/usr/bin/env bash
model=sonnet
if [[ "$1" == "opus" ]]; then
    shift 1
    model=opus
fi
export EXTENSION_SECRET=$(pass browser-control.mcp | head -1)
claude --model $model --dangerously-skip-permissions "$@"
