#!/usr/bin/env bash

B3SUMS="/tmp/SUMS.txt.$$"

cat "$@" > "$B3SUMS"

find . -type f -print0 | xargs -0 -P10 b3sum | while read file ; do
    SUM=$(echo "$file" | awk '{print $1}')
    PATHNAME=$(echo "$file" | cut -c67-)
    if grep -q "^$SUM" "$B3SUMS" ; then
        echo "$PATHNAME"
    fi
done

rm -f "$B3SUMS"
