#!/bin/bash

B3SUMS="$1"

find . -type f -print0 | xargs -0 -P10 b3sum | while read file ; do
    SUM=$(echo "$file" | awk '{print $1}')
    PATHNAME=$(echo "$file" | cut -c67-)
    if grep -q "^$SUM" "$B3SUMS" ; then
        echo "$PATHNAME"
    fi
done
