#!/bin/bash

for file in *.dmg *.zip; do
    if [[ -f "$file" ]]; then
	if echo "$file" | grep -q '\.dmg$'; then
	    bzdmg "$file"
	fi
        verify -v "$file"
	mv "$file" ~/Archives/Mac\ OS\ X/Software
    elif [[ -d "$file" ]]; then
	echo Archiving in directory $file ... > /dev/stderr
    fi
done
