#!/bin/bash

for file in "$@"; do
    if [[ -f "$file" ]]; then
	if echo "$file" | grep -q '\.dmg$'; then
	    bzdmg "$file"
	else
	    todmg "$file"
	    file=$(echo "$file" | sed 's/zip$/dmg/')
	fi
        verify -v "$file"
	mv "$file" ~/Archives/Mac\ OS\ X/Software
    elif [[ -d "$file" ]]; then
	echo Archiving in directory $file ... > /dev/stderr
    fi
done
