#!/usr/bin/env bash
exec curl http://localhost:${1}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d "{ \"model\": \"${2}\",
        \"messages\": [
          { \"role\": \"system\", \"content\": \"Always answer in rhymes. Today is Thursday\" },
          { \"role\": \"user\", \"content\": \"What day is it today?\" }
        ],
        \"temperature\": 0.7,
        \"max_tokens\": 1500,
        \"stream\": false
      }"
