#!/usr/bin/env bash
exec curl http://localhost:${1}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d "{ \"model\": \"${2}\",
        \"messages\": [
          { \"role\": \"system\", \"content\": \"You are a philosopher. Answer in sufficient detail that I could convince another thinking person of the correctness of your answer, or at least the cogency of your argument\" },
          { \"role\": \"user\", \"content\": \"How much wood would a woodchuck chuck if a woodchuck could chuck wood?\" }
        ],
        \"temperature\": 0.7,
        \"max_tokens\": 2000,
        \"stream\": false
      }"
