#!/usr/bin/env bash

OPTS=$(getopt -o h:p:m: --long host:,port:,model: -- "$@")
if [ $? != 0 ]; then
  echo "Failed to parse options." >&2
  exit 1
fi

eval set -- "$OPTS"

HOST="localhost"
PORT="8080"
MODEL=""

# Parse options
while true; do
  case "$1" in
    -h|--host)
      HOST="$2"
      shift 2
      ;;
    -p|--port)
      PORT="$2"
      shift 2
      ;;
    -m|--model)
      MODEL="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Internal error!" >&2
      exit 1
      ;;
  esac
done

echo "Host:  $HOST"
echo "Port:  $PORT"
if [[ -n "$MODEL" ]]; then
    echo "Model: $MODEL"
else
    echo "Please specify the model to ask using --model"
    exit 1
fi
echo ""

curl -sv http://${HOST}:${PORT}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d "{ \"model\": \"${MODEL}\",
        \"messages\": [
          { \"role\": \"system\", \"content\": \"You are a philosopher. Answer in sufficient detail that I could convince another thinking person of the correctness of your answer, or at least the cogency of your argument\" },
          { \"role\": \"user\", \"content\": \"How much wood would a woodchuck chuck if a woodchuck could chuck wood?\" }
        ],
        \"temperature\": 0.7,
        \"max_tokens\": 2000,
        \"stream\": false
      }" | jq -r
