#!/usr/bin/env bash

REPO=$1
shift 1

export B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID:-$(pass show Passwords/backblaze-api-key)}
export B2_APPLICATION_KEY=${B2_APPLICATION_KEY:-$(pass show Passwords/backblaze-secret-key)}

export B2_ACCOUNT_ID=$B2_APPLICATION_KEY_ID
export B2_ACCOUNT_KEY=$B2_APPLICATION_KEY

exec restic --repo b2:jwiegley-${REPO}: "$@"
