#!/bin/bash

for fileset in                                  \
    Audio                                       \
    Backups/Misc                                \
    Backups/Servers                             \
    Backups/System/Applications                 \
    Databases                                   \
    Games                                       \
    Media                                       \
    Movies                                      \
    Photos                                      \
    Pictures                                    \
    Projects
do
    (cd /Volumes/mybook/$fileset; b2-sync $fileset)
done
