#!/bin/bash

POOL="$1"
shift 1

export PATH=$HOME/.nix-profile/bin:$PATH
export RESTIC_PASSWORD_COMMAND="pass show Passwords/restic"

# export B2_ACCOUNT_ID=${B2_ACCOUNT_ID:-$(pass show Passwords/backblaze-api-key)}
# export B2_ACCOUNT_KEY=${B2_ACCOUNT_KEY:-$(pass show Passwords/backblaze-secret-key)}

export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-$(pass show Passwords/b2-access-key-id | head -1)}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-$(pass show Passwords/b2-access-key | head -1)}

function restic_it() {
    echo "========================================================================"
    echo "restic backup ${@:$#}"
    echo "========================================================================"

    if [[ "$1" == "--bucket" ]]; then
        bucket="$2"
        shift 2
    else
        bucket=$(echo ${@:$#} | sed 's%/%-%g')
    fi

    cat ~/.config/ignore.lst                    \
        | sed 's/^- //'                         \
        | sed 's%/$%/**%'                       \
        > /tmp/ignore.$$

    fs="${@:$#}"
    DIR=$(zfs get -H -o value mountpoint $POOL/$fs)

        # --repo b2:jwiegley-${bucket} backup

    restic                                                                      \
        --repo s3:s3.us-west-001.backblazeb2.com/jwiegley-${bucket} backup      \
	-o b2.connections=10                                                    \
        --ignore-inode                                                          \
        --one-file-system                                                       \
        --exclude-if-present '.b2-exclude'                                      \
        --exclude-file /tmp/ignore.$$                                           \
        "${@:1:$#-1}"                                                           \
        "$DIR"
}

function backup() {

case ${1:---all} in
  --all)
    for i in                                    \
        Audio                                   \
        Backups/Misc                            \
        Databases                               \
        Desktop                                 \
        Documents                               \
        Home                                    \
        Library                                 \
        Media                                   \
        Messages                                \
        Photos                                  \
        Video                                   \
        doc                                     \
        src
    do
        backup $i
    done
    ;;

  Home | kadena | src)
    restic_it                                   \
        --exclude '*.agdai'                     \
        --exclude '*.glob'                      \
        --exclude '*.hi'                        \
        --exclude '*.o'                         \
        --exclude '*.aux'                       \
        --exclude '*.vo'                        \
        --exclude '*.vok'                       \
        --exclude '*.vos'                       \
        --exclude '*.elc'                       \
        --exclude '*.eln'                       \
        --exclude '*.cma'                       \
        --exclude '*.cmi'                       \
        --exclude '*.cmo'                       \
        --exclude '*.cmx'                       \
        --exclude '*.cmxa'                      \
        --exclude '*.cmxs'                      \
        --exclude '*.lia-cache'                 \
        --exclude '*.lra-cache'                 \
        --exclude '*.nia-cache'                 \
        --exclude '*.nra-cache'                 \
        --exclude '.lia.cache'                  \
        --exclude '.lra.cache'                  \
        --exclude '.nia.cache'                  \
        --exclude '.nra.cache'                  \
        --exclude '.vagrant'                    \
        --exclude '.ghc.*'                      \
        --exclude '.cabal'                      \
        --exclude '.cargo'                      \
        --exclude '.coq-native'                 \
        --exclude 'result'                      \
        --exclude 'result-*'                    \
        --exclude '.ghc'                        \
        --exclude '.MAlonzo'                    \
        --exclude '.dist'                       \
        --exclude '.dist-newstyle'              \
        --exclude '.slocdata'                   \
        --exclude '.local/share/vagrant'        \
        $1 ;;

  Library)
    restic_it                                                           \
        --exclude 'Application Support/Bookmap/Cache'                   \
        --exclude 'Application Support/FileProvider'                    \
        --exclude 'Application Support/MobileSync'                      \
        --exclude 'CloudStorage/GoogleDrive-copper2gold1@gmail.com'     \
        --exclude 'Containers'                                          \
        --exclude 'Caches/GeoServices'                                  \
        $1 ;;

  Messages)
    restic_it                                   \
        --exclude 'lucene-indexes'              \
        --exclude 'dovecot.index.*'             \
        $1 ;;

  Video)
    # jww (2023-01-13): Due to historical accident, the bucket is called
    # jwiegley-Movies, and not jwiegley-Video; but since it's very large and I
    # cannot rename buckets, it's not worth re-uploading just yet. The usual
    # ~/Movies folder isn't something I backup to B2.
    restic_it --bucket Movies $1 ;;

  *) restic_it $1 ;;
esac

}

backup $1
