#!/bin/bash

export B2_ACCOUNT_ID=${B2_ACCOUNT_ID:-$(pass show Passwords/backblaze-api-key)}
export B2_ACCOUNT_KEY=${B2_ACCOUNT_KEY:-$(pass show Passwords/backblaze-secret-key)}

REMOTE=$1
shift 1

function restic_it() {
    echo "========================================================================"
    echo "restic backup ${@:$#}"
    echo "========================================================================"
    bucket=$(echo ${@:$#} | sed 's%/%-%g')
    (cd $REMOTE;                                        \
     restic --repo b2:jwiegley-${bucket}: backup        \
	    -o b2.connections=10                        \
            --ignore-inode                              \
            --one-file-system                           \
            --exclude '.DocumentRevisions-V100/**'      \
            --exclude '.Spotlight-V100/**'              \
            --exclude '.TemporaryItems/**'              \
            --exclude '.Trash/**'                       \
            --exclude '.Trashes/**'                     \
            --exclude '.Trashes'                        \
            --exclude '.apdisk'                         \
            --exclude '.fseventsd/**'                   \
            --exclude '_cache/**'                       \
            --exclude '.zfs/**'                         \
            "$@")
}

case ${1:-all} in
  tank)
    for i in      \
        Documents \
        Messages  \
        src       \
        Databases \
        Audio     \
        Desktop   \
        Games     \
        Home      \
        Library   \
        Media     \
        Misc      \
        Photos    \
        Pictures  \
        Movies    \
        Nasim
    do
        b2-restic $REMOTE $i
    done
    ;;

  Misc)    restic_it Backups/Misc ;;
  Nasim)   restic_it Backups/Nasim ;;

  Messages)
    restic_it                                   \
        --exclude 'dovecot.index.backup'        \
        --exclude 'dovecot.index.cache'         \
        Messages ;;

  src)
    restic_it                                   \
        --exclude '/src/nix/nixpkgs/**'         \
        src ;;

  Media)
    restic_it                                   \
        --exclude 'Windows/Media/**'            \
        --exclude 'Windows/Templates/**'        \
        --exclude 'macOS/Media/**'              \
        --exclude 'macOS/Templates/**'          \
        --exclude 'Linux/CentOS/Media/**'       \
        --exclude 'Linux/Ubuntu/Media/**'       \
        Media ;;

  Movies)
    restic_it                                   \
        --exclude 'Bicycle/**'                  \
        --exclude 'DSSS17/**'                   \
        --exclude 'OPLSS/**'                    \
        --exclude 'Introductory/**'             \
        --exclude 'Haskell/**'                  \
        --exclude 'Finance/**'                  \
        Movies ;;

  *) restic_it $1 ;;
esac
