#!/bin/bash

#Archives
for i in \
Machines
do
rsync -rtP --modify-window=2 --delete --inplace "$@" \
      --ignore-errors \
      --exclude='/38*/' \
      --exclude='/Desktop DB' \
      --exclude='/Desktop DF' \
      --exclude='/TheVolumeSettingsFolder/' \
      --exclude='/lost+found/' \
      --exclude='/.Caches/' \
      --exclude='.DS_Store' \
      --exclude='/.Spotlight-V100/' \
      --exclude='/.TemporaryItems/' \
      --exclude='/.Trashes/' \
      --exclude='/.com.apple.timemachine.donotpresent' \
      --exclude='/.com.apple.timemachine.supported' \
      --exclude='/.fseventsd/' \
      /Volumes/RAID/$i/ /Volumes/backup/$i/
done
