#!/bin/bash

function monitor() {
    label="$1"
    shift 1
    echo "$label"
    date >> ~/Library/Logs/${label}.log
    /usr/bin/time "$@"                          \
        >> ~/Library/Logs/${label}.log 2>&1     \
        || echo "$label FAILED!"
}

# Make sure that all authentications have been loaded:

u vulcan pull
getpass 'sample.com'
(cd ~/src/emacs ; git ru)

# Now run the backup

if quickping $HERMES_ETHERNET; then
    monitor "push-hermes" push hermes
fi

if [[ -d /Volumes/tank/src/pushme ]]; then
    monitor "push-tank" push tank

    monitor "rsync-CopperToGold" \
        volcopy --delete /Volumes/CopperToGold/ /Volumes/tank/Backups/CopperToGold/

    monitor "snapshots-tank" sudo sanoid --cron --verbose

    monitor "syncoid-cardano" \
        syncoid ext/ChainState/cardano tank/ChainState/cardano
    monitor "syncoid-Photos" \
        syncoid ext/Photos tank/Photos
    monitor "syncoid-kadena" \
        syncoid -r --skip-parent athena:studio/ChainState/kadena tank/ChainState/kadena

    monitor "b2-restic" b2-restic tank --all
fi

monitor "reindex-mail" reindex-mail

# if [[ ! -d ~/.local/share/recoll/xapiandb ]]; then
#     mkdir -p ~/.local/share/recoll/xapiandb
# fi
# monitor "recollindex" recollindex -z

monitor "update-kadena" update ~/kadena
monitor "update-src"    update ~/src
monitor "update-doc"    update ~/doc

if quickping $HERMES_ETHERNET; then
    monitor "nix-update-sync" u vulcan update-sync
else
    monitor "nix-update" u vulcan update
fi
