#!/usr/bin/env bash

mkdir -p ~/doc/machines
cd ~/doc/machines

rsync -av --delete ~/hera/ hera/
rsync -av --delete clio:clio/ clio/
rsync -av --delete athena:athena/ athena/
mkdir -p vulcan/etc
mkdir -p vulcan/var/lib
rsync -av --delete vulcan:/etc/ vulcan/etc/
rsync -av --delete vulcan:/var/lib/ vulcan/var/lib/     \
      --exclude=/AccountsService/                       \
      --exclude=/containers/                            \
      --exclude=/dhcpcd/                                \
      --exclude=/dhcpd/                                 \
      --exclude=/logrotate.status                       \
      --exclude=/machines/                              \
      --exclude=/portables/                             \
      --exclude=/private/                               \
      --exclude=/systemd/                               \
      --exclude=/pihole/etc-pihole/logrotate
