#!/bin/bash

Untitled="/Volumes/BOOTCAMP"
Documents_and_Settings="$Untitled/Documents and Settings"
John_Wiegley="$Documents_and_Settings/John Wiegley"
All_Users="$Documents_and_Settings/All Users"
All_Application_Data="$All_Users/Application Data"
My_Documents="$John_Wiegley/My Documents"
My_Games="$My_Documents/My Games"

Untitled_1="/Volumes/My Book"
Games="$Untitled_1"

Saves="$HOME/Archives/Backups/Saves"

OPTS="-aN --delete"

rsync $OPTS "$My_Documents"/ "$Saves"/My\ Documents/

#[[ ! -d "$Saves/Steam" ]] && mkdir -p "$Saves/Steam"
#for game in "$Games"/steam/steamapps/SourceMods/*; do
#    name=$(basename "$game")
#    [[ ! -d "$Saves/Steam/$name" ]] && mkdir -p "$Saves/Steam/$name"
#    rsync $OPTS "$game"/SAVE/ "$Saves/Steam/$name"/SAVE/
#done
#
#for game in "$Games"/steam/steamapps/jwiegley/*; do
#    name=$(basename "$game")
#    if [[ "$name" != "source sdk base" ]]; then
#	[[ ! -d "$Saves/Steam/$name" ]] && mkdir -p "$Saves/Steam/$name"
#	rsync $OPTS "$game"/*/SAVE/ "$Saves/Steam/$name"/SAVE/
#    fi
#done
