#!/bin/bash

HOST=192.168.9.144
RSYNC="rsync -az"

$RSYNC --delete ~/Machines/ $HOST::backup/Machines/

$RSYNC --delete /Volumes/RAID/Backups/VPS.sparsebundle/ $HOST::backup/VPS.sparsebundle/
$RSYNC --delete /Volumes/RAID/Backups/Saves/ $HOST::backup/Saves/
$RSYNC /Volumes/RAID/Backups/ $HOST::backup/

$RSYNC --exclude='*.dtBase2/' --exclude='*.sparsebundle/' \
    /Volumes/RAID/Archives/ $HOST::archive/
(cd /Volumes/RAID/Archives; find . \
    \( -name '*.dtBase2' -o -name '*.sparsebundle' \) -type d | \
while read dir; do
    dir=$(echo $dir | sed 's/^\.\///')
    $RSYNC --delete "/Volumes/RAID/Archives/$dir/" $HOST::"archive/$dir/"
done)

$RSYNC --exclude='Music/' /Volumes/RAID/Media/ $HOST::media/
$RSYNC /Volumes/RAID/Media/Music/iTunes/iTunes\ Media/ $HOST::media/
$RSYNC --delete /Volumes/RAID/Media/Music/iTunes/iTunes\ Media/Music/ $HOST::media/Music/
