#!/bin/bash

monitor() {
    label="$1"
    shift 1
    echo "===== $label ====="
    echo "########################################################################" \
         >> ~/Library/Logs/${label}.log
    date >> ~/Library/Logs/${label}.log
    echo "########################################################################" \
         >> ~/Library/Logs/${label}.log
    /usr/bin/time "$@"                          \
        >> ~/Library/Logs/${label}.log 2>&1     \
        || echo "$label FAILED!"
}

# Make sure that all authentications have been loaded:

u vulcan pull
getpass 'sample.com'
(cd ~/src/emacs ; git pull)

mbsync gmail-all-mail
mbsync gmail-kadena-all-mail
mbsync gmail-c2g-all-mail

# Now run the backup

monitor "reindex-mail" reindex-mail

# if [[ ! -d ~/.local/share/recoll/xapiandb ]]; then
#     mkdir -p ~/.local/share/recoll/xapiandb
# fi
# monitor "recollindex" recollindex -z

monitor "update-git" update ~/kadena ~/src ~/doc

monitor "nix-update" u vulcan update

if quickping $HERMES_ETHERNET; then
    monitor "push-hermes" push

    monitor "rebuild-athena" ssh hermes zsh -il -c "u hermes rebuild" &
fi

if quickping $ATHENA_ETHERNET; then
    monitor "push-athena" push athena

    monitor "rebuild-athena" ssh athena zsh -il -c "u athena rebuild" &
fi

if quickping $ATHENA_ETHERNET && ssh athena test -d /Volumes/tank/src/pushme ; then
    monitor "push-tank" push tank

    monitor "workspace-update" workspace-update
fi

wait
