#!/bin/bash

#Archives
for i in \
Backups \
Contracts \
Documents \
Downloads \
Machines \
Music \
Nasim \
Photos \
Pictures \
Products \
Projects \
Public \
Sites
do
    rsync -aP --delete --inplace "$@" \
      --exclude='/38*/' \
      --exclude='/Desktop DB' \
      --exclude='/Desktop DF' \
      --exclude='/TheVolumeSettingsFolder/' \
      --exclude='/lost+found/' \
      --exclude='/.Caches/' \
      --exclude='.DS_Store' \
      --exclude='/.Spotlight-V100/' \
      --exclude='/.TemporaryItems/' \
      --exclude='/.Trashes/' \
      --exclude='/.com.apple.timemachine.donotpresent' \
      --exclude='/.com.apple.timemachine.supported' \
      --exclude='/.fseventsd/' \
      --exclude='/Systems/' \
      --exclude='/Languages/SICP/' \
      --exclude='/Bizcard/' \
      --exclude='/ABC/' \
      --exclude='/iTunes/iTunes Media/TV Shows/' \
      --exclude='/iTunes/iTunes Media/Podcasts/' \
      /Volumes/RAID/$i/ /Volumes/USB1TB/$i/
done
