#!/usr/bin/env bash

mkdir -p ~/src/machines
cd ~/src/machines

rsync -av --delete ~/hera/ hera/
rsync -av --delete clio:clio/ clio/
rsync -av --delete athena:athena/ athena/
mkdir -p vulcan/etc/nixos
mkdir -p vulcan/var/lib
rsync -av --delete vulcan:/etc/nixos/ vulcan/etc/nixos/
rsync -av --delete vulcan:/var/lib/ vulcan/var/lib/
