#!/bin/bash -e

DIR=$1
REMOTE=athena
ISO=$(date --iso-8601=seconds)
STORE=${REMOTE}:/Volumes/tank/${DIR}/.borg

if ! ssh ${REMOTE} test -d /Volumes/tank/${DIR}/.borg; then
    borg init --encryption keyfile-blake2 $STORE
fi

exec borg create -s --progress ${STORE}::${ISO} ~/${DIR}
