#!/bin/bash -x

for repo in                                     \
    /tank/Archives                              \
    /tank/Backups/Misc                          \
    /tank/Media/Movies                          \
    /tank/Media/Music                           \
    /tank/Media/Photos                          \
    /tank/Media/Rentals
do
    cd $repo
    eval "$@"
done
