#!/bin/bash -x

for repo in                                     \
    /tank/Archives                              \
    /tank/Backups/Misc                          \
    /tank/Media/Movies                          \
    /tank/Media/Music                           \
    /tank/Media/Photos                          \
    /tank/Media/Pictures                        \
    /tank/Media/Rentals
do
    cd $repo

    git prune
    git gc
    git prune

    for i in hermes titan storage; do
        ssh -t $i "(cd $repo; git prune)"
        ssh -t $i "(cd $repo; git gc)"
        ssh -t $i "(cd $repo; git prune)"
    done

    git annex sync
    for i in hermes titan storage; do
        ssh -t $i "(cd $repo; git annex sync)"
    done

    git annex sync
    for i in hermes titan storage; do
        ssh -t $i "(cd $repo; git annex sync)"
    done

    git annex sync
    for i in hermes titan storage; do
        ssh -t $i "(cd $repo; git annex sync)"
    done

    git annex fsck 2>&1 | egrep --line-buffered -v '^fsck.*ok$'
    git annex fsck -A 2>&1 | egrep --line-buffered -v '^fsck.*ok$'
    git annex status
    git count-objects -v
    hammer .

    for i in hermes titan storage; do
        ssh -t $i "(cd $repo; git annex fsck)" 2>&1 | \
            egrep --line-buffered -v '^fsck.*ok$'
        ssh -t $i "(cd $repo; git annex fsck -A)" 2>&1 | \
            egrep --line-buffered -v '^fsck.*ok$'
        ssh -t $i "(cd $repo; git annex status)"
        ssh -t $i "(cd $repo; git count-objects -v)"
    done
done

touch bfsck.done
