#!/usr/bin/env bash

set -euo pipefail

for browser in                                  \
    Zotero                                      \
    Firefox                                     \
    Safari                                      \
    Brave\ Browser                              \
    Opera                                       \
    Vivaldi                                     \
    Thunderbird                                 \
    Tor\ Browser                                \
    DEVONagent
do
    open -j -g "/Applications/${browser}.app"
done
