#!/bin/bash -e

if [[ $1 = clean ]]; then
    find lib vignettes \( -name '*.glob' \
           -o -name '*.v.d' -o -name '*.vo' \
           -o -name '*.hi' -o -name '*.o' \
           -o -name '*.hp' -o -name '.*.aux' \) -type f -delete
    for i in coq-haskell bedrock fiat vignettes/bytestring ; do
        (cd $i ; load-env-$1 make clean)
    done
    for i in bedrock fiat ; do
        (cd $i ; git clean -dfx)
    done
else
    echo \#\#\# Building fiat \#\#\#
    (cd fiat ; load-env-$1 make -j16)
    echo \#\#\# Building coq-haskell \#\#\#
    (cd coq-haskell ; load-env-$1 make)
    echo \#\#\# Building bytestring \#\#\#
    (cd vignettes/bytestring ; load-env-$1 make)
    echo \#\#\# Building lib \#\#\#
    (cd lib ; load-env-$1 make) || exit 0
    echo \#\#\# Building simple_parser_fiat \#\#\#
    (cd vignettes/simple_parser_fiat ; load-env-$1 make)
fi
