#!/bin/bash

cd ~/fpco

do_pull () {
    if which git-smart-pull; then
        git smart-pull
    else
        git pull || (git fetch && tg update)
    fi
}

if [[ "$1" == --update ]]; then
    do_pull
    if [ -d learning-site/content ]; then
        (cd learning-site/content; do_pull)
    fi
    git clean -dfx
    ./dev-scripts/update-repo.sh
    find . -name config -type f                 \
        | xargs perl -i -pe                     \
            's%(git|https?)://github.com/(fpco|jwiegley)/%git\@github.com:\2/%;'
    find . -name '*.hs' | xargs hasktags -e -o - > TAGS
fi

cd ~/build/fpco

if [[ "$1" == --update ]]; then
    lndir -silent ~/fpco
    for gitDir in $(cd ~/fpco ; find . -name .git); do
        test -L ~/build/fpco/$gitDir \
            || ln -s ~/fpco/$gitDir ~/build/fpco/$(dirname $gitDir)
    done
fi

./dev-scripts/test-all.sh --ghc-option='-Wall'

source dev-scripts/activate-hsenv.sh

# RUNNER='if grep -q "^test" {} && test -d {//}/dist; then        \
#             (cd {//}; echo Testing {//} ; cabal test);          \
#         else                                                    \
#             exit 0;                                             \
#         fi'

# exec find ./ -name '*.cabal' -print0 \
#      | parallel -0 -j 16 --halt 0 "$RUNNER"
