#!/bin/bash -xe

cd ~/fpco

do_pull () {
    if which git-smart-pull
        then git smart-pull
        else git pull || (git fetch && tg update)
    fi
}

if [[ "$1" == --update ]]; then
    do_pull
    if [ -d learning-site/content ]; then
        (cd learning-site/content; do_pull)
    fi
    ./dev-scripts/update-repo.sh
fi

cd ~/build/fpco

./dev-scripts/test-all.sh

# RUNNER='if grep -q "^test" {} && test -d {//}/dist; then        \
#             (cd {//}; echo Testing {//} ; cabal test);          \
#         else                                                    \
#             exit 0;                                             \
#         fi'

# exec find ./ -name '*.cabal' -type f -print0 \
#      | parallel -0 -j 16 --halt 0 "$RUNNER"
