#!/bin/bash -xe

case $1 in
    ledger)
        mkdir -p ~/Products/ledger
        cd ~/Products/ledger
        load-env-ledger-py2                             \
            cmake ~/src/ledger                     \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=1       \
                -DCMAKE_C_COMPILER:PATH=gcc             \
                -DCMAKE_CXX_COMPILER:PATH=g++           \
                -DBUILD_DEBUG=1                         \
                -GNinja
        ninja -j4
        ctest
        ;;

    ledger-rtags)
        build ledger
        cd ~/Products/ledger
        rc -J .
        ;;

    concerto-txrx)
        cd ~/bae/concerto/solver
        make clean
        nix-shell --command "cabal build"
        ./dist/build/solver/solver --args test/TXRX.opts
        ;;

    haskell-z3)
        cd ~/src/haskell-z3
        cabal build
        ./dist/build/generate/generate --yaml generate/z3-api-4.5.0.yml
        ;;

    monitors)
        load-env-rings                                                          \
            make CC=clang                                                       \
                 PYTHONPATH=$(echo ~/bae/python/* ~/bae/atif-deliverable/monitors/smon/smedl | sed 's/ /:/g')
        ;;

    xhtml)
        make MACOS_NIX=true \
             MGEN="PYTHONPATH=$(echo ~/bae/python/* ~/bae/smedl | sed 's/ /:/g') python -m smedl.mgen" \
             clean location-scraper-d monitor
        ;;

    *)
        echo Unknown build command: "$@"
        ;;
esac
