#!/bin/bash -e

if [[ $1 = clean ]]; then
    for i in coq-haskell fiat ; do (cd $i ; git clean -dfx); done
else
    (cd fiat ; load-env-$1 make -j16)
    (cd coq-haskell ; load-env-$1 make)
    (cd lib ; load-env-$1 make) || exit 0
    (cd vignettes/simple_parser_fiat ; load-env-$1 make)
fi
