#!/usr/bin/env zsh

if (( $# > 0 )); then
    cmd=$1
    shift 1

    if [[ $cmd == install ]]; then
        exec ~/.cabal/bin/cabal $cmd -j --enable-library-profiling      \
            --haddock-hoogle --haddock-html --haddock-executables       \
            --haddock-internal --haddock-hyperlink-source "$@"
    else
        exec ~/.cabal/bin/cabal $cmd "$@"
    fi
else
    exec ~/.cabal/bin/cabal
fi
