#!/bin/bash

if [[ ! -d ~/Mirrors/Hackage/mirror.cfg ]]; then
    start-hackage
fi

#
cabal update

if [[ "$1" == "-a" ]]; then
    cab outdated | awk '{print $1}' | xargs cabal install -j
    for i in $(seq 0 20); do
        yes | cabal-delete $(cabal-delete -l | tail +3 | awk '{print $1}')
    done > /tmp/cabal-delete.log 2>&1

elif [[ "$1" == "--all" ]]; then
    cabal-reset.sh
    cabal-bootstrap.sh --full
fi

ghc-pkg check

if [[ "$1" == "--all" ]]; then
    rebuild-hoogle
fi

exit 0
