#!/bin/sh

echo "repo.url=$1"
echo "repo.name=$2"
echo "repo.desc=$3"
echo "repo.path=/srv/git/$1.git"
echo "repo.owner=John Wiegley"
echo "repo.defbranch=master                           ## define a default branch"
echo "repo.snapshots=tar.bz2                          ## override a sitewide snapshot-setting"
echo "#repo.readme=info/web/readme                    ## specify a file to include on summary page"
echo "repo.clone-url=git://newartisans.com/$1.git"
