#!/usr/bin/env bash

git add -A
git ls-files --deleted -z | while read -r file; do
    git rm "$file"
done
git commit --quiet --no-status -a -m "changes"

ONLINE=no
if quickping newartisans.hopto.org; then
    ONLINE=yes
fi

if [[ -d .git/annex/objects ]]; then
    if [[ $ONLINE == yes ]]; then
        git annex sync
    else
        git annex sync --no-push --no-pull
    fi
elif [[ $ONLINE == yes && -n $(git remote) ]]; then
    git push --quiet
fi
