#!/bin/bash

find . \( -name '*.js' -o -name '*.osl' -o -name '*.htm*' -o \
          -name '*.JS' -o -name '*.OSL' -o -name '*.HTM*' \) \
    -type f -print0 | xargs -0 ~/bin/print-links.pl |
    grep -v ^test_ > /tmp/out.$$

uniqify /tmp/out.$$

find . \( -name '*.js' -o -name '*.osl' -o -name '*.htm*' -o \
          -name '*.JS' -o -name '*.OSL' -o -name '*.HTM*' -o \
          -name '*.gif' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.tif' -o \
          -name '*.GIF' -o -name '*.JPG' -o -name '*.JPEG' -o -name '*.TIF' \) \
    -type f > /tmp/list.$$

for file in $(< /tmp/out.$$); do
    if ! grep -q $file /tmp/list.$$; then
	if ! grep -q -i $file /tmp/list.$$; then
	    echo MISSING: $file
	else
	    echo MISNAMED: $file
	fi
    fi
done | sort | uniq

rm -f /tmp/out.$$ /tmp/list.$$
