#!/bin/bash

set -e

if [[ -n "$1" ]]; then
    ROOT=$HOME/src/llvm/branches/$1
else
    ROOT=$HOME/src/llvm
fi

cd $ROOT && git pull
cd tools/clang && git pull
if [[ -d test/Embt ]]; then
    cd test/Embt && git pull
fi

if [[ $(basename "$ROOT") == llvm ]]; then
    cd ~/Products/llvm/main
else
    cd ~/Products/llvm/$(basename "$ROOT")
fi

/bin/rm -fr *
nice -n 20 cmake -DLLVM_TARGETS_TO_BUILD:=X86 $ROOT

if ! nice -n 20 make-distcc; then
    notify "Clang failed to build"
else
    if ! nice -n 20 make clang-test; then
        notify "Clang failed tests"
    fi
fi

exit 0
