#!/bin/bash

set -e

rebuild=true
if [[ "$1" == "-s" ]]; then
    rebuild=false
    shift 1
fi

if [[ -n "$1" ]]; then
    ROOT=$HOME/src/llvm/branches/$1
else
    ROOT=$HOME/src/llvm
fi

if quickping bite.entic.net; then
    cd $ROOT && git pull
    cd tools/clang && git pull
    if [[ -d test/Embt ]]; then
        cd test/Embt && git pull
    fi
fi

if [[ $(basename "$ROOT") == llvm ]]; then
    PRODUCTS=$HOME/Products/llvm/main
else
    PRODUCTS=$HOME/Products/llvm/$(basename "$ROOT")
fi
cd "$PRODUCTS"

if [[ $rebuild == true || ! -f "$PRODUCTS/Makefile" ]]; then
    /bin/rm -fr *
    nice -n 20 cmake -DLLVM_TARGETS_TO_BUILD:=X86 $ROOT
fi

if ! nice -n 20 make-distcc; then
    echo "Clang failed to build"
    exit 1
else
    if ! nice -n 20 make clang-test; then
        echo "Clang failed tests"
        exit 2
    fi
fi

exit 0
