#!/bin/bash

set -e

if [[ -n "$1" ]]; then
    ROOT=$HOME/src/corp/embt/branches/$1
else
    ROOT=$HOME/src/corp/embt/llvm
fi

if [[ $(basename "$ROOT") == llvm ]]; then
    PRODUCTS=$HOME/Products/llvm/main
else
    PRODUCTS=$HOME/Products/llvm/$(basename "$ROOT")
fi
cd "$PRODUCTS"

if [[ $rebuild == true || ! -f "$PRODUCTS/Makefile" ]]; then
    /bin/rm -fr *
    nice -n 20 cmake                                            \
        -DCMAKE_BUILD_TYPE:=Debug                               \
        -DLLVM_TARGETS_TO_BUILD:=X86                            \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/stow/clang       \
        $ROOT
fi

exit 0

### clangup-clean ends here
