#!/bin/sh

#sudo pdnsd-ctl -c ~/Library/Caches/pdnsd empty-cache .ti.com
#sudo pdnsd-ctl -c ~/Library/Caches/pdnsd server ti retest

sudo pdnsd-ctl -c ~/Library/Caches/pdnsd server opendns retest
sudo pdnsd-ctl -c ~/Library/Caches/pdnsd server google retest
sudo pdnsd-ctl -c ~/Library/Caches/pdnsd server dyndns retest

sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder

sudo pdnsd-ctl -c ~/Library/Caches/pdnsd status \
     | egrep -i '(server (assumed|[0-9])|label)'
