#!/bin/bash

find "$@" \( \( -type f                         \
             \( -name '.ghc.*'                  \
             -o -name 'cabal.project.local*'    \
             \)                                 \
          \)                                    \
       -o \( -type d                            \
             \( -name '.ghc.*'                  \
             -o -name 'dist'                    \
             -o -name 'dist-newstyle'           \
             \)                                 \
          \)                                    \
       -o \( -type l                            \
             \( -name 'result'                  \
             -o -name 'result-*'                \
             \)                                 \
          \)                                    \
       -o \( -type f                            \
             \( -name '.envrc.cache'            \
             \)                                 \
          \)                                    \
       -o \( -type d                            \
             \( -name '.direnv'                 \
             -o -name '.vagrant'                \
             \)                                 \
          \)                                    \
       -o \( -type d                            \
             \( -name '.cargo-home'             \
             -o -name 'target'                  \
             \)                                 \
          \)                                    \
       -o \( -type f                            \
             \( -name '*~'                      \
             \)                                 \
          \)                                    \
       \)                                       \
    -print0 |                                   \
    if [[ $1 == "-n" ]]; then                   \
        parallel -0 ls -ld;                     \
    else                                        \
        parallel -0 --xargs rm -fr;             \
    fi
