#!/usr/bin/env python

import csv
import sys

reader = csv.reader(open(sys.argv[1]))

rows = {}

firstRow = None

for row in reader:
    if not firstRow:
        firstRow = row
        continue

    key = row[2] + row[3]
    if key not in rows:
        rows[key] = row

writer = csv.writer(open(sys.argv[2], 'w'), quoting=csv.QUOTE_ALL)

writer.writerow(firstRow)

for row in rows.values():
    writer.writerow(row)
