#!/usr/bin/env bash

dryrun=false
if [[ $1 == "-n" ]]; then
    dryrun=true
    shift 1
fi

find "$@" \(                                    \
          \( -type d                            \
             \( -name '.ghc.*'                  \
             -o -name '.cargo'                  \
             -o -name '.cargo-home'             \
             -o -name '.coq-native'             \
             -o -name '.direnv'                 \
             -o -name '.ghcup'                  \
             -o -name '.mypy_cache'             \
             -o -name '.pytest_cache'           \
             -o -name '.rustup'                 \
             -o -name '.taskmaster'             \
             -o -name '.venv'                   \
             -o -name 'MAlonzo'                 \
             -o -name '__pycache__'             \
             -o -name '_deps'                   \
             -o -name 'dist'                    \
             -o -name 'dist-newstyle'           \
             -o -name 'gen'                     \
             -o -name 'ghc[0-9_]*'              \
             -o -name 'node_modules'            \
             -o -name 'target'                  \
             \)                                 \
          \)                                    \
       -o \( -type f                            \
             \( -name '.ghc.*'                  \
             -o -name '.*emacs-dev*'            \
             -o -name '*.agdai'                 \
             -o -name '*.cma'                   \
             -o -name '*.cmi'                   \
             -o -name '*.cmo'                   \
             -o -name '*.cmx'                   \
             -o -name '*.cmxa'                  \
             -o -name '*.cmxs'                  \
             -o -name '*.elc'                   \
             -o -name '*.glob'                  \
             -o -name '*.hi'                    \
             -o -name '.lia.cache'              \
             -o -name '.lra.cache'              \
             -o -name '.nia.cache'              \
             -o -name '.nra.cache'              \
             -o -name '*.lia-cache'             \
             -o -name '*.lra-cache'             \
             -o -name '*.nia-cache'             \
             -o -name '*.nra-cache'             \
             -o -name '*.v.d'                   \
             -o -name '*.v.tex'                 \
             -o -name '*.vio'                   \
             -o -name '*.vo'                    \
             -o -name '*.vok'                   \
             -o -name '*.vos'                   \
             -o -name '*~'                      \
             -o -name '.*.aux'                  \
             -o -name '.Makefile.coq.d'         \
             -o -name '.envrc.cache'            \
             -o -name 'Makefile.coq'            \
             -o -name 'Makefile.coq.conf'       \
             -o -name 'cabal.project.local*'    \
             \)                                 \
          \)                                    \
       -o \( -type l                            \
             \( -name 'result'                  \
             -o -name 'result-*'                \
             \)                                 \
          \)                                    \
       \)                                       \
    -print0 |                                   \
    if [[ $dryrun == true ]]; then              \
        parallel -0 ls -ld;                     \
    else                                        \
        parallel -0 --xargs /bin/rm -fr;        \
    fi
