#!/bin/zsh

for fs in "$@"; do
    mountpoint=$(zfs get -H -o value mountpoint $fs)
    snapshot="$mountpoint/.zfs/snapshot"
    entries=$(ls -1 "$snapshot" | wc -l)
    for rev in $(ls -1 "$snapshot" | sort -n | head -$((entries - 2))); do
        sudo zfs destroy -r $fs@$rev
    done
done
