#!/bin/bash

packmail

if [[ $1 == --heavy ]]; then
    (cd ~/Messages/Maildir ; git flush)
    linkdups ~/Messages/Maildir
fi

for i in comp gmane gnu; do
    if [[ -d ~/.emacs.d/mirror/Usenet/$i/emacs ]]; then
        rsync -a ~/Messages/Newsdir/$i/emacs/ \
            ~/.emacs.d/mirror/Usenet/$i/emacs/
    fi
done

for i in wg21/c++ comp/std/c++ comp/lang/c++; do
    if [[ -d ~/Archives/Languages/C++/Usenet/$i ]]; then
        rsync -a ~/Messages/Newsdir/$i/ \
            ~/Archives/Languages/C++/Usenet/$i/
    fi
done

texpire -vvv -f -n -r
texpire -vvv -f

mairix -F

### cleanup-mail ends here