#!/bin/bash

COMMENT="Snapshot $(date +'%Y-%m-%d %H:%M:%S')"

echo Committing in ~/bin ...
(cd ~/bin; hg -q commit -m "$COMMENT")
echo Committing in ~/Documents ...
(cd ~/Documents; hg -q commit -m "$COMMENT")
echo Committing in ~/Library/Emacs ...
(cd ~/Library/Emacs; hg -q commit -m "$COMMENT")

for dir in ~/Projects/*/.hg; do
    SRCDIR=$(dirname "$dir")
    echo Committing in $SRCDIR ...
    (cd "$SRCDIR"; hg -q commit -m "$COMMENT")
done
