#!/bin/bash

COMMENT="Snapshot $(date +'%Y-%m-%d %H:%M:%S')"

(cd ~/bin; hg commit -m "$COMMENT")
(cd ~/Documents/Accounts; hg commit -m "$COMMENT")
(cd ~/Documents/Pending; hg commit -m "$COMMENT")
(cd ~/Documents/Writings; hg commit -m "$COMMENT")
(cd ~/Library/Emacs; hg commit -m "$COMMENT")
