#!/bin/bash -xe

open /Applications/Calendar.app
open /Applications/Day\ One.app
(open /Applications/Dragon\ Dictate.app || exit 0)
open /Applications/EmacsAlt.app
open /Applications/Messages.app
#open /Applications/Misc/Clarify.app
open /Applications/Misc/Deskzilla\ Lite.app
#open /Applications/Misc/ExpanDrive.app
#open /Applications/Misc/GitHub.app
open /Applications/Misc/Path\ Finder.app
open /Applications/Misc/QuicKeys.app
#open /Applications/Misc/ScreenSharingMenulet.app
open /Applications/Twitter.app
open ~/Documents/Notes/Notes.tbx

exit 0
