#!/bin/bash -xe

open /Applications/Calendar.app
#open /Applications/Day\ One.app
open /Applications/Dragon\ Dictate.app
#open ~/.nix-profile/Applications/Emacs.app
open /Applications/EmacsAlt.app
#open /Applications/Evernote.app
#open /Applications/Growl.app
open /Applications/Messages.app
#open /Applications/Misc/Clarify.app
open /Applications/Misc/Deskzilla\ Lite.app
#open /Applications/Misc/ExpanDrive.app
#open /Applications/Misc/Fantastical.app
#open /Applications/Misc/Firefox.app
#open /Applications/Misc/GitHub.app
open /Applications/Misc/Path\ Finder.app
open /Applications/Misc/QuicKeys.app
#open /Applications/Misc/ScreenSharingMenulet.app
#open /Applications/Misc/Skype.app
open /Applications/Twitter.app

exit 0
