#!/bin/bash -xe

open /Applications/EmacsAlt.app
open /Applications/Messages.app
open /Applications/Misc/DropBox.app
open /Applications/Misc/ExpanDrive.app
open /Applications/Misc/GitHub.app
open /Applications/Misc/NetNewsWire.app
open /Applications/Misc/ScreenSharingMenulet.app
open /Applications/Misc/Shimo.app
open /Applications/Misc/Skype.app
open /Applications/Safari.app
open /Applications/Twitter.app

exit 0
