#!/bin/sh
#
# Filename: contacts2bbdb.sh
# Description: Converts addresses from OSX Addressbook.app to BBDB format
# Author: Anupam Sengupta (anupamsg@gmail.com)
# Maintainer: Anupam Sengupta
#
# (c) 2007-2016 Anupam Sengupta.
#
# Created: Fri May 25 15:53:22 2007
# Version: 1.0
# Last-Updated:
# By: Anupam Sengupta
# Update #: 740
# URL: http://slashusr.wordpress.com
# Keywords: `BBDB’, ‘OSX’, ‘contacts’, ‘convert’
# Compatibility: GNU Emacs 21 and above
#
#--------------------------------------------------------------------
#
# Commentary:
#
# Runs the export of OS X Address Book contacts to the Emacs BBDB file.
#
# Requires:
# 1. The contacts2bbdb.rb Ruby script
# (http://slashusr.wordpress.com/)
# 2. The Ruby interpreter (Version 1.8 and above)
# (http://www.ruby-lang.org/)
# 3. The Big Brother Database (BBDB) Emacs Package
# (http://bbdb.sourceforge.net/)
# 4. The contacts command line program to extract the records
# (http://gnufoo.org/contacts/)
#
# Usage:
# 1. Backup the Addressbook.app’s addresses
# 2. Install BBDB and ‘contacts’, if not already present
# 3. Edit the BBDBDIR and RUBYPROG variables below
# 4. Open Terminal.app and run this script
# 5. The script will also create a backup of the previous bbdb file
#
#
#
# TODO: Edit these variables to match the file locations
BBDBDIR=$HOME # Edit this to match location of the bbdb file
BBDBFILE=.bbdb # Edit this to match your bbdb file name
RUBYPROG=$HOME/bin/contacts2bbdb.rb # Name and loction of the Ruby Script
#
####################################### Do not edit beyond this point !
#
RUBYEXEC=`which ruby`
#
if [ -x ${RUBYEXEC} ]; then
    cp ${BBDBDIR}/$BBDBFILE ${BBDBDIR}/bbdb.bak
    ${RUBYEXEC} ${RUBYPROG} > $BBDBDIR/$BBDBFILE
fi
echo “BBDB Export and conversion completed.”
#
# End of contacts2bbdb.sh