#!/bin/bash

cat .gitmodules | while read module
do
    if [[ $module == \[submodule* ]]; then
        mpath=$(echo $module | cut -d\" -f2)
        read module; read module;
        murl=$(echo $module | cut -d\  -f3)
        mcommit=`eval "git submodule status ${mpath} | cut -d\  -f2"`
        mname=$(basename $mpath)
        # echo -e "$name\t$mpath\t$murl\t$mcommit"
        if [[ -z "$mcommit" ]]; then
            echo MISSING: $mpath
        else
            mv $mpath ${mpath}.prev
            git submodule deinit $mpath
            git rm --cached $mpath
            rm -fr $mpath
            git commit -a -m "Remove submodule $mpath"
            # git remote add -f ext/$mname $murl
            git subtree add --prefix $mpath ext/$mname $mcommit --squash
            rsync -av --exclude=.git/ --exclude=.git ${mpath}.prev/ $mpath/
            rm -fr ${mpath}.prev
        fi
    fi
done
echo git rm .gitmodules

# To update later, after git fetch --all
# git subtree pull --prefix $mpath ext/$mname master --squash
