#!/bin/bash

operation=duplicate
if [[ $1 == '-m' ]]; then
    operation=move
    shift 1
fi

type=file
if [[ -d "$1" ]]; then
    type=folder
fi

osascript <<EOF > /dev/null
  tell application "Finder"
    set theSource to POSIX file "$(abspath "$1")"
    set theDest to POSIX file "$(abspath "$2")"
    $operation $type theSource to alias theDest replacing true
  end tell
EOF
