#!/bin/bash

# zpool create                                            \
#       -f                                                \
#       -o ashift=12                                      \
#       -O checksum=sha256                                \
#       -O casesensitivity=insensitive                    \
#       -O atime=off                                      \
#       -O normalization=formD                            \
#       -O compression=lz4                                \
#       tank                                              \
#       mirror ata-ST3000DM001-1CH166_Z1F4B95C            \
#              ata-ST3000DM001-1ER166_Z5004TVT            \
#              ata-WDC_WD30EFRX-68AX9N0_WD-WMC1T2920326   \
#       mirror ata-ST3000DM001-1ER166_Z501M1F8            \
#              ata-WDC_WD30EFRX-68AX9N0_WD-WMC1T3310080   \
#              ata-WDC_WD30EFRX-68AX9N0_WD-WMC1T3312925   \
#       mirror ata-ST3000DM001-1CH166_Z1F4BARW            \
#              ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N0434075   \
#              ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N0435061

# ssh titan zfs create tank/Archives
# ssh titan zfs create tank/Audio
# ssh titan zfs create tank/Backups
# ssh titan zfs create tank/Backups/CrashPlan
# ssh titan zfs create tank/Backups/Images
# ssh titan zfs create tank/Backups/Misc
# ssh titan zfs create tank/Backups/Servers
# ssh titan zfs create tank/Backups/System
# ssh titan zfs create tank/Backups/System/Applications
# ssh titan zfs create tank/Backups/System/Home
# ssh titan zfs create tank/Backups/System/Library
# ssh titan zfs create -o copies=2 tank/Contracts
# ssh titan zfs create -o copies=2 tank/Databases
# ssh titan zfs create -o copies=2 tank/Desktop
# ssh titan zfs create -o copies=2 tank/Documents
# ssh titan zfs create tank/Downloads
# ssh titan zfs create -o copies=2 tank/Dropbox
# ssh titan zfs create tank/Games
# ssh titan zfs create tank/Machines
# ssh titan zfs create tank/Media
# ssh titan zfs create -o copies=2 tank/Messages
# ssh titan zfs create tank/Movies
# ssh titan zfs create tank/Nasim
# ssh titan zfs create tank/Photos
# ssh titan zfs create tank/Pictures
# ssh titan zfs create -o copies=2 tank/Projects
# ssh titan zfs create tank/Rentals
# ssh titan zfs create tank/iTunes

# ssh titan chown -R johnw /tank

for i in                                        \
    Archives                                    \
    Audio                                       \
    Contracts                                   \
    Databases                                   \
    Desktop                                     \
    Documents                                   \
    Downloads                                   \
    Dropbox                                     \
    Games                                       \
    Machines                                    \
    Messages                                    \
    Pictures                                    \
    Projects                                    \
    Photos                                      \
    Media                                       \
    Rentals                                     \
    Movies                                      \
    Backups/Misc                                \
    Backups/Servers                             \
    Backups/System/Applications                 \
    Backups/System/Home                         \
    Backups/System/Library                      \
    iTunes                                      \
    Nasim                                       \
    Backups/Images
do
    volcopy -av --delete /Volumes/mybook/$i/ titan:/tank/$i/
done
