#!/bin/bash

if [[ "$1" == "titan" ]]; then
    ln -sf /Library/Application\ Support/CrashPlan/ui_johnw.properties.titan \
        /Library/Application\ Support/CrashPlan/ui_johnw.properties
    ln -sf /Library/Application\ Support/CrashPlan/ui_info.titan \
        /Library/Application\ Support/CrashPlan/.ui_info
else
    ln -sf /Library/Application\ Support/CrashPlan/ui_johnw.properties.self \
        /Library/Application\ Support/CrashPlan/ui_johnw.properties
    ln -sf /Library/Application\ Support/CrashPlan/ui_info.self \
        /Library/Application\ Support/CrashPlan/.ui_info
fi

exec /Applications/CrashPlan.app/Contents/MacOS/CrashPlan
