#!/usr/bin/env bash

if [[ ! -d .git ]]; then
    git init
    git add .
    git commit -m "Initial revision"
fi

exec gh repo create "$1" \
	--source=. \
	--description "$2" \
	--public \
	--remote=origin \
	--disable-wiki \
	--push
