#!/bin/bash

IMAP=$HOME/.nix-profile/libexec/dovecot/imap

python3 ~/src/IMAPdedup/imapdedup.py            \
  -P "$IMAP -c /etc/dovecot/dovecot.conf"       \
  -u johnw -w pass -S -c -m                     \
  mail.kadena                                   \
  mail.kadena.archive                           \
  INBOX                                         \
  Drafts                                        \
  list.kadena                                   \
  list.kadena.amazon                            \
  list.kadena.asana                             \
  list.kadena.bill                              \
  list.kadena.calendar                          \
  list.kadena.expensify                         \
  list.kadena.github                            \
  list.kadena.google                            \
  list.kadena.greenhouse                        \
  list.kadena.immunefi                          \
  list.kadena.justworks                         \
  list.kadena.lattice                           \
  list.kadena.notion                            \
  list.kadena.slack                             \
  list.finance                                  \
  list.types                                    \
  list.ledger                                   \
  list.haskell.cloud                            \
  list.haskell.prime                            \
  list.haskell.infrastructure                   \
  list.haskell.hackage-trustees                 \
  list.haskell.committee                        \
  list.haskell.commercial                       \
  list.haskell.libraries                        \
  list.haskell.ghc                              \
  list.haskell.ghc.linker                       \
  list.haskell.ghc.devel                        \
  list.haskell.community                        \
  list.haskell.cafe                             \
  list.haskell.cabal                            \
  list.haskell.beginners                        \
  list.haskell.announce                         \
  list.haskell.admin                            \
  list.gnu                                      \
  list.gnu.prog                                 \
  list.gnu.prog.discuss                         \
  list.gnu.debbugs                              \
  list.emacs.org-mode                           \
  list.emacs.sources                            \
  list.emacs.proofgeneral                       \
  list.emacs.manual                             \
  list.emacs.conf                               \
  list.emacs.elpa.diffs                         \
  list.emacs.help                               \
  list.emacs.bugs                               \
  list.emacs.tangents                           \
  list.emacs.devel                              \
  list.emacs.devel.owner                        \
  list.emacs.announce                           \
  list.emacs.orgmode                            \
  list.coq                                      \
  list.coq.fiat                                 \
  list.coq.ssreflect                            \
  list.coq.deepspec                             \
  list.coq.devel                                \
  list.coq-devs                                 \
  list.bahai                                    \
  list.bahai.ror                                \
  list.bahai.ctg                                \
  list.bahai.ctg.sunday                         \
  list.bahai.anti-racism                        \
  list.bahai.tarjuman                           \
  list.bahai.srp                                \
  list.bahai.study                              \
  list.gsoc.mentors                             \
  mail.archive                                  \
  mail.spam                                     \
  mail.spam.report                              \
  mail.trash                                    \
  mail.sent                                     \
  mail.pending                                  \
  list.github                                   \
  list.notifications                            \
  list.misc                                     \
  mail.gmail                                    \
  mail.gmail.sent                               \
  mail.gmail.kadena                             \
  mail.gmail.c2g

for i in $(msgcounts | field 1 | tail -n +2)
do
    doveadm expunge mailbox $i DELETED
done
