#!/bin/bash

# This is a rather brainless replacement for rm that moves files to
# the Trash instead of deleting them right away.

if pwd | grep -q /Volumes/; then
    exec /bin/rm "$@"
else
    while echo "$1" | grep -q '^-'; do
	shift 1
    done

    for file in "$@"; do
	if [[ -L "$file" ]]; then
	    /bin/rm "$file"
	elif echo "$file" | grep -q /Volumes/; then
	    exec /bin/rm "$file"
	elif [[ -e "$file" ]]; then
	    target=$(basename "$file")
	    index=$$
	    while [[ -e "$HOME/.Trash/$target" ]]; do
		target=$(basename "$file")-$index
		index=$((index + 1))
	    done
	    /bin/mv "$file" "$HOME/.Trash/$target" 2>&1
	fi
    done | grep -v "set owner/group.*Operation not permitted"

    exit 0
fi
