#!/bin/bash
sort=""
if [[ "$1" == "-s" ]]; then
    sort="-s used"
    shift
elif [[ "$1" == "-S" ]]; then
    sort="-s refer"
    shift
fi
exec zfs list -o name,used,avail,refer,compressratio,mounted -t filesystem $sort "$@"
