#!/usr/bin/env bash

if ! command -v zfs > /dev/null 2>&1; then
    echo "ERROR: ZFS not installed on this system"
    exit 1
fi

sort=""
type="filesystem,volume"
fields="name,used,refer,avail,compressratio,mounted"

if [[ "$1" == "-u" ]]; then
    sort="-s used"
    shift
elif [[ "$1" == "-s" ]]; then
    type="snapshot"
    fields="name,refer,creation"
    shift
elif [[ "$1" == "-r" ]]; then
    sort="-s refer"
    shift
fi

exec zfs list -o $fields -t $type $sort "$@"
