#!/bin/bash

sort=""
type="filesystem,volume"
fields="name,used,refer,avail,compressratio,mounted"

if [[ "$1" == "-u" ]]; then
    sort="-s used"
    shift
elif [[ "$1" == "-s" ]]; then
    type="snapshot"
    fields="name,refer,creation"
    shift
elif [[ "$1" == "-r" ]]; then
    sort="-s refer"
    shift
fi

exec zfs list -o $fields -t $type $sort "$@"
