#!/bin/bash -xe

function quitapp() {
    tell application "$1" to quit
}

quitapp Calendar
quitapp Day\ One
quitapp Emacs
quitapp EmacsAlt
#quitapp Growl
quitapp Messages
#quitapp Clarify
quitapp Deskzilla\ Lite
quitapp DropBox
quitapp Dropzone
#quitapp ExpanDrive
#quitapp Fantastical
quitapp Firefox
quitapp GitHub
quitapp LittleSnapper
quitapp NetNewsWire
quitapp Path\ Finder
quitapp QuicKeys
quitapp ScreenSharingMenulet
quitapp Shimo
quitapp Skype
quitapp Pocket
quitapp Reminders
quitapp Safari
#quitapp ScreenFlow
quitapp Twitter

exit 0
