#!/bin/bash

launchctl limit maxproc 512

export CCACHE_PREFIX=distcc
export DISTCC_DIR=$HOME/.distcc
export DISTCC_SSH=ssh
export DISTCC_FALLBACK=0
#export DISTCC_VERBOSE=1

find-env > /tmp/env.$$
source /tmp/env.$$
rm -f /tmp/env.$$

exec /opt/local/bin/distcc "$@"
