#!/bin/sh

name="$1"
shift

if [ -f "$name" ]; then
    dosbox -conf $HOME/.dosboxrc "$name" -exit "$@"
elif [ -d "$name" ]; then
    if [ ! -d /tmp/DosData ]; then
	mkdir /tmp/DosData
    fi
    dosbox -conf $HOME/.dosboxrc "$name" -c "mount d /tmp/DosData" "$@"
else
    echo $name is invalid!
fi
