#!/usr/bin/env python

import sys
import os

from os.path import abspath

app = "/Applications/Misc/DeltaWalker.app/Contents/MacOS/DeltaWalker"

if len(sys.argv) > 3:
    os.execl(app, app, abspath(sys.argv[2]), abspath(sys.argv[1]),
             abspath(sys.argv[3]))
else:
    os.execl(app, app, abspath(sys.argv[1]), abspath(sys.argv[2]))
