#!/usr/bin/env python

import re
import sys

from subprocess import *

p = Popen("pylint -f parseable -r n --disable-msg=W0702,W0703,W0142,W0141,W0603 --disable-msg-cat=C,R %s" %
          sys.argv[1], shell = True, stdout = PIPE).stdout

for line in p:
    match = re.search("\\[([WE])(, (.+?))?\\]", line)
    if match:
        kind = match.group(1)
        func = match.group(3)

        if func:
            line = re.sub("\\[([WE])(, (.+?))?\\]",
                          "%s (%s):" % ("Warning" if kind == "W" else "Error",
                                        func), line)
        else:
            line = re.sub("\\[([WE])?\\]",
                          "Warning:" if kind == "W" else "Error:", line)
    print line,

p.close()
