#!/bin/bash -x

cmds=""
while [[ "$1" != "--" ]]; do
    cmds="$cmds $1"
    shift 1
done

if [[ "$1" == "--" ]]; then
    shift 1
fi

find . $cmds -type f -print0 | xargs -P4 -0 egrep -nH "$@"
#find . $cmds -type f -print0 | xargs -P4 -0 cgrep --color "$@"
