#!/usr/bin/bash

cat > /data/MANIFEST.txt < /dev/null

for fs in $(zfs list -o mountpoint -H -r data); do
    if [[ "$fs" != "none" ]]; then
        if [[ "$fs" != "/data/Backups/TimeMachine" \
           && "$fs" != "/data/Mail" ]]; then
            find "$fs" -type f >> /data/MANIFEST.txt
            find "$fs"/.zfs -type f >> /data/MANIFEST.txt
        fi
    fi
done
