#!/bin/bash

LOCAL=$(ipaddr bond0 2> /dev/null)
if [[ -z "$LOCAL" ]]; then
    LOCAL=$(ipaddr en0 2> /dev/null)
fi
if [[ -z "$LOCAL" ]]; then
    LOCAL=$(ipaddr en1 2> /dev/null)
fi

if [[ "$LOCAL" == 192.168.1.69 ]]; then
    echo 'JOBS=-j22'
    echo 'laptop=false'

    if quickping 192.168.1.73; then
        echo 'found=true'
        echo 'REMOTE=hermes'
        echo 'export DISTCC_HOSTS="localhost/12 @hermes/4"'
    else
        echo 'found=false'
        echo 'JOBS=-j18'
        echo 'export DISTCC_HOSTS="localhost/16"'
    fi
else
    echo 'JOBS=-j18'
    echo 'laptop=true'

    if quickping 192.168.1.69; then
        echo 'found=true'
        echo 'REMOTE=vulcan'
        echo 'export DISTCC_HOSTS="localhost/4 @vulcan/16"'
    else
        echo 'found=false'
        echo 'JOBS=-j6'
        echo 'export DISTCC_HOSTS="localhost/4"'
    fi
fi

exit 0
