#!/bin/bash

LIMIT=50

sqlite3 -noheader -list ~/Messages/Envelope\ Index \
"
SELECT DISTINCT
    address
FROM
    (
            SELECT DISTINCT
                lower(a.address) AS address,
                m.date_received  AS date_received
            FROM
                addresses AS a,
                messages  AS m
            WHERE
                m.sender = a.rowid
            AND (
                    a.address LIKE '%$1%'
                OR  a.comment LIKE '%$1%'
                )

        UNION

            SELECT DISTINCT
                lower(a.address) AS address,
                m.date_received  AS date_received
            FROM
                addresses  AS a,
                messages   AS m,
                recipients AS r
            WHERE
                m.rowid      = r.message_id
            AND r.address_id = a.rowid
            AND (
                    a.address LIKE '%$1%'
                OR  a.comment LIKE '%$1%'
                )

        ORDER BY
            m.date_received DESC

        LIMIT $LIMIT
    )
"
