#!/bin/sh

account=$1
server=$2
protocol=$3
port=$4

security find-internet-password -g -a $account \
	 -P $port -r $protocol -s $server \
	 ~/Library/Keychains/johnw.keychain 2>&1 | \
	 grep ^password | sed -e 's/^password: "//' -e 's/"$//'
