#!/usr/bin/env bash

for i in "$@" ; do
    work fix-${i}
    ( cd fix-${i} ;                             \
      de ;                                      \
      direnv allow . ;                          \
      spawn "ai --model sonnet '/fix $i'")
done
