#!/usr/bin/env ruby

ARGV.each do |dir|
  mtime = Time.at(0)

  Dir.entries(dir).each { |entry|
    if entry != "." and entry != ".."
      file_mtime = File.mtime(File.join(dir, entry))
      if file_mtime > mtime
        mtime = file_mtime
      end
    end
  }

  if mtime != Time.at(0)
    File.utime(mtime, mtime, dir)
  end
end
