#!/bin/zsh

chkarch=$1
outarch=$2
shift 2

for appdir in "$@"; do
    for execfile in "$appdir"/**/Contents/MacOS/**/*(*); do
	if lipo -info "$execfile" | \
	   grep -q "Architectures in the fat file:.*$chkarch"; then
	    base=$(basename "$execfile")
	    lipo -thin $outarch -output "/tmp/$base" "$execfile" && \
		mv "/tmp/$base" "$execfile" && \
		echo M "$execfile"
	fi
    done

    for langdir in "$appdir/Contents/Resources"/**/*.lproj(/); do
	base=$(basename "$langdir")
	if [ ! "$base" = "English.lproj" -a \
	     ! "$base" = "en.lproj" ]; then
	    rm -fr "$langdir" && echo D "$langdir"
	fi
    done
done
