#!/bin/bash

exec hours "$@"                                 \
    --file ~/doc/Tasks/todo.txt                 \
    --category complete                         \
    --archive ~/doc/Tasks/FPComplete.txt        \
    --gratis 8
