#!/bin/bash
where=$1
shift 1
git annex copy -c annex.alwayscommit=false --not --in $where --to $where "$@"
git annex copy -c annex.alwayscommit=false -U --not --in $where --to $where "$@"
git annex sync
