#!/usr/bin/env bash -e

changes

for remote in $(git remote); do
    if [[ $PWD =~ /org || $remote != clio ]]; then
        git annex sync $remote --content --all
    fi

    if [[ $remote != backblaze ]]; then
        host=$remote
        dir=$PWD

        if [[ $host == tank ]]; then
            host=clio
            dir=/Volumes/tank/$(echo $PWD | sed 's%/Users/johnw/%%')
        fi

        if [[ $PWD =~ /org || $remote != tank ]]; then
            ssh $host "(cd $dir; git annex sync --no-push --no-pull)"
        fi
    fi
done
