#!/usr/bin/env bash -e

changes

for remote in $(git remote); do
    git annex sync $remote --content --all

    if [[ $remote != backblaze ]]; then
        host=$remote
        dir=$PWD

        if [[ $host == tank ]]; then
            host=athena
            dir=/Volumes/tank/$(echo $PWD | sed 's%/Users/johnw/%%')
        fi

        ssh $host "(cd $dir; git annex sync --no-push --no-pull)"
    fi
done
