#!/bin/bash

TMP=$HOME/tmp/Haddock

test -d $TMP/log || mkdir $TMP/log
test -d $TMP/src || mkdir $TMP/src

find ~/Mirrors/Hackage/archive/package -name '*.tar.gz' -type f | \
while read pkg; do
    cd $TMP/src
    dir=$(una $pkg 2>&1)
    if [[ $? == 0 ]]; then
        dir=$(echo "$dir" | sed 's/Extracted directory: //')
        cd "$dir"

        if ! cabal-dev -s $TMP install -j                       \
                --haddock-hoogle --haddock-html                 \
                --haddock-internal --haddock-hyperlink-source   \
                > "$TMP/log/$dir.log" 2>&1
        then
            echo "Failed to build $dir"
        else
            echo "Built $dir"
        fi

        rm -fr $TMP/packages* $TMP/lib
    fi
done
