#!/bin/bash

if ! running fetchmail; then
    getmail &
fi

(cd ~/.emacs.d/mirror/Marmalade ; httrack -X0 --update) &

git all --fetchonly ~/Archives ~/Projects ~/Contracts ~/.emacs.d &

sudo port selfupdate
sudo port fetch outdated
sudo port -p mirror all

wait

(cd ~/.emacs.d/mirror/EmacsWiki ; git reset --hard origin/master)
(cd ~/.emacs.d/mirror/Worg      ; git reset --hard origin/master)

### getall ends here
