#!/bin/sh

org2tc /Users/johnw/doc/Tasks/todo.txt \
    | ledger -f - --day-break print \@BAE > /tmp/BAE.dat
org2tc /Users/johnw/doc/Tasks/BAE.txt \
    | ledger -f - --day-break print >> /tmp/BAE.dat

echo
echo Daily totals
echo ======================================================================

ledger -f /tmp/BAE.dat --weekly \
    -p "$1" --columns=62 --day-break --sort date reg

echo
echo Weekly total
echo ======================================================================

ledger -f /tmp/BAE.dat --weekly \
    -p "$1" --columns=62 --day-break --sort date bal

exit 0
