#!/bin/bash

#start-mail; sleep 60

#sudo sa-update-5.12 --no-gpg &
#sudo freshclam &

#wait

fetchmail
FETCHMAILHOME=$HOME/Messages/Newsdir fetchmail -f ~/Messages/fetchmailrc.lists
#FETCHMAILHOME=$HOME/Messages/Maildir fetchmail -f ~/Messages/fetchmailrc.spam

fetchnews -d ~/Messages/Newsdir -F ~/Messages/leafnode/config -vvv -n

#doveadm -v purge
#doveadm -v index '*'

#imapfilter &

texpire -d ~/Messages/Newsdir -F ~/Messages/leafnode/config -vvv -f -r
texpire -d ~/Messages/Newsdir -F ~/Messages/leafnode/config -vvv -f

#mairix -p

#imap2nntp -N -H newartisans.com -d ~/Messages/Newsdir \
#    -T 'mail.trash' -v 'Lists'

#logrotate -s /tmp/logrotate.state -v ~/Messages/rotate.conf

#stop-mail

#wait

### getmail ends here
