#!/usr/bin/env python3
#
# getphotos, version 1.3, by John Wiegley <johnw@newartisans.com>
#
# Download photos from a photo card or camera, while renaming and doing other
# house-keeping tasks at the same time.

import sys
import string
import re
import os
import time
import shutil
import hashlib
import logging
import logging.handlers

from stat import *
from os.path import *

#from PIL import Image
#from PIL.ExifTags import TAGS

def get_exif_capture_date(fn):
    #try:
    #    i = Image.open(fn)
    #    info = i._getexif()
    #    if info:
    #        keys = {}
    #        for tag, value in info.items():
    #            decoded = TAGS.get(tag, tag)
    #            keys[decode] = value
    #
    #        if 'DateTimeOriginal' in keys:
    #            return time.strptime(keys['DateTimeOriginal'], '%Y:%m:%d %H:%M:%S')
    #        if 'DateTime' in keys:
    #            return time.strptime(keys['DateTime'], '%Y:%m:%d %H:%M:%S')
    #except:
    #    pass

    with os.popen("exiv2 -q \"%s\"" % fn) as fd:
        for line in fd.readlines():
            match = re.match("^Image timestamp : (.+)", line)
            if match:
                try:
                    return time.strptime(match.group(1), '%Y:%m:%d %H:%M:%S')
                except ValueError:
                    pass

    return None

image_regexp = "(([0-9]{6})_([0-9]{4}))[^.]*\\.(jpe?g|cr[w23]|psd|[pd]ng|webp|heic|gif|mov|mp4|tiff?)(\\.dxo)?$"

dates = {}
readonly = False

def initialize_dates(path):
    global dates
    for entry in sorted(os.listdir(path)):
        base = entry
        entry = join(path, entry)
        if islink(entry) or isfile(entry):
            match = re.match(image_regexp, base, re.IGNORECASE)
            if match:
                name = match.group(1)
                date = match.group(2)
                code = int(match.group(3)) + 1
                if not date in dates or dates[date] < code:
                    dates[date] = code
        elif isdir(entry) \
             and not base == '.Trashes' \
             and not base == '.Spotlight-V100' \
             and not base == '.fseventsd':
            initialize_dates(entry)

def delete_file(path):
    if debug:
        log.debug("rm " + path)
    else:
        log.info("- %s" % path)
    if not readonly:
        os.unlink(path)

def move_file(from_path, to_path):
    if debug:
        log.debug("mv " + from_path + " " + to_path)
    else:
        log.info("%s -> %s" % (from_path, to_path))
    if not readonly:
        shutil.move(from_path, to_path)

def make_directory(path):
    if debug:
        log.debug("mkdir " + path)
    else:
        log.info("+ %s" % path)
    if not readonly:
        os.makedirs(path)

def remove_directory(path):
    if debug:
        log.debug("rmdir " + path)
    else:
        log.info("- %s" % path)
    if not readonly:
        os.rmdir(path)

def make_readonly(path):
    if debug:
        log.debug("chmod 400 " + path)
    if not readonly:
        os.chmod(path, 0o0400)

entry_list = []

def collect_images(path):
    if islink(path) or isfile(path):
        if re.search("\\.(jpe?g|tiff?|[dp]ng|webp|heic|mov|mp4|gif|cr[w23])$", path, re.IGNORECASE):
            mtime = get_exif_capture_date(path)
            if mtime is None:
                log.error("Ignoring image with no capture date: " + path)
            else:
                global entry_list
                entry_list.append((mtime, path))
        elif re.search("\\.thm$", path, re.IGNORECASE):
            delete_file(path)
    elif isdir(path):
        entries = os.listdir(path)
        for entry in entries:
            entry = join(path, entry)
            collect_images(entry)

def prune_dirs(path):
    entries = os.listdir(path)
    if entries:
        recursed = 0
        for entry in entries:
            entry = join(path, entry)
            if isdir(entry):
                prune_dirs(entry)
                recursed = 1
        if recursed:
            entries = os.listdir(path)

    if not entries:
        remove_directory(path)

registry = {}

def move_image(fn, mtime, path):
    root = splitext(fn)[0].lower()
    root = re.sub('_1$', '', root)

    ext = splitext(fn)[1].lower()
    ext = re.sub('jpeg', 'jpg', ext)
    ext = re.sub('tiff', 'tif', ext)

    global registry
    if root in registry:
        base = "%s%s" % (registry[root], ext)
    else:
        global dates

        date = time.strftime("%y%m%d", mtime)
        if not date in dates:
            dates[date] = 1

        serial = dates[date]
        base = "%s_%04d%s" % (date, serial, ext)
        serial += 1
        dates[date] = serial

        registry[root] = splitext(base)[0]

    if path is None:
        move_file(fn, base)
        make_readonly(base)
    else:
        dest = join(path, base)

        if not isdir(dirname(dest)):
            make_directory(dirname(dest))

        if isdir(dirname(dest)):
            if isfile(dest):
                log.error("would overwrite %s!" % (dest,))
            else:
                move_file(fn, dest)
                make_readonly(dest)

########################################################################

formatter = logging.Formatter("%(name)s: %(levelname)s: %(message)s")
ch = logging.StreamHandler()
ch.setFormatter(formatter)

log = logging.getLogger(os.path.basename(sys.argv[0]))
log.addHandler(ch)
log.setLevel(logging.INFO)

args = sys.argv[1 :]
debug = False
renamer = False

if len(args) > 0 and args[0] == "-n":
    readonly = True
    args = args[1 :]
if len(args) > 0 and args[0] == "-d":
    log.setLevel(logging.DEBUG)
    debug = True
    args = args[1 :]
if len(args) > 0 and args[0] == "-r":
    renamer = True
    args = args[1 :]

if renamer:
    if len(args) > 1 and isdir(args[0]):
        baseline = args[0]
        args = args[1 :]
    else:
        baseline = "/Users/johnw/Photos/"

    if isdir(baseline):
        initialize_dates(baseline)
    elif debug:
        log.error("Could not find target path \"%s\"" % baseline)

    for file in args:
        collect_images(file)

    for entry in sorted(entry_list):
        move_image(entry[1], entry[0], None)
else:
    # These are all the possible names of the source volumes, after they have been
    # mounted.
    cards = [ "/Volumes/EOS_DIGITAL" ]

    # A single source directory can be added via the command line.
    if len(args) > 0 and isdir(args[0]):
        cards.append(args[0])
        args = args[1 :]

    # These is the directory to copy pictures to.
    if len(args) > 1 and isdir(args[0]) and isdir(args[1]):
        baseline = args[0]
        target = args[1]
        args = args[2 :]
    else:
        baseline = "/Users/johnw/Photos/"
        target = "/Users/johnw/Photos/Imported"

    if isdir(baseline):
        initialize_dates(baseline)
    elif debug:
        log.error("Could not find target path \"%s\"" % baseline)

    for volume in cards:
        if isdir(volume):
            collect_images(volume)
        elif len(cards) == 1:
            log.warning("Could not find card volume \"%s\"" % volume)

    for entry in sorted(entry_list):
        move_image(entry[1], entry[0], target)

    for volume in cards:
        if isdir(volume):
            prune_dirs(volume)
            if not debug and exists("/usr/sbin/diskutil") and \
               re.search("Volumes", volume):
                os.system("diskutil eject \"%s\"" % volume)
