#!/bin/sh -x

set -e

cd ~/Products/ghc

SRCDIR=$HOME/Projects/ghc
(cd $SRCDIR; git pull; ./sync-all pull)
rsync -av --delete $SRCDIR/ ./

if [ ! -e "mk/build.mk" ]; then
    echo "mk/build.mk file not found; please configure this build!"
    exit 1
fi

echo Configuring build
time (perl boot; ./configure --prefix=/usr/local/Cellar/ghc/HEAD) \
    > configure.log 2>&1

echo Building compiler
#time nice -n 20 make -j16 > make.log 2>&1
time nice -n 20 make > make.log 2>&1

echo Building testsuite
time (cd testsuite/tests ; nice -n 20 make THREADS=64) > make-fulltest.log 2>&1

echo Building nofib
time (cd nofib ; make boot ; nice -n 20 make) > make-nofib.log 2>&1

#echo Installing
#/bin/rm -fr /usr/local/Cellar/ghc/HEAD
#make install > make-install.log 2>&1

exit 0
