#!/bin/bash
set -e
SRCDIR=$HOME/Projects/ghc
find -type l -not -xtype f -print -exec rm {} +
lndir "$SRCDIR"
if [ ! -e "mk/build.mk" ]; then
    echo "mk/build.mk file not found; please configure this build!"
    exit 1
fi
perl boot
if [ ! -e "local" ]; then
    mkdir local
fi
./configure --prefix=`pwd`/local --enable-bootstrap-with-devel-snapshot
make
