#!/bin/bash -xe

DIR=$1
shift 1
cd $DIR

BASE=$(echo $DIR | sed 's/\/tank\///')

for host in "$@" ; do
    if [[ ! -d /Volumes/$host ]]; then
        scp ~/bin/git-annex-restart $host:.
    fi
done

for host in "$@" ; do
    if [[ -d /Volumes/$host ]]; then
        (cd /Volumes/$host/$BASE; git-annex-restart $host)
        (cd /Volumes/$host/$BASE; git config receive.denyCurrentBranch ignore)
    else
        ssh -t $host "(cd $DIR; ~/git-annex-restart $host)"
        ssh -t $host "(cd $DIR; git config receive.denyCurrentBranch ignore)"
    fi
done

git-annex-restart --primary vulcan "$@"

for host in "$@" ; do
    if [[ -d /Volumes/$host ]]; then
        (cd /Volumes/$host/$BASE; git-annex-restart --finish $host) &
    else
        ssh -t $host "(cd $DIR; ~/git-annex-restart --finish $host)" &
    fi
done

wait

git annex sync
for host in "$@" ; do
    if [[ -d /Volumes/$host ]]; then
        (cd /Volumes/$host/$BASE; git-annex sync)
    else
        ssh -t $host "(cd $DIR; git-annex sync)"
    fi
done
git annex sync

git prune
git config pack.compression 9
git gc --aggressive --prune=now
git prune

for host in "$@" ; do
    if [[ -d /Volumes/$host ]]; then
        (cd /Volumes/$host/$BASE; git prune)
        (cd /Volumes/$host/$BASE; git config pack.compression 9)
        (cd /Volumes/$host/$BASE; git gc --aggressive --prune=now)
        (cd /Volumes/$host/$BASE; git prune)
        (cd /Volumes/$host/$BASE; git config --unset receive.denyCurrentBranch)
    else
        ssh -t $host "(cd $DIR; git prune)"
        ssh -t $host "(cd $DIR; git config pack.compression 9)"
        ssh -t $host "(cd $DIR; git gc --aggressive --prune=now)"
        ssh -t $host "(cd $DIR; git prune)"
        ssh -t $host "(cd $DIR; git config --unset receive.denyCurrentBranch)"
    fi
done

git annex fsck -c annex.alwayscommit=false --fast

exit 0
