#!/bin/bash -xe

if [[ "$1" != --finish ]]; then
    mv .git/config config-$$
    mv .git/annex/objects objects-$$

    /bin/rm -fr .git

    git init
    mv config-$$ .git/config

    git config --global annex.backends SHA512E
    git config --global --bool annex.alwayscommit false

    git config annex.backends SHA512E
    git config --bool annex.alwayscommit false

    git annex init
    mv objects-$$ .git/annex/objects
fi

if [[ "$1" == --primary ]]; then
    shift 1
    git checkout --orphan master
    git add .
    git commit -m git-annex-restart

    git annex status --fast

    git annex describe here $1
    shift 1

    for host in "$@"; do
        git push -f $host master:refs/heads/master
        git push -f $host git-annex:refs/heads/git-annex
    done

    git annex fsck -c annex.alwayscommit=false --fast || exit 0

elif [[ "$1" == --finish ]]; then
    shift 1

    git annex describe here $1

    /bin/rm -fr * .gitattributes .apdisk
    git reset --hard HEAD

    git annex status --fast
    git annex fsck -c annex.alwayscommit=false --fast || exit 0
fi

exit 0
