#!/bin/sh

cat <<EOF
repo.url=$1
repo.name=$2
repo.desc=$3
repo.path=/srv/git/$1.git
repo.owner=John Wiegley
repo.defbranch=master                           ## define a default branch
repo.snapshots=tar.bz2                          ## override a sitewide snapshot-setting
repo.clone-url=git://newartisans.com/$1.git
EOF
