#!/usr/bin/env python

import sys
import tempfile
import os
import re

left  = None
right = None

args = sys.argv[1:]

if len(args) == 1:
    args = ('HEAD:' + args[0], args[0])
    
if re.search(':', args[0]):
    fd, name = tempfile.mkstemp()
    pipe = os.popen('git show %s' % args[0])
    os.write(fd, pipe.read())
    os.close(fd)
    left = name
else:
    left = args[0]

right = args[1]

os.system("/Applications/p4merge.app/Contents/MacOS/p4merge '%s' '%s'" %
          (left, right))

if left != args[0]:
    os.remove(left)
