#!/bin/bash

stat=false
if [[ "$1" == "--stat" ]]; then
    stat=true
    shift 1
fi

if [[ $# == 2 ]]; then
    git checkout $2
    echo ======================================================================
fi

if [[ $stat == true ]]; then
    diff -w -U3 -r . "$1" | diffstat | grep -v only$
else
    diff -w -U3 -r . "$1"
fi
