#!/bin/sh

dryrun=false
if [ "$1" = "-n" ]; then
    dryrun=true
    shift 1
fi

find $1 -name .nnmaildir -type d | \
while read nndir; do
    if [ -d "$nndir"/num ]; then
	last=$(find "$nndir"/num -type f | sed -e 's/.*\///' | sort -n | tail -1)
	if [ $dryrun = true ]; then
	    echo rm -fr "$nndir"/num
	    echo echo $last '>' "$nndir"/num
	else
	    rm -fr "$nndir"/num
	    echo $last > "$nndir"/num
	fi
    fi
done
