#!/usr/bin/env python

import sys

from googlevoice import Voice
from googlevoice.util import input

voice = Voice()
voice.login()

if sys.argv[1] == 'call':
    outgoingNumber = sys.argv[2]
    forwardingNumber = None

    voice.call(outgoingNumber, forwardingNumber)

elif sys.argv[1] == 'text':
    phoneNumber = sys.argv[2]
    text = sys.argv[3]

    voice.send_sms(phoneNumber, text)

### gvoice ends here
