#!/usr/bin/env bash

TANKHOST=hermes

tankp() {
    ssh $TANKHOST test "$@"
}
tankpath() {
    echo "${TANKHOST}:${1}"
}

if tankp -d /Volumes/tank/Video/Zoom
then
    for dir in $(find ~/Products -name '20[0-9][0-9]-*' -type d -ctime +1)
    do
        echo "$dir ⟶ tank/Video/Zoom"
        rsync -a "$dir" $(tankpath /Volumes/tank/Video/Zoom) \
            && rm -fr "$dir"
    done
fi
