#!/usr/bin/env bash

for model in "$@"; do
    if [[ -f $model ]]; then
        GIT_SSH_COMMAND="ssh -i $HOME/hera/id_hera -o IdentitiesOnly=yes" \
                       git lfs fetch --include $model
        git lfs checkout $model
        git lfs dedup
        file=$(realpath $model)
        base=$(echo "$file" | sed -e 's/\/Users\/johnw\/Models\///')
        target=$HOME/.local/share/lmstudio/models/$base
        mkdir -p $(dirname $target)
        ln -sf $file $target
    elif [[ -d $model ]]; then
        echo "ERROR: Model directory already exists"
        exit 1
    else
        mkdir -p $model
        GIT_SSH_COMMAND="ssh -i $HOME/hera/id_hera -o IdentitiesOnly=yes" \
                       git clone git@hf.co:$model $model
        cd $model
        # git config lfs.storage ~/Athena/LFS
    fi
done
