#!/bin/bash -e

set -euo pipefail
IFS=$'\n\t'

while [[ $PWD != "/" && ! -f default.nix ]]; do
    cd ..
done

ARGS="$@"

exec nix-shell                                  \
     --arg includeHIE true                      \
     --arg nixpkgs '(import <darwin> {}).pkgs'  \
     --command "hie $ARGS"                      \
     --pure
