#!/usr/bin/env python

import sys

file = open(sys.argv[1])

line = file.readline()
num  = 1
while line:
     lastnum = -1
     for ch in line:
          if ord(ch) > 128 and num != lastnum:
               print "%s:%d:%s" % (sys.argv[1], num, line),
               lastnum = num
     line = file.readline()
     num += 1

file.close()
