#!/bin/bash

perl_match() {
    perl -ne "s/--.*//; print \"$2:\$.:\$_\" if /$1/;" "$2"
}

perl_match '\b(undefined|error|throw)\b' "$1" \
    | while read line; do
    linenum=$(echo "$line" | perl -pe 's/^([0-9]+:).+/\1/;')
    linerem=$(echo "$line" | perl -pe 's/^[0-9]+://;')
    echo "$1:$linenum Warning: Possible partial function"
    echo
done

perl_match '\b(unsafe[a-zA-Z]+)\b' "$1" \
    | while read line; do
    linenum=$(echo "$line" | perl -pe 's/^([0-9]+:).+/\1/;')
    linerem=$(echo "$line" | perl -pe 's/^[0-9]+://;')
    echo "$1:$linenum Warning: Dangerous use of unsafe function"
    echo
done

perl_match '\b(jww)\b' "$1" \
    | while read line; do
    linenum=$(echo "$line" | perl -pe 's/^([0-9]+:).+/\1/;')
    linerem=$(echo "$line" | perl -pe 's/^[0-9]+://;')
    echo "$1:$linenum Warning: Unaddressed TODO comment"
    echo
done

ghc -Wall                                       \
    -fwarn-tabs                                 \
    -fwarn-incomplete-record-updates            \
    -fwarn-monomorphism-restriction             \
    -fwarn-unused-do-bind                       \
    -fwarn-implicit-prelude                     \
    -i. -i.. -i../.. -v0 -c -fforce-recomp "$1"

hlint -u "$1"

exit 0
