#!/bin/bash

if nice -n 20 "$@"; then
    growlnotify -a /Applications/Utilities/Terminal.app \
	-d shell -p High -m "Finished: $1" > /dev/null 2>&1
else
    growlnotify -a /Applications/Utilities/Terminal.app \
	-d shell -p High -m "FAILED: $1" > /dev/null 2>&1
fi
