#!/bin/bash -e

if [[ "$1" == "server" ]]; then
    exec docker run -d -p 8687:8687 -ti jwiegley/hoogle-local
else
    cid=$(docker ps -q --filter ancestor=jwiegley/hoogle-local)
    exec docker exec -i $cid hoogle "$@"
fi
