#!/usr/bin/env bash

HPC_DIR=dist/hpc
SRC_DIR=FP
TEST_DIR=test

TEST_MODULES=(`cd ${TEST_DIR}; find . -name "*.hs"      \
                | sed -e "s/\.hs$//g"                   \
                | sed -e "s/^\.\///g"                   \
                | sed -e "s/\//\./g"`)

for ITEM in ${TEST_MODULES[@]}; do
    EXCLUDES="${EXCLUDES} --exclude ${ITEM}"
done

hpc report $@ $EXCLUDES --hpcdir=$HPC_DIR --xml-output > result.xml
hpc markup $@ $EXCLUDES --hpcdir=$HPC_DIR --destdir=.

open hpc_index.html

exit 0

### hpc-report
