#!/usr/bin/env bash
export PATH=/etc/profiles/per-user/johnw/bin:$PATH
exec uvx --python 3.12 --isolated --with torch --with hf_xet --with hf_transfer --with safetensors --from 'huggingface_hub[cli]' huggingface-cli "$@"
