#!/bin/bash

args=""
if [ $1 = "-f" ]; then
    args="$args -f"
    shift 1
    args="$args $1"
    shift 1
fi

if [ $1 = "-t" ]; then
    args="$args -t"
    shift 1
    args="$args $1"
    shift 1
fi

for file in "$@"; do
    iconv $arg "$file" > /tmp/file.$$ && mv /tmp/file.$$ "$file" 2> /dev/null
done
