#!/bin/zsh

MAIL=$HOME/Library/Mail

imap-unread localhost $(whoami)

echo "Fetching new news"
fetchnews -v -n >> $MAIL/fetchnews.log 2>&1

echo "Updating mairix database"
mairix -F -v >> $MAIL/mairix.log 2>&1

#echo "Storing mail changes in Git"
#packmail >> $MAIL/packmail.log 2>&1
#
#echo "Storing news changes in Git"
#packnews >> $MAIL/packnews.log 2>&1
#
#echo "Linking duplicate messages"
#linkdups $MAIL/Maildir

echo "Done with post-sync"

exit 0

### imap-postsync ends here
