#!/usr/bin/env bash

function dedup_mailboxes() {
    python3 imapdedup.py                            \
            -P "/nix/store/qzysdjsy76v23xg3whsbcqsig4bi9d4r-dovecot-2.3.21.1/libexec/dovecot/imap -c /etc/dovecot/dovecot.conf" \
            -u johnw                                \
            -c                                      \
            -m                                      \
            "$@"
}

if [[ -n "$1" ]]; then
    dedup_mailboxes "$@"
else
    dedup_mailboxes                             \
                                                \
        list/ledger                             \
        list/haskell                            \
        list/haskell/hackage-trustees           \
        list/emacs/tangents                     \
        list/emacs/org-mode                     \
        list/emacs/devel                        \
        list/bahai                              \
        list/bahai/tarjuman                     \
        list/bahai/c2g                          \
        list/bahai/assembly                     \
        list/bahai/andf                         \
                                                \
        list/notifications                      \
        list/misc                               \
        list/github                             \
                                                \
        mail/quantum                            \
                                                \
        INBOX                                   \
                                                \
        Archive                                 \
        Trash                                   \
        Spam                                    \
        Sent                                    \
        NeedsRule                               \
        IsSpam                                  \
        IsGood
fi
