#!/usr/bin/env bash
exec renamer --recursive                                \
        import ~/Photos/Negatives/Canon\ EOS\ R8        \
        --from ~/dl/EOS_DIGITAL                         \
        --to ~/Photos/Negatives/Canon\ EOS\ R8
