#!/usr/bin/env bash
exec renamer --recursive --execute --verbose    \
    import ~/Photos/Negatives/Canon\ EOS\ R8    \
    --from /Volumes/EOS_DIGITAL                 \
    --to ~/Photos/Negatives/Canon\ EOS\ R8
