#!/usr/bin/env bash

set -e

renamer --recursive --execute                      \
    import ~/Photos/Negatives/Canon\ EOS\ R8       \
    --from /Volumes/EOS_DIGITAL                    \
    --to ~/Photos/Negatives/Canon\ EOS\ R8

diskutil eject /Volumes/EOS_DIGITAL
