#!/bin/bash

DIRFILE=$HOME/Library/Info/dir
rm $DIRFILE

install_info() {
    cd "$1"
    for i in * ; do install-info $i $DIRFILE ; done
}

install_info /Users/johnw/.emacs.d/info
install_info /Users/johnw/.nix-profile/share/info

perl -i -ne 'print unless /^This is/;' $DIRFILE
