#!/bin/sh

build=$HOME/Products/Leopard_Release

cp -p $build/zfs /usr/sbin/zfs
cp -p $build/zpool /usr/sbin/zpool
cp -p $build/libzfs.dylib /usr/lib/libzfs.dylib

rm -rf /System/Library/Filesystems/zfs.fs
rm -fr /System/Library/Extensions/zfs.kext

cp -pR $build/zfs.fs /System/Library/Filesystems/zfs.fs
cp -pR $build/zfs.kext /System/Library/Extensions/zfs.kext
