#!/usr/bin/env zsh

case "$1" in
    prof)                                                              \
           cabal clean                                                 \
        && cabal configure --enable-library-profiling                  \
                           --enable-executable-profiling               \
                           --enable-tests                              \
                           --ghc-option=-fprof-auto                    \
                           --ghc-option=-rtsopts                       \
        && cabal build                                                 \
        && cabal test                                                  \
        && (cd test ; make DATA=$HOME/Mirrors/Boost/boost.svnrepo.dump prof)
        ;;

    rebuild)                                                           \
           cabal clean                                                 \
        && cabal configure --enable-tests                              \
                           --ghc-option=-rtsopts                       \
        && cabal build                                                 \
        && cabal test
        ;;
esac
