#!/bin/bash

export PATH=/Users/johnw/bin:/Users/johnw/.nix-profile/bin:$HOME/src/hours/result/bin/

exec hours "$@"                                 \
    --file ~/doc/Tasks/todo.txt                 \
    --category BAE
    # --archive ~/doc/Tasks/BAE.txt
