#!/bin/bash

# Knock on port 1908 to enable SSH for the next 5 minutes
#echo 'Hello, world\!' | socat TCP:johnwiegley.com:1908 - 2> /dev/null

# Open a root login to the server
exec ssh -t johnwiegley.com exec screen -UDR exec sudo su -
