#!/bin/bash
exec nix build "$@"                                                                                  \
    --option build-use-substitutes true                                                              \
    --extra-substituters 'https://nixcache.chainweb.com'                                             \
    --extra-trusted-public-keys 'nixcache.chainweb.com:FVN503ABX9F8x8K0ptnc99XEz5SaA4Sks6kNcZn2pBY=' \
    --extra-substituters 'http://nixcache.kadena.io'                                                 \
    --extra-trusted-public-keys 'kadena-cache.local-1:8wj8JW8V9tmc5bgNNyPM18DYNA1ws3X/MChXh1AQy/Q='  \
    --extra-substituters 'https://open-source.nixcache.obsidian.systems'                             \
    --extra-trusted-public-keys 'obsidian-open-source:KP1UbL7OIibSjFo9/2tiHCYLm/gJMfy8Tim7+7P4o0I='  \
    --extra-substituters 'https://cache.nixos.org'                                                   \
    --extra-trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
