#!/bin/sh

LAMBDABOT=$HOME/src/tools/lambdabot

export XS=$LAMBDABOT/cabal-dev/packages-7.4.2.conf
export XS=$XS:/usr/local/Cellar/ghc/7.4.2/lib/ghc-7.4.2/package.conf.d
export GHC_PACKAGE_PATH=$XS

cd $LAMBDABOT/cabal-dev/bin
export PATH=$PWD:$PATH
exec ./lambdabot
