#!/bin/bash

for appdir in					\
    /Applications				\
    /Developer					\
    /Library					\
    /System					\
    $HOME/Library
do
    find "$appdir" -name '*.lproj' -type d | \
    while read langdir
    do
	base=$(basename "$langdir")
	if [[ "$base" != "English.lproj" && \
	      "$base" != "en.lproj" && \
	      "$base" != "en_US.lproj" ]]
	then
	    /bin/rm -fr "$langdir"
    done
done
