#!/usr/bin/env zsh

set -e

function install() {
   sudo port install $*
}

if false; then
    sudo rm -fr /opt/local/var/macports/build/*
    sudo rm -fr /opt/local/var/macports/registry/*.db
    sudo find /opt -name '.turd*' -delete
    sudo find /opt -name '*.mp_*' -delete
    sudo sign-archives
fi

# Needed for running Emacs
install                                         \
    xml2                                        \
    ncurses                                     \
    gnutls                                      \
    aspell                                      \
    aspell-dict-en

## Used by Emacs modes
install                                         \
    lisp-hyperspec                              \
    MPlayer                                     \
    taglib

# Basics to get the shell working right
install                                         \
    zsh-devel +doc+examples+mp_completion+pcre  \
    coreutils                                   \
    diffutils                                   \
    findutils                                   \
    gnutar                                      \
    gawk                                        \
    grep                                        \
    gsed                                        \

# Sysadmin
install                                         \
    stow                                        \
    xz                                          \
    p7zip                                       \
    flip                                        \
    parallel                                    \
    watch                                       \
    pv                                          \
    screen                                      \
    p5-module-depends                           \
    p5-list-moreutils

## Those last two are needed by ~/Library/MacPorts/cpan2port

# Scripting and other languages
install                                         \
    python27                                    \
    ruby19 +c_api_docs+nosuffix                 \
    sbcl +html

# Mail, News and Chat
install                                         \
    postfix -mysql55+pcre+sasl+tls              \
    pflogsumm                                   \
    fetchmail                                   \
    procmail                                    \
    mairix                                      \
    logrotate +bzip2                            \
    mutt -ssl                                   \
    bitlbee +otr

# Anti-Spam
install                                         \
    p5-mail-spamassassin                        \
    p5-razor-agents                             \
    clamav +clamav_milter                       \
    clamav-server                               \
    p5-mail-clamav                              \
    milter-greylist                             \
    p5-mime-base64                              \
    p5-compress-raw-zlib                        \
    p5-filesys-df                               \
    p5-net-cidr                                 \
    p5-ole-storage_lite                         \
    p5-sys-sigaction                            \
    p5-mime-encwords

## From p5-mime-base64 to the end is needed by MailScanner

# Networking
install                                         \
    rsync                                       \
    mtr                                         \
    nmap                                        \
    socat                                       \
    bmon                                        \
    autossh                                     \
    tcpdump                                     \
    httrack                                     \
    wget                                        \
    boehmgc-devel                               \
    w3m +inline_image_gtk2                      \
    apg

# Version control
install                                         \
    git-core +svn                               \
    subversion                                  \
    cvsps                                       \
    gc-utils                                    \
    bzr                                         \
    bzr-fastimport                              \
    bzrtools                                    \
    mercurial

# development
install                                         \
    m4                                          \
    libtool                                     \
    autoconf                                    \
    automake                                    \
    autogen                                     \
    cmake                                       \
    ccache                                      \
    distcc                                      \
    doxygen                                     \
    gmake                                       \
    gperf                                       \
    lcov                                        \
    valgrind                                    \
    sloccount                                   \
    highlight                                   \
    patchutils                                  \
    diffstat                                    \
    tidy                                        \
    gmp                                         \
    mpfr                                        \
    xmlstarlet

# Perl modules used by Texas Instruments
install                                         \
    p5-ipc-run                                  \
    p5-list-compare                             \
    p5-dbd-mysql                                \
    p5-mime-lite                                \
    p5-tie-insertorderhash

# Compilers
install                                         \
    gcc47                                       \
    gcc48

# Other
install                                         \
    graphviz                                    \
    aquaterm                                    \
    cotvnc

# Databases
install                                         \
    sqlite3                                     \
    mysql55-server                              \
    postgresql92-server

# TeX
install                                         \
    texinfo                                     \
    texlive-xetex                               \
    texlive-documentation-english               \
    texlive-fonts-extra                         \
    texlive-fonts-recommended                   \
    texlive-fontutils                           \
    texlive-generic-extra                       \
    texlive-lang-english                        \
    texlive-latex-extra                         \
    texlive-math-extra                          \
    texlive-metapost                            \
    texlive-pictures                            \
    texlive-plain-extra                         \
    texlive-pstricks

exit 0

### macports-bootstrap ends here
