#!/bin/bash

env=${1:-ghc782}

source $HOME/.bashrc

OLDPATH="$PATH"
OLDTZ="$TZ"

envdir=$(readlink $(which load-env-$env))/../..
source $envdir/dev-envs/$env

PATH="$PATH:$OLDPATH"
export buildInputs
export NIX_STRIP_DEBUG=0
export TZ="$OLDTZ"

nohup ~/.nix-profile/Applications/Emacs.app/Contents/MacOS/Emacs \
    > /dev/null &
