#!/bin/sh

imapsync \
    --dry \
    --nofoldersizes \
    --noreleasecheck \
    --syncinternaldates \
    --useheader 'Message-Id' \
    --allowsizemismatch \
    \
    --host1 imap.gmail.com \
    --port1 993 \
    --ssl1 \
    --user1 jwiegley@gmail.com \
    --passfile1 /Users/johnw/bin/gmail.secret \
    --authmech1 LOGIN \
    --sep1 '/' \
    \
    --host2 localhost \
    --port2 143 \
    --user2 johnw \
    --passfile2 /Users/johnw/bin/local.secret \
    --authmech2 LOGIN \
    --sep2 '.'
