#!/bin/sh

for i in Pictures Applications Documents Reference Music Software
do
    echo $i
    sudo hdiutil create -format UDTO -srcfolder "$i" \
	/Volumes/My\ Book/Archive/Backups/2008-01-17/"$i 2008-01-17.cdr"
done
