#!/bin/bash

docker-machine create                           \
    --driver vmwarefusion                       \
    --vmwarefusion-cpu-count 2                  \
    --vmwarefusion-disk-size 60000              \
    --vmwarefusion-memory-size 4096             \
    default
