#!/bin/bash

launchctl limit maxproc 512

export CCACHE_PREFIX=distcc
export DISTCC_DIR=$HOME/.distcc
export DISTCC_SSH=ssh
export DISTCC_FALLBACK=0
#export DISTCC_VERBOSE=1

CC="distcc /opt/local/bin/x86_64-apple-darwin10-gcc-mp-4.5"
CXX="distcc /opt/local/bin/x86_64-apple-darwin10-g++-mp-4.5"
LD="distcc /opt/local/bin/x86_64-apple-darwin10-gcc-mp-4.5" 

find-env > /tmp/env
source /tmp/env
rm -f /tmp/env

if [[ $found = false ]]; then
    echo "Could not find remote!"
    exit 1
else
    echo "Remote is named $REMOTE"
fi

make CC="$CC" CXX="$CXX" LD="$LD" $JOBS "$@"

exit 0
