#!/bin/bash

REMOTE=home
#REMOTE=vulcan
JOBS=-j22

launchctl limit maxproc 512

export CCACHE_PREFIX=distcc
export DISTCC_DIR=$HOME/.distcc
export DISTCC_SSH=ssh
export DISTCC_FALLBACK=0
#export DISTCC_VERBOSE=1

if hostname | egrep -qi '(vulcan|mrfun)'; then
    export DISTCC_HOSTS="localhost/16 @hermes/4"
else
    export DISTCC_HOSTS="localhost/4 @$REMOTE/16"
fi

nice -n 20 \
make CC="distcc /opt/local/bin/gcc-mp-4.5" \
     CXX="distcc /opt/local/bin/g++-mp-4.5" \
     LD="distcc /opt/local/bin/gcc-mp-4.5" $JOBS "$@"
