#!/bin/sh

date=2008-01-17

mkdir -p /Volumes/My\ Book/Archive/Backups/$date > /dev/null 2>&1

for i in Pictures Applications Documents Reference Music Software
do
    echo $i
    sudo hdiutil create -format UDTO -srcfolder "$i" \
	/Volumes/My\ Book/Archive/Backups/$date/"$i $date.cdr"
done
