#!/bin/bash

cd ~/.emacs.d/mirror/github

rm -f /tmp/urls

for i in $(seq 0 100) ; do
    #curl -s http://github.com/api/v2/yaml/repos/search/emacs\?start_page=$i | \
    #    grep :url: >> /tmp/urls
    #sleep 2
    curl -s http://github.com/api/v2/yaml/repos/show/emacsmirror\?start_page=$i | \
        grep :url: >> /tmp/urls
    sleep 2
done

#egrep -v '(.*emacs[.-]d.*|/(\.|dot[.-]?)?emacs$|emacs-config|/my-)' | \
grep :url: /tmp/urls | awk '{print $2}' | \
egrep -v 'emacsmirror\.github\.com' | \
while read url; do
    if grep -q "^$url\$" .gitignore; then
        continue
    fi

    dir=$(echo $url | sed 's/https:\/\/github\.com\///')
    if [[ ! -d $dir ]]; then
        mkdir -p $dir
        git clone $url $dir
    fi
done

rm -f /tmp/urls

### mkclones ends here
