#!/usr/bin/env python

import os
import sys

from os.path import *

entries = os.listdir(sys.argv[1])

for entry in entries:
    fullPath = join(sys.argv[1], entry)
    print fullPath
    os.system("mdimport \"%s\"" % fullPath)
