#!/bin/bash -x

#REMOTE_BRANCH=upstream
REMOTE_BRANCH=release_31

BRANCHES=$HOME/Contracts/Embarcadero/Projects/branches
PRODUCTS=$HOME/Products/embt
LOG=$HOME/Library/Logs/merge.log

test -f /tmp/attachment.names && rm -f /tmp/attachment.names

echo -a $LOG >> /tmp/attachment.names

send_mail() {
    if [[ -f $HOME/Desktop/MergeIsBroken ]]; then
        eval "mutt $(echo $(< /tmp/attachment.names)) -s '$1' -c 'johnw@boostpro.com' johnw@boostpro.com"
    else
        eval "mutt $(echo $(< /tmp/attachment.names)) -s '$1' -c 'johnw@boostpro.com' $2"
    fi
}

error() {
    export GIT_DIR=$BRANCHES/merge/tools/clang/.git
    hash_remote=$(git rev-parse origin/$REMOTE_BRANCH | cut -c 1-9)
    hash_work=$(git rev-parse origin/work | cut -c 1-9)

    #cat - $LOG <<EOF | send_mail "[embt] $2" 'dave@boostpro.com'
    cat <<EOF | send_mail "[embt] $2" 'dave@boostpro.com'
Merge with upstream FAILED: $REMOTE_BRANCH $hash_remote + origin/work $hash_work

Hmm, it failed (got as far as line $1 of $(basename $0)).  Full logs are
attached.
EOF
    rm -f /tmp/attachment.names
}

log()
{
    echo "$@" >> $LOG 2>&1
}

quiet() {
    #trap 'error ${LINENO}' ERR

    if ! "$@" > /tmp/output.$$ 2>&1; then
        echo "Command failed: $@" >> $LOG
        cat /tmp/output.$$ >> $LOG
    fi
    rm -f /tmp/output.$$
}

update() {
    #trap 'error ${LINENO}' ERR

    git remote update

    if [[ "$1" == "--pull" ]]; then
        git pull
        git submodule update --init
    elif [[ "$1" == "--reset" ]]; then
        git clean -qfx
        git reset -q --hard HEAD
        git checkout -q -f $2
        git reset -q --hard origin/$2
    fi
}

merge() {
    #trap 'error ${LINENO}' ERR

    git checkout -q -f $1
    git reset -q --hard HEAD
    git merge -s recursive -X patience -X ignore-all-space $2
}

run() {
    #trap 'error ${LINENO}' ERR

    cd $SOURCE; "$@"
    cd tools/clang; "$@"
    #cd test/Embt; "$@"
}

rm -f $LOG

if [[ "$1" == --build-all ]]; then
    for branch in $PRODUCTS/*; do
        if [[ ! -d $branch ]]; then continue; fi

        BASE=$(basename $branch)
        SOURCE=$BRANCHES/$BASE

        if [[ ! -d $SOURCE ]]; then continue; fi
        if [[ $BASE == main ]]; then continue; fi
        if [[ $BASE == test ]]; then continue; fi
        if [[ $BASE == merge ]]; then continue; fi

        log ========================================================================
        log Building $branch on $(date)
        log ========================================================================

        if [[ $BASE == 'svn' ]]; then
            run svn update >> $LOG 2>&1
        elif [[ $BASE == 'git-svn' ]]; then
            run git svn fetch >> $LOG 2>&1
            run git svn rebase >> $LOG 2>&1
        else
            run update >> $LOG 2>&1
        fi

        #(cd $branch && quiet-clang-build --tests -j16 >> $LOG 2>&1)
    done
else
    shift 1
fi

log ========================================================================
log Merging Clang/LLVM on $(date)
log ========================================================================

run_clangup() {
    CLANGLOG=~/Library/Logs/$1_$2-$3.log
    log "------------------------------------------------------------------------------"
    log "### For sanity's sake, checking if current $* builds..."
    log "------------------------------------------------------------------------------"
    eval "$@" | tr -d '\r' | tee $CLANGLOG
    echo -a $CLANGLOG >> /tmp/attachment.names
    case $? in
        0)
            log ========================================================================
            log Cannot tell if $1 $2 build succeeded.  Last 50 lines from log:
            log ========================================================================
            cat $CLANGLOG | tail -50 >> $LOG
            ;;
        1)
            log ========================================================================
            log $1 $2 build FAILED.  Log appended here:
            log ========================================================================
            cat $CLANGLOG >> $LOG
            log ========================================================================
            log Log ends here.
            log ========================================================================
            ;;
        2)
            log ========================================================================
            log $1 $2 build FAILED to pass tests.  Log appended here:
            log ========================================================================
            cat $CLANGLOG >> $LOG
            log ========================================================================
            log Log ends here.
            log ========================================================================
            ;;
    esac
}

run_clangup clangup $REMOTE_BRANCH
if [[ "$1" != --no-windows ]]; then
    run_clangup win-clangup $REMOTE_BRANCH 2010
    run_clangup win-clangup $REMOTE_BRANCH 2008
fi

run_clangup clangup work
if [[ "$1" != --no-windows ]]; then
    run_clangup win-clangup work 2010
    run_clangup win-clangup work 2008
fi

log "------------------------------------------------------------------------------"

SOURCE=$BRANCHES/merge
PRODUCTS=$PRODUCTS/merge

run git branch -D merged
run git branch -Dr origin/merged
run git push origin :refs/heads/merged

run update --reset work >> $LOG 2>&1

if [[ ! -d $PRODUCTS ]]; then
  mkdir -p $PRODUCTS
  cd $PRODUCTS
fi

log "------------------------------------------------------------------------------"
log "Merging origin/$REMOTE_BRANCH $(git rev-parse origin/$REMOTE_BRANCH | cut -c 1-9) into work $(git rev-parse work | cut -c 1-9)"
log "------------------------------------------------------------------------------"

if ! run merge work origin/$REMOTE_BRANCH >> $LOG 2>&1; then
    error ${LINENO} "Failed to merge; please attempt a local merge"
    exit 1
fi

log "------------------------------------------------------------------------------"
log "Building resulting merge"
log "------------------------------------------------------------------------------"

cd $PRODUCTS
/bin/rm -fr *
cmake -DLLVM_TARGETS_TO_BUILD:=X86 $SOURCE

if ! make-distcc >> $LOG 2>&1; then
    log "=== Merge failed to build ==="

    run git branch -f merged work
    run git push -f origin merged

    error ${LINENO} "Resulting merge failed to build; in branch 'merged'"
    exit 1
fi

# If it builds, push the commits to work now; it may not be passing tests
#run git push >> $LOG 2>&1

log "------------------------------------------------------------------------------"
log "Testing resulting merge"
log "------------------------------------------------------------------------------"

if ! make clang-test >> $LOG 2>&1; then
    log "=== Merge failed to pass tests ==="

    run git branch -f merged work
    run git push -f origin merged

    error ${LINENO} "Resulting merge failed to pass tests; in branch 'merged'"
    exit 1
fi

# If it passes tests, merge it to master
#run git fixws >> $LOG 2>&1
log "------------------------------------------------------------------------------"
log "Merging new work branch into master"
log "------------------------------------------------------------------------------"
run merge master work >> $LOG 2>&1

cd $SOURCE/tools/clang
if git ls-files --modified test/Embt | grep -q Embt; then
    git add test/Embt
    git commit -m "Updated test/Embt submodule"
fi

log "Pushing new work and master to remote"
run git push >> $LOG 2>&1

if [[ "$1" != --no-windows ]]; then
    run_clangup win-clangup merge 2010
    run_clangup win-clangup merge 2008

    sleep 300

    osascript -e 'tell application "VMware Fusion" to quit'
fi

export GIT_DIR=$BRANCHES/merge/tools/clang/.git
hash_work=$(git rev-parse work | cut -c 1-9)
send_mail "[embt] Merge with upstream SUCCESS: work $hash_work" 'dave@boostpro.com' <<EOF
Yay, it worked.  Logs attached.
EOF

rm -f /tmp/attachment.names

mv $LOG $PRODUCTS

exit 0

### merge-upstream ends here
