#!/bin/bash

function gen_files() {
    if [[ -n "$1" ]]; then
        (cd $1;                                                         \
            git ls-files --                                             \
            '*.c' '*.cc' '*.cpp' '*.cxx'                                \
            '**/*.c' '**/*.cc' '**/*.cpp' '**/*.cxx'                    \
            '*.h' '*.hh' '*.hpp' '*.hxx'                                \
            '**/*.h' '**/*.hh' '**/*.hpp' '**/*.hxx') > /tmp/subfiles.$$
        cat /tmp/subfiles.$$ | while read file; do
            echo $1/$file >> /tmp/files.$$
        done
        rm -f /tmp/subfiles.$$
    fi
}

rm -f /tmp/files.$$

for i in "." "$@"; do gen_files "$i"; done

if [[ -d lib/Sema ]]; then
    perl -i -ne 'print unless /^(test|tools|unittests|INPUTS|bindings|examples|utils)\//;' /tmp/files.$$
elif [[ -d tools/clang/lib/Sema ]]; then
    perl -i -ne 'print unless /^(test|tools|unittests|INPUTS|bindings|examples|utils)\//;' /tmp/files.$$
    perl -i -ne 'print unless /^tools\/clang\/(test|tools|unittests|INPUTS|bindings|examples|utils)\//;' /tmp/files.$$
elif [[ -f test/unit/t_amount.cc ]]; then
    perl -i -ne 'print unless /^(test)\//;' /tmp/files.$$
fi

if [[ "$1" != "--c" ]]; then
    export GTAGSFORCECPP=1
fi
cat /tmp/files.$$ | gtags --statistics -v -f -

#cat /tmp/files.$$ | xargs -0 etags -o TAGS

rm -f /tmp/files.$$

### mktags ends here
