#!/bin/bash

if [[ "$1" == "--cpp" ]]; then
    export GTAGSFORCECPP=1
fi

gen_files() {
    cd $1
    git ls-files --                                     \
        '*.c' '*.cc' '*.cpp' '*.cxx'                    \
        '**/*.c' '**/*.cc' '**/*.cpp' '**/*.cxx'        \
        '*.h' '*.hh' '*.hpp' '*.hxx'                    \
        '**/*.h' '**/*.hh' '**/*.hpp' '**/*.hxx'	\
        '**/*.v' '**/*.hs'
}

filter_files() {
    LLVM_IGNORE="(test|tools|unittests|INPUTS|bindings|examples|utils)"

    if [[ -d $1/lib/Sema ]]; then
        egrep -v "^$LLVM_IGNORE/"
    elif [[ -d $1/tools/clang/lib/Sema ]]; then
        egrep -v "^$LLVM_IGNORE/" | egrep -v "^tools/clang/$LLVM_IGNORE/"
    elif [[ -f $1/test/unit/t_amount.cc ]]; then
        egrep -v "^test/"
    elif [[ -f $1/disp/il.c ]]; then
        egrep -v "^disp/"
    elif [[ -f $1/ANSI_33/ah_gen_be.c ]]; then
        egrep -v "^ANSI_33/"
    else
        cat
    fi
}

prefix_lines() {
    while read line; do echo $1/$line; done
}

for i in "$@"; do
    gen_files "$i" | filter_files "$i" | prefix_lines "$i"
done \
| if [[ -f GTAGS ]]; then
      gtags --statistics -v -i -f -
  else
      gtags --statistics -v -f -
  fi

### mktags ends here
