#!/usr/bin/env bash
command="$1"
shift 1
export PATH=/etc/profiles/per-user/johnw/bin:$PATH
exec uvx --python 3.12 --isolated --with openmpi --with hf_xet --with hf_transfer --with huggingface_hub --with torch --with mlx_lm --from mlx mlx."$command" "$@"
