#!/bin/bash
exec /usr/local/bin/multitail                                   \
    -l "cd ~/fpco; ~/.cabal/bin/git-monitor -v"                 \
    -l "cd ~/fpco/gitlib; ~/.cabal/bin/git-monitor -v"          \
