#!/bin/bash

if ping -q -t 5 -c 1 192.168.9.144 > /dev/null
then
    if [[ ! -d /Volumes/backup ]]; then
	mkdir /Volumes/backup
    fi
    if [[ ! -d /Volumes/backup/389073385741093261 ]]; then
	sudo launchctl unload /Library/LaunchDaemons/com.crashplan.engine.plist

	diskutil eject /Volumes/BOOTCAMP
	diskutil eject /Volumes/GAMES

	/sbin/mount_afp afp://192.168.9.144/backup /Volumes/backup
	sleep 15

	if [[ ! -d /Volumes/backup/389073385741093261 ]]; then
	    rmdir /Volumes/backup
	else
	    sudo launchctl load /Library/LaunchDaemons/com.crashplan.engine.plist
	fi
    fi
    if [[ ! -d /Volumes/media ]]; then
	mkdir /Volumes/media
	/sbin/mount_afp afp://192.168.9.144/media /Volumes/media
    fi
fi
