#!/bin/bash

remote=$1
local=$2

if [[ -z $local ]]; then
    local=$(basename $remote)
fi

if [[ ! -d /Volumes/$local ]]; then
    mkdir /Volumes/$local
fi

sshfs $remote /Volumes/$local && open /Volumes/$local
