#!/bin/bash -x

cabal=$(echo *.cabal)

profiling=no
if [[ "$1" == "prof" ]]; then
    profiling=yes
    shift 1
fi

if [[ ! -f default.nix ]]; then
    cabal2nix . > default.nix
fi

if [[ ! -f Setup.hs && ! -f Setup.lhs ]]; then
    cat > Setup.hs <<EOF
import Distribution.Simple
main = defaultMain
EOF
fi

exec nix-shell '<nixpkgs>' -Q -j4 -k -A haskPkgs.$(basename $(pwd)).env "$@"
