#!/usr/bin/env bash

# Posts notifications to iOS device using prowl & curl

APIKEY=$(pass api.prowlapp.com | head -1)

# Post notification to Prowl using curl
curl -s --globoff https://api.prowlapp.com/publicapi/add        \
  -F apikey=$APIKEY                                             \
  -F application=Terminal                                       \
  -F event=""                                                   \
  -F description="$@" > /dev/null

exec $HOME/Applications/Home\ Manager\ Apps/terminal-notifier.app/Contents/MacOS/terminal-notifier -message "$@"
