#!/bin/bash

repack=false
if [[ "$1" == --repack ]]; then
    repack=true
    shift 1
fi

for dir in "$@"; do
    if [[ -d "$dir" ]]; then
        echo Packing directory $dir
        cd "$dir"

        git ls-files --deleted -z | xargs -0 git rm --cached
        git ls-files --exclude-standard --modified --others -z | \
            xargs -0 git update-index --add
        git commit -q -m "Backup $(date +%Y%m%d%H%M)"

        if [[ $repack == true ]]; then
            echo Flushing directory $dir
            git flush
        fi
    fi
done

### packmail ends here
