#!/bin/sh

DIR=/Users/johnw

if /opt/local/bin/curl -s http://www.newartisans.com/i_am_stolen.html | \
   /usr/bin/grep -q "I_AM_STOLEN"
then
    for item in \
	$DIR/Library/Keychains/* \
	$DIR/Library/openvpn/* \
	$DIR/Private/* \
	$DIR/Documents/todo.txt \
	$DIR/Documents/archive.txt \
	$DIR/.ssh/* \
	$DIR/.gnupg/* \
	$DIR/.cvspass \
	$DIR/.subversion/* \
	$DIR/.authinfo \
	$DIR/.fetchmailrc
    do
	/usr/bin/srm -mfr $item &
    done
    wait
    echo PANIC: All sensitive data has been wiped.
fi
