#!/usr/bin/env bash

if [[ ! -d .claude ]]; then
    mkdir .claude
fi

if [[ ! -f .claude/settings.local.json ]]; then
    cat > .claude/settings.local.json <<EOF
{
  "apiKeyHelper": "cat ~/.claude/pos-api-key"
}
EOF
fi

claude mcp remove pal -s local
claude mcp add                                                                  \
    pal -s local                                                                \
    -e ANTHROPIC_API_KEY=$(pass positron/api.anthropic.com | head -1)           \
    -e OPENAI_API_KEY=$(pass positron/api.openai.com | head -1)                 \
    -e GEMINI_API_KEY=$(pass positron/api.gemini.com | head -1)                 \
    -e DISABLED_TOOLS=tracer                                                    \
    -e DEFAULT_MODEL=auto                                                       \
    --                                                                          \
    uvx --from git+https://github.com/BeehiveInnovations/pal-mcp-server.git     \
        pal-mcp-server                                                          \
