#!/bin/sh

SYSNAME=`scutil --get ComputerName`
UUID=`system_profiler | grep 'Hardware UUID' | awk '{print $3}'`

hdiutil create -size 2T -fs HFS+J -volname 'Time Machine Backups' -type SPARSEBUNDLE "${SYSNAME}.sparsebundle" && \
cat <<EOF > "${SYSNAME}.sparsebundle"/com.apple.TimeMachine.MachineID.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>com.apple.backupd.HostUUID</key>
        <string>$UUID</string>
</dict>
</plist>
EOF
