#!/bin/bash -x

# CACHE=$2 u $1 rebuild

for dir in                                      \
    ~/dfinity/master/prod                       \
    ~/dfinity/master/rs                         \
    ~/dfinity/master/tests                      \
    ~/dfinity/master                            \
    ~/dfinity/consensus-model/reference         \
    ~/src/category-theory                       \
    ~/src/notes/coq                             \
    ~/src/notes/haskell                         \
    ~/src/thinkorswim/trade-journal
do
    (cd "$dir" && bash -c "CACHE=$2 de")
done

/bin/rm -fr ~/dfinity/master/.envrc
/bin/rm -fr ~/dfinity/master/.direnv

(cd ~/src/ledger/master ; load-env-ledger-py2 ./acprep --ninja debug)
(cd ~/Products/master/debug ; load-env-ledger-py2 ninja)
