#!/bin/bash

chmod -R go+rX ~/Public/

nc jw 1908 < /dev/null
rsync -aP --delete --exclude="Drop Box/" ~/Public/ jw:/srv/ftp/pub/

nc jw2 1908 < /dev/null
rsync -aP --delete --exclude="Drop Box/" ~/Public/ jw2:/srv/ftp/pub/
