#!/usr/bin/env bash

MYHOST=$(myhost)

if [[ $MYHOST == hera ]]; then
    if [[ "$1" == "clio" ]]; then
        shift 1
        exec pushme "$@" hera@24 clio@10
    elif [[ "$1" == "athena" ]]; then
        shift 1
        exec pushme "$@" hera@24 athena@8
    elif [[ "$1" == "tank" ]]; then
        shift 1
        exec pushme "$@" hera@24 tank@1
    elif [[ "$1" == "all" ]]; then
        shift 1
        exec pushme "$@" hera@24 clio@10 athena@8 tank@1
    else
        exec pushme "$@" hera@24 clio@10 athena@8
    fi
elif [[ $MYHOST == clio ]]; then
    exec pushme "$@" clio@6 hera@6
fi
