#!/bin/bash

OPTS=""
serial=false
while getopts 'LNnvQSj:' opt; do
    case $opt in
        L)  OPTS="$OPTS -L" ;;
        N)  OPTS="$OPTS -N" ;;
        Q)  OPTS="$OPTS -c quick" ;;
        S)  serial=true ;;
        j)  OPTS="$OPTS -j$OPTARG" ;;
        n)  OPTS="$OPTS -n" ;;
        v)  OPTS="$OPTS -v" ;;
        \?) OPTS="$OPTS -$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

# Find out which remote machine to copy to
if [[ -z "$1" ]]; then
    find-env > /tmp/env
    source /tmp/env
    rm -f /tmp/env

    if [[ $found = false ]]; then
        echo "Could not find remote!"
        exit 1
    elif ! ssh $REMOTE true; then
        echo "Error: Could not reach host $REMOTE"
        exit 1
    fi

    echo "Remote is named $REMOTE"
else
    REMOTE=""
fi

# # Scan for items which should be synchronized
if ! running postfix/master; then
    echo "Giving queued messages a chance to escape..."

    if sudo /usr/libexec/postfix/master -t; then
        sudo /usr/libexec/postfix/master -e 60 &
    fi
    sudo /usr/sbin/postqueue -f
fi

if [[ $(hostname) == "vulcan.local" || $(hostname) == "Vulcan.local" ]]; then
    sudo /usr/local/sbin/dovecot stop
fi

# Stop running applications
#ssh $REMOTE osascript -e "tell application \"LaunchBar\" to quit"

find ~/Messages/Gnus -name 'nnir:*' -exec /bin/rm -fr '{}' \;

# Synchronize directories
if [[ -n "$REMOTE" && ($REMOTE == vulcan || $REMOTE == home) ]]; then
    OPTS="$OPTS -j8"

elif [[ -n "$REMOTE" && ($REMOTE == hermes || $REMOTE == hermesw) ]]; then
    rsync -av \
        hermes:'Applications/World\ of\ Warcraft/WTF/Account/78475252\#2/' \
        ~/Applications/World\ of\ Warcraft/WTF/Account/78475252\#2/
    OPTS="$OPTS -j8"

elif [[ "$1" == "titan" ]]; then
    ARGS="-L titan mirror @mirror mirror/titan @tank tank/titan"
    shift 1
fi

time ~/src/pushme/dist/build/pushme/pushme                              \
    --ssh="ssh -F $HOME/.ssh/config" $OPTS $REMOTE $ARGS "$@"           \
    && ( cd ~/.pushme && git commit --all -m "Updated on $(date)" )

if [[ -n "$REMOTE" ]]; then
    rsync -av --delete ~/.pushme/ $REMOTE:.pushme/
fi

if [[ $(hostname) == "vulcan.local" || $(hostname) == "Vulcan.local" ]]; then
    sudo /usr/local/sbin/dovecot
fi

exit 0

### pushme ends here
