#!/bin/bash

# There are several "zones" which this script synchronizes:
#
#  - ~/
#  - ~/Contracts
#  - ~/Downloads       (only from laptop -> desktop)
#  - /Applications     (only from desktop -> laptop)
#  - /opt              (only from desktop -> laptop)
#  - /usr/local/stow   (only from desktop -> laptop)
#  - ~/Archives
#  - Media
#
# The home directory synchronization is made more complex by the fact that
# each machine has two areas where files live:
#
#  laptop  :: ~, /Volumes/Private
#  desktop :: ~, /Volumes/RAID
#
# This makes for four separate synchronization passes, for each combination.

RSYNC='sudo /opt/local/bin/rsync'
FLAGS="-arPXHEyzh"
LAPTOP=hermes

EXCLUDES=""
EXCLUDES="$EXCLUDES --exclude=/.com.apple.timemachine.supported"
EXCLUDES="$EXCLUDES --exclude=/.fseventsd/"
EXCLUDES="$EXCLUDES --exclude=/.Spotlight-V100/"
EXCLUDES="$EXCLUDES --exclude=/.TemporaryItems/"
EXCLUDES="$EXCLUDES --exclude=/.Trashes/"
EXCLUDES="$EXCLUDES --exclude=.DS_Store"
EXCLUDES="$EXCLUDES --exclude=.localized"
FLAGS="$FLAGS $EXCLUDES"

if [[ $(basename "$0") == 'pushme' ]]; then
    SOURCE=''
    TARGET="$LAPTOP:"
    SSOURCE="$SOURCE$HOME"
    TTARGET="$TARGET/Volumes/Passport"
    CSOURCE="$SOURCE$HOME/Contracts"
    CTARGET="$TARGET/Volumes"
    PSOURCE="$SOURCE$HOME"
    PTARGET="$TARGET/Volumes/Private"
    RSOURCE="$SOURCE$HOME"
    RTARGET="$TARGET/Volumes/RAID"
    RPSOURCE="$SOURCE/Volumes/RAID"
    RPTARGET="$TARGET/Volumes/Private"
else
    SOURCE="$LAPTOP:"
    TARGET=''
    SSOURCE="$SOURCE/Volumes/Passport"
    TTARGET="$TARGET$HOME"
    CSOURCE="$SOURCE/Volumes"
    CTARGET="$TARGET$HOME/Contracts"
    PSOURCE="$SOURCE/Volumes/Private"
    PTARGET="$TARGET$HOME"
    RSOURCE="$SOURCE/Volumes/RAID"
    RTARGET="$TARGET$HOME"
    RPSOURCE="$SOURCE/Volumes/Private"
    RPTARGET="$TARGET/Volumes/RAID"
fi

if ! ssh $LAPTOP true; then
    exit 1
fi

# Home: ~ <-> ~

echo $SOURCE$HOME/ '->' $TARGET$HOME/
rsync $FLAGS --delete --rsync-path "$RSYNC" \
    --include='/.MacOSX/' \
    --include='/.PySolFC/' \
    --include='/.bazaar/' \
    --include='/.deltawalker/' \
    --include='/.gdbrc' \
    --include='/.git*' \
    --include='/.groovy/' \
    --include='/.inputrc' \
    --include='/.ledgerrc' \
    --include='/.scapy_startup.py' \
    --include='/.screenrc' \
    --include='/.ssh/' \
    --include='/.stella/' \
    --include='/.vplls/' \
    --include='/.zshrc' \
    --include='/Desktop/' \
    --exclude='/Desktop/Private.sparsebundle' \
    --include='/Library/' \
    --include='/Music/' \
    --exclude='/*/' \
    --exclude='/*' \
    --exclude='/.*/' \
    --exclude='/.*' \
    --include='/Library/Application Support/' \
    --include='/Library/Audio/' \
    --include='/Library/Calendars/' \
    --include='/Library/Emacs/' \
    --include='/Library/FontCollections/' \
    --include='/Library/Fonts/' \
    --include='/Library/Info/' \
    --include='/Library/Inform/' \
    --include='/Library/Java/' \
    --include='/Library/KeyBindings/' \
    --include='/Library/Keyboard Layouts/' \
    --include='/Library/Lisp/' \
    --include='/Library/Application Support/' \
    --include='/Library/PreferencePanes/' \
    --include='/Library/Preferences/' \
    --include='/Library/QuicKeys/' \
    --include='/Library/QuickLook/' \
    --include='/Library/Scripts/' \
    --include='/Library/Sounds/' \
    --include='/Library/Spelling/' \
    --include='/Library/TexPackages/' \
    --include='/Library/Wallpapers/' \
    --include='/Library/Widgets/' \
    --include='/Library/Workflows/' \
    --include='/Library/Workflows/' \
    --include='/Library/XMind/' \
    --include='/Library/texmf/' \
    --exclude='/Library/*/' \
    --exclude='/Library/*' \
    --exclude='/Library/.*/' \
    --exclude='/Library/.*' \
    --include='/Library/Application Support/DEVONagent/' \
    --include='/Library/Application Support/Google Earth/' \
    --include='/Library/Application Support/Hazel/' \
    --exclude='/Library/Application Support/Hazel/*.hazeldb' \
    --include='/Library/Application Support/IntelliJIDEA70/' \
    --include='/Library/Application Support/IntelliJIDEA80/' \
    --include='/Library/Application Support/Merlin/' \
    --include='/Library/Application Support/OmniGraffle/' \
    --include='/Library/Application Support/Scrivener/' \
    --include='/Library/Application Support/TextExpander/' \
    --include='/Library/Application Support/TextMate/' \
    --include='/Library/Application Support/WorldOfGoo/' \
    --exclude='/Library/Application Support/*/' \
    --exclude='/Library/Application Support/*' \
    --exclude='/Library/Application Support/.*/' \
    --exclude='/Library/Application Support/.*' \
    --include='/Library/Preferences/Adobe*/' \
    --include='/Library/Preferences/Adobe*' \
    --exclude='/Library/Preferences/*/' \
    --exclude='/Library/Preferences/*' \
    --exclude='/Library/Preferences/.*/' \
    --exclude='/Library/Preferences/.*' \
    $SOURCE$HOME/ $TARGET$HOME/

# Home: ~ <-> Private

echo $PSOURCE/ '->' $PTARGET/
rsync $FLAGS --delete --rsync-path "$RSYNC" \
    --include='/.Deskzilla/' \
    --include='/.datastudio/' \
    --include='/.dbvis/' \
    --include='/.emacs.bmk' \
    --include='/.eshell/' \
    --include='/.filezilla/' \
    --include='/.gnupg/' \
    --include='/.m2/' \
    --include='/.subversion/' \
    --include='/Library/' \
    --exclude='/*/' \
    --exclude='/*' \
    --exclude='/.*/' \
    --exclude='/.*' \
    --include='/Library/Application Support/' \
    --include='/Library/Mail/' \
    --include='/Library/Mail Downloads/' \
    --exclude='/Library/*/' \
    --exclude='/Library/*' \
    --exclude='/Library/.*/' \
    --exclude='/Library/.*' \
    --include='/Library/Application Support/AddressBook/' \
    --include='/Library/Application Support/Adium 2.0/' \
    --include='/Library/Application Support/Colloquy/' \
    --include='/Library/Application Support/Cyberduck/' \
    --include='/Library/Application Support/DEVONthink Pro 2/' \
    --include='/Library/Application Support/DVD Player/' \
    --include='/Library/Application Support/Firefox/' \
    --include='/Library/Application Support/PhoneView/' \
    --include='/Library/Application Support/Skype/' \
    --include='/Library/Application Support/Tunnelblick/' \
    --include='/Library/Application Support/ecto3/' \
    --exclude='/Library/Application Support/*/' \
    --exclude='/Library/Application Support/*' \
    --exclude='/Library/Application Support/.*/' \
    --exclude='/Library/Application Support/.*' \
    $PSOURCE/ $PTARGET/

# Home: ~ and RAID (Archives is the only thing)

echo $RSOURCE/ '->' $RTARGET/
rsync $FLAGS --delete --rsync-path "$RSYNC" \
    --include='/Archives/' \
    --exclude='/Archives/Games/' \
    --exclude='/Archives/Games' \
    --exclude='/Archives/Linux/' \
    --exclude='/Archives/Linux' \
    --exclude='/Archives/Systems/' \
    --exclude='/Archives/Systems' \
    --exclude='/Archives/SICP/' \
    --exclude='/Archives/SICP' \
    --include='/Files.sparsebundle/' \
    --exclude='/*/' \
    --exclude='/*' \
    --exclude='/.*/' \
    --exclude='/.*' \
    $SOURCE$HOME/Archives/ $TARGET$HOME/Archives/

# Home: Private and RAID

echo $RPSOURCE/ '->' $RPTARGET/
rsync $FLAGS --delete --rsync-path "$RSYNC" \
    --include='/Backups/' \
    --exclude='/Backups/[0-9]*/' \
    --include='/Documents/' \
    --include='/Projects/' \
    --include='/Sites/' \
    --exclude='/*/' \
    --exclude='/*' \
    --exclude='/.*/' \
    --exclude='/.*' \
    $RPSOURCE/ $RPTARGET/

# Contracts

for contract in CEG TI
do
    if ssh hermes "mount | grep -q '/Volumes/$contract.*hfs'"; then
	echo $CSOURCE/$contract/ '->' $CTARGET/$contract/
	rsync $FLAGS --delete --rsync-path "$RSYNC" \
	    --exclude='Backup/' \
	    --exclude='Backup.[0-9]/' \
	    --exclude=/.backups/ \
	    --exclude=/Machines/ \
	    --exclude=/3dex/ \
	    --exclude=target/ \
	    --exclude=darwin/ \
	    $CSOURCE/$contract/ $CTARGET/$contract/
    fi
done

if [[ $(basename "$0") == 'pullyou' ]]; then
    # Downloads
    echo $SOURCE$HOME/Downloads/ '->' $TARGET$HOME/Downloads/
    rsync $FLAGS --rsync-path "$RSYNC" \
	$SOURCE$HOME/Downloads/ $TARGET$HOME/Downloads/

else
    ## Applications
    echo $SOURCE/Applications/ '->' $TARGET/Applications/
    rsync $FLAGS --delete --rsync-path "$RSYNC" \
	--include='/Games/' \
	--include='/Misc/' \
	--exclude='/Misc/Networking/Dropbox.app/' \
	--exclude='/Misc/Utilities/ForeverSave.app/' \
	--exclude='/Misc/Utilities/LaunchBar.app/' \
	--exclude='/Misc/Utilities/Tunnelblick.app/' \
	--exclude=/*/ \
	$SOURCE/Applications/ $TARGET/Applications/

    # opt
    echo $SOURCE/opt/local/var/macports/ '->' $TARGET/opt/local/var/macports/
    rsync $FLAGS --delete --rsync-path "$RSYNC" \
	--exclude=.tclpackage \
	--exclude=/build/ \
	--exclude=/port-help.tcl \
	--exclude=/receipts/ \
	--exclude=/software/ \
	--exclude=/sources/ \
	$SOURCE/opt/local/var/macports/ $TARGET/opt/local/var/macports/
fi

# stow
echo $SOURCE/usr/local/stow/ '->' $TARGET/usr/local/stow/
rsync $FLAGS --delete --rsync-path "$RSYNC" \
    $SOURCE/usr/local/stow/ $TARGET/usr/local/stow/

if ssh $LAPTOP test -d /Volumes/Passport; then
    # Archives, the larger part
    echo $SSOURCE/Archives/ '->' $TTARGET/Archives/
    rsync $FLAGS --delete --rsync-path "$RSYNC" \
	--include=/Linux/ \
	--exclude=/Linux/Fedora/ \
	--exclude=/Linux/Debian/ \
	--exclude=/*/ \
	$SSOURCE/Archives/ $TTARGET/Archives/

    # Media: Movies, Pictures, Photos
    echo /Volumes/RAID/Media/ '->' $TTARGET/Media/
    rsync $FLAGS --delete --rsync-path "$RSYNC" \
	/Volumes/RAID/Media/ $TTARGET/Media/
fi
