#!/bin/bash

serial=false
fullsync=true
while getopts 'LNnvDQSsFfcCj:h:' opt; do
    case $opt in
        N)  OPTS="$OPTS -N" ;;
        c)  OPTS="$OPTS -c $OPTARG" ;;
        C)  OPTS="$OPTS --checksum" ;;
        f)  OPTS="$OPTS -f $OPTARG" ;;
        s)  OPTS="$OPTS -c sync" ;;
        Q)  OPTS="$OPTS -c quick" ;;
        S)  serial=true ;;
        F)  fullsync=false ;;
        j)  OPTS="$OPTS -j$OPTARG" ;;
        h)  OPTS="$OPTS --from $OPTARG" ;;
        n)  OPTS="$OPTS -n" ;;
        v)  OPTS="$OPTS -v" ;;
        D)  OPTS="$OPTS -D" ;;
        \?) OPTS="$OPTS -$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

if [[ -z "$1" ]]; then
    find ~/Messages/Gnus -name 'nnir:*' -exec /bin/rm -fr '{}' \;

    test -d /Volumes/Files   && diskutil eject /Volumes/Files
    test -d /Volumes/Hackage && diskutil eject /Volumes/Hackage
fi

LOCAL=$(ipaddr bond0 2> /dev/null)
if [[ -z "$LOCAL" ]]; then
    LOCAL=$(ipaddr en8 2> /dev/null)
fi
if [[ -z "$LOCAL" ]]; then
    LOCAL=$(ipaddr en0 2> /dev/null)
fi
if [[ -z "$LOCAL" ]]; then
    LOCAL=$(ipaddr en1 2> /dev/null)
fi

if [[ "$LOCAL" == $VULCAN_ETHERNET ]]; then
    JOBS=-j22
    laptop=false
    LOCAL=vulcan

    if ssh hermes true; then
        found=true
        REMOTE=hermes
        OPTS="--from $LOCAL $OPTS"
    else
        echo Cannot find hermes
        exit 1
    fi
else
    JOBS=-j18
    laptop=true
    LOCAL=hermes

    if ssh vulcan true; then
        found=true
        REMOTE=vulcan
        OPTS="--from $LOCAL $OPTS"
    else
        echo Cannot find vulcan
        exit 1
    fi
fi


if [[ -z "$1" ]]; then
    if [[ $found = false ]]; then
        echo "Could not find remote!"
        exit 1
    elif ! ssh $REMOTE true; then
        echo "Error: Could not reach host $REMOTE"
        exit 1
    fi

    echo "Local is named $LOCAL"
    echo "Remote is named $REMOTE"
elif [[ "$1" != "$REMOTE" ]]; then
    REMOTE=""
fi

if [[ "$1" == vulcan || (-n "$REMOTE" && ($REMOTE == vulcan || $REMOTE == home)) ]]; then
    ARGS="$ARGS $REMOTE"
    OPTS="$OPTS -j8"
    if [[ $fullsync == false ]]; then
        OPTS="$OPTS -c sync"
    fi

elif [[ "$1" == hermes || (-n "$REMOTE" && ($REMOTE == hermes || $REMOTE == hermesw)) ]]; then
    ARGS="$ARGS $REMOTE"
    OPTS="$OPTS -j8"
    if [[ $fullsync == false ]]; then
        OPTS="$OPTS -c sync"
    fi

elif [[ "$1" == athena || (-n "$REMOTE" && $REMOTE == athena || $REMOTE == build) ]]; then
    ARGS="$ARGS $REMOTE"
    OPTS="$OPTS -j8"
    if [[ $fullsync == false ]]; then
        OPTS="$OPTS -c sync"
    fi

fi

if [[ ( $LOCAL == vulcan && $REMOTE == hermes ) ||
      ( $LOCAL == hermes && $REMOTE == vulcan ) ]]; then
    (cd ~/doc/org && syncit)
    (cd ~/kadena/docs && syncit)
fi

echo pushme $OPTS $ARGS "$@"

pushme --config $HOME/.config/pushme \
       --si --ssh="ssh -A -F $HOME/.ssh/config" \
       --rsync=~/.nix-profile/bin/rsync $OPTS $ARGS "$@"

### pushme ends here
