#!/bin/bash -e

CACHE=/Volumes/mybook/Machines/nix-binary-cache

nix-push --dest $CACHE --link --key-file ~/.nix/sk \
         --manifest --url-prefix http://ftp.newartisans.com/pub/nix-binary-cache \
         $(readlink -f ~/.nix-profile)

(cd ~/.nix-defexpr/nixpkgs ; git rev-parse HEAD) > $CACHE/commit.txt

exec rsync -aP --delete $CACHE/ jw3:/srv/ftp/pub/nix-binary-cache/
