#!/bin/bash

sudo cleanup -u

if ! running offlineimap; then
    cleanup-mail "$1"
fi

getall

(cd ~/.emacs.d/mirror/Marmalade; httrack -X0 --update)

git find-fetch ~/Archives/

pushme

### pushall ends here
