#!/bin/bash

pushme -F "$@"

if [[ -d /Volumes/Vault/Dropbox ]]; then
    pushme vault "$@"
fi

if [[ $(hostname) == "Vulcan.local" || $(hostname) == "vulcan.local" ]]; then
    pushme titan "$@"
fi

(sudo cleanup -u; sudo cleanup -u; sudo cleanup -u) > /dev/null 2>&1

### pushall ends here
