#!/bin/bash

len=$1
if [[ -z "$len" ]]; then
   len=16
fi

apg -E "Il10O^%_!#.\`'\"\$\\&;,|*-()[]{}<>~-/=?+:" -d -a1 -n1 -m$len -x$len | pbcopy

echo Randomly generated password \($len chars\) now on the clipboard.
