#!/bin/bash

#set -o errexit

runtests=false
if [[ $1 == '--tests' ]]; then
    runtests=true
    shift 1
fi

error=false
if ! make-distcc > /tmp/build.$$ 2>&1; then
    error=true
fi

cat /tmp/build.$$ | egrep -av '(Creating |Updating |Linking |Copying |config\.status: |Regenerating |Making Clang |lit\.cfg:|Building |Compiling |Nothing to be done|=======|\*\*\*\*\*)'
rm -f /tmp/build.$$

if [[ $error == true ]]; then exit 1; fi

if [[ $runtests == true ]]; then
    cd tools/clang/test

    error=false
    if ! make > /tmp/build.$$ 2>&1; then
        error=true
    fi

    cat /tmp/build.$$ | egrep -av '(Running |Making Clang |lit\.cfg:|Testing Time|Testing: 0)'
    rm -f /tmp/build.$$

    if [[ $error == true ]]; then exit 1; fi
fi
