#!/bin/sh
sudo rsync $1 -aXP --delete --exclude=.TemporaryItems/ --exclude=.Caches/ --exclude=Products/ --exclude=.fseventsd/ --exclude=.Spotlight-V100/ --exclude=.DS_Store --exclude=.Trashes/ --exclude='/Downloads/**/*.VOB' /Volumes/RAID/ /Volumes/AA1T/
