#!/bin/bash

fw_script=$HOME/src/firewall/rc.firewall

GATEWAY=$(netstat -nr -f inet | grep ^default | awk '{print $2}')

sudo route add 208.70.150.153 $GATEWAY
sudo route add 208.70.150.157 $GATEWAY

#PROXY=localhost:8118
#REMOTE=208.70.150.157:80
#htc -P $PROXY -F 5000 $REMOTE

sudo sh $fw_script --blackhole --stealth \
    --trusted-tcp 8140 \
    en1::208.70.150.153 en1 \
    vmnet8+win::192.168.36.0/24 \
    tun1::10.9.0.0/24 tun1 \
    tap0+win::10.9.19.0/24 \
    tap0+win::172.24.8.0/24 tap0

ssh -fNL localhost:5000:208.70.150.153:1195 jw
