#!/bin/bash -xe

HDIR=$HOME/Library/Hoogle

test -d $HDIR || mkdir -p $HDIR
cd $HDIR

function import_dbs() {
    find $1 -name '*.txt' \
        | parallel 'cp -p {} .; perl -i -pe "print \"\@url file://{//}/index.html\n\" if /^\@version/;" {/}; hoogle convert {/}'
}

import_dbs $HDIR/pkgs/.hsenv/ghc/share/doc/ghc/html/libraries
import_dbs $HDIR/pkgs/.hsenv/cabal/share/doc/x86_64-osx-ghc-7.6.3

rm -f default.hoo rehoo*

time hoogle data -d $HDIR --redownload -l $(echo *.txt | sed 's/\.txt//g')
time rehoo -j4 -c64 .
