#!/bin/bash -x

NIX_FLAGS="-k -Q -j8 --show-trace"

nix-env $NIX_FLAGS -u --leq

cd ~/crash
nix-build $NIX_FLAGS -A crashEnv

cd ~/doc/newartisans
nix-build ~/src/nixpkgs $NIX_FLAGS -A pkgs.haskellPackages_ghc783.newartisans

for j in                                \
    haskellPackages_ghc763_profiling    \
    haskellPackages_ghc783_profiling
do
    for i in                            \
        $j.bugs                         \
        $j.consistent                   \
        $j.findConduit                  \
        $j.gitAll                       \
        $j.hours                        \
        $j.loggingHEAD                  \
        $j.pushme                       \
        $j.simpleMirror                 \
        $j.theseHEAD                    \
        $j.gitlib                       \
        $j.hlibgit2                     \
        $j.gitMonitor                   \
        $j.newartisans                  \
        $j.c2hsc                        \
        $j.shellyHEAD                   \
        $j.lensHEAD                     \
        $j.machinesHEAD                 \
        $j.exceptionsHEAD               \
        $j.conduitHEAD                  \
        $j.conduitExtraHEAD             \
        $j.conduitCombinatorsHEAD       \
        $j.narwhal
    do
        nix-shell ~/src/nixpkgs $NIX_FLAGS -A pkgs.$i --pure --command exit
    done
done

for i in   \
    ledger
do
    nix-shell ~/src/nixpkgs $NIX_FLAGS -A pkgs.$i --pure --command exit
done
