#!/bin/bash -x

NIX_FLAGS="-k -Q -j8 --show-trace"

find ~/ -name result -type l -delete
find ~/ -name Setup -type f -delete
find ~/ -name dist -type f -delete

cd ~/src/hours
nix-cabal-build $NIX_FLAGS

cd ~/bae/crash
nix-build $NIX_FLAGS -A crashEnv

cd ~/doc/newartisans
nix-cabal-build $NIX_FLAGS

for j in                                \
    haskellPackages_ghc784              \
    haskellPackages_ghc784_profiling
do
    for i in                            \
        $j.bugs                         \
        $j.consistent                   \
        $j.AgdaPrelude                  \
        $j.findConduit                  \
        $j.simpleConduitHEAD            \
        $j.taskPool                     \
        $j.gitAll                       \
        $j.fuzzcheck                    \
        $j.hnix                         \
        $j.hours                        \
        $j.loggingHEAD                  \
        $j.pushme                       \
        $j.simpleMirror                 \
        $j.theseHEAD                    \
        $j.gitlib                       \
        $j.hlibgit2                     \
        $j.gitMonitor                   \
        $j.newartisans                  \
        $j.c2hsc                        \
        $j.shellyHEAD                   \
        $j.shellyExtraHEAD              \
        $j.foldlHEAD                    \
        $j.lensHEAD                     \
        $j.machinesHEAD                 \
        $j.exceptionsHEAD
    do
        nix-shell ~/src/nixpkgs $NIX_FLAGS -A pkgs.$i --pure --command exit
    done
done

for i in ledger
do
    nix-shell ~/src/nixpkgs $NIX_FLAGS -A pkgs.$i --pure --command exit
done
