#!/bin/bash -e

DIR=$HOME/.cabal/share/hoogle/databases

test -d $DIR || mkdir -p $DIR
cd $DIR

rm -f default.hoo rehoo*

time ~/src/tools/hoogle/cabal-dev/bin/hoogle data -r -l all
time rehoo -j4 -c64 .
