#!/bin/zsh

set -e

cabal clean
rm -fr dist

if [[ "$1" == "opt" ]]; then
    cabal configure --enable-tests --enable-benchmarks -O2
else
    cabal configure --enable-tests --enable-benchmarks -p       \
        --enable-executable-profiling
    #    --ghc-option=-prof                      \
    #    --ghc-option=-fprof-auto                \
    #    --ghc-option=-fprof-auto-calls
    #--ghc-option=-fhpc                      \
fi

cabal build
cabal test
