#!/bin/bash

find . \( -name '*.tgz' -o \
          -name '*.tar.gz' -o \
          -name '*.tar' -o \
          -name '*.tbz' -o \
          -name '*.zip' -o \
          -name '*.tar.bz2' -o \
          -name '*.dmg' \) -print \
| \
while read file; do
    filedir=$(dirname "$file")
    filebase=$(basename "$file")
    if echo $file | grep -q '\.dmg$'; then
	(cd "$filedir"; bzdmg "$filebase")
    elif echo $file | grep -q '\.tar$'; then
	(cd "$filedir"; 7za a "$filebase".7z "$filebase" && rm -f "$filebase")
    elif echo $file | egrep -q '\.(tar\.gz|tgz)$'; then
	(cd "$filedir"; gzip -dv "$filebase")
	filebase=$(echo "$filebase" | sed 's/(\.tar\.gz|\.tgz)$/.tar/')
	(cd "$filedir"; 7za a "$filebase".7z "$filebase" && rm -f "$filebase")
    elif echo $file | egrep -q '\.(tar\.bz2|tbz)$'; then
	(cd "$filedir"; bzip2 -dv "$filebase")
	filebase=$(echo "$filebase" | sed 's/(\.tar\.bz2|\.tbz)$/.tar/')
	(cd "$filedir"; 7za a "$filebase".7z "$filebase" && rm -f "$filebase")
    elif echo $file | grep -q '\.zip$'; then
	(cd "$filedir"; safe-unzip "$filebase" && rm -f "$filebase")
	filebase=$(echo "$filebase" | sed 's/\.zip$//')
	(cd "$filedir"; tar cf - "$filebase" | \
	    7za -si a "$filebase".tar.7z && rm -fr "$filebase")
    fi
done
