#!/bin/bash

# Listen to connections from the VPN to our address as known to them
# (10.9.19.82) and transparently redirect the traffic to our Windows XP box.
# I need to use netcat because this machine (my Mac) must sit in between the
# connect as a "broker" of sorts, since the shared networking support in
# Parallels will not accept packets which have been redirected from another
# source; they *must* be seen to come from the Mac itself.

sudo tcpserver 10.9.19.82 80 nc 10.211.55.9 80
