#!/bin/zsh

for dir in "$@"; do
    toc_file=$(ls -1 $dir/*.toc)
    if [[ -f $toc_file ]]; then
        base=$(basename $toc_file | sed 's/\.toc$//')
        mkdir $base
        echo mv $(dirname $toc_file)/* $base
        mv $(dirname $toc_file)/* $base
        mv $base $(dirname $toc_file)
    fi
done
