#!/bin/bash

sudo renice -15 $(pid LaunchBar) \
	        $(pid Contents/MacOS/Dock) \
	        $(pid Resources/WindowServer) \
	        $(pid QuicKeys\\.app/Contents/MacOS/QuicKeys) \
	        $(pid QuicKeysBackgroundEngine\\.app/Contents/MacOS/QuicKeysBackgroundEngine) \
	        $(pid Default\ Folder\ X\ Helper)

sudo renice  15 $(pid diskimages) \
	        $(pid Speed\ Download)
