#!/bin/bash

DATA=${1:-/Volumes/Files/ledger.dat}
if [[ ! -f "$DATA" ]]; then
   echo Cannot read Ledger data from '$DATA'
   exit 1
fi

EXEC=$(which ledger)
if [[ -z "$EXEC" ]]; then
   EXEC=$HOME/Products/ledger/ledger
fi

if [[ ! -x "$EXEC" ]]; then
   echo Cannot find Ledger executable
   exit 1
fi

LESS=--quit-if-one-screen exec $EXEC -f "$DATA" --pager less
