#!/bin/bash

host=$(basename "$1")
host=$(echo "$host" | sed 's/\.vmwarevm//')

mac=$(grep "ethernet.*Address = " "$1"/*.vmx | sed 's/.* = "//' | sed 's/".*$//')

ip=$2

echo host $host mac $mac ip $ip

dhcpd_conf="/Library/Application Support/VMware Fusion/vmnet8/dhcpd.conf"

if grep -q "$host" "$dhcpd_conf"; then
    echo Host $host has already been reserved.
    exit 1
fi

cat >> "$dhcpd_conf" <<EOF

host $host {
    hardware ethernet $mac;
    fixed-address $ip;
}
EOF

"/Library/Application Support/VMware Fusion/boot.sh" --restart

cat >> /etc/hosts <<EOF
$ip	$host
EOF

exit 0
