#!/bin/bash -xe

(sudo killall gpg-agent || exit 0)
(sudo killall shutdown-gpg-agent || exit 0)

launchctl unload ~/Library/LaunchAgents/mac.gpg-agent.plist
sleep 2
launchctl load ~/Library/LaunchAgents/mac.gpg-agent.plist
