#!/bin/bash

for item in "$@"; do
    path=$(abspath "$item")
    dest=$(echo "$path" | sed 's/\/Users\/johnw/\/Users\/johnw\/Archives\/Retired/')
    dest=$(echo "$dest" | sed 's/\/Volumes\/Data/\/Volumes\/Data\/Archives\/Retired/')
    destdir=$(dirname "$dest")
    mkdir -p "$destdir"
    mv "$path" "$dest"
done
