#!/bin/bash

for item in "$@"; do
    path=$(abspath "$item")
    dest=$(echo "$path" | sed 's/\/Users\/johnw/\/Users\/johnw\/Archives\/Retired/')
    mkdir -p $(dirname "$dest")
    mv "$path" "$dest"
done
