#!/bin/bash -e

retire_into=FALSE
if [[ "$1" == "--into" ]]; then
    shift 1
    retire_into="$1"
    shift 1
fi

for path in "$@"; do
    abs=$(abspath "$item")

    dest=$(echo "$abs" | sed 's/\/Users\/johnw/\/Users\/johnw\/Archives\/Retired/')
    dest=$(echo "$dest" | sed 's/\/Volumes\/Data/\/Users\/johnw\/Archives\/Retired/')
    dest=$(echo "$dest" | sed 's/\/Volumes\/tank/\/Users\/johnw\/Archives\/Retired/')

    if [[ "$retire_into" != FALSE ]]; then
        dest="$retire_into"
        destdir=$(dirname "$dest")
        mkdir -p "$destdir"
    else
        mkdir -p "$dest"
    fi

    if [[ -d "$path" ]]; then
        echo tardir "$path"
        ARCHIVE=$(tardir "$path")
        echo mv "$ARCHIVE" "$dest"
        mv -v "$ARCHIVE" "$dest"
        echo rm -fr "$path"
        rm -fr "$path"
    else
        echo mv "$path" "$dest"
        mv "$path" "$dest"
    fi
done
