#!/usr/bin/perl
$volume=shift @ARGV;
$oroot=shift @ARGV;
$tracks=shift @ARGV;
$width=0;
$height=0;
$start=1;

foreach $arg (@ARGV ) {
    if ( $arg =~ /-width=(\d+)/ ) {
        $width=$1;
    } elsif ( $arg =~ /-height=(\d+)/ ) {
        $height=$1;
    } elsif ( $arg =~ /-wide=(\d+)/ ) {
        $width=$1;
    } elsif ( $arg =~ /-high=(\d+)/ ) {
        $height=$1;
    } elsif ( $arg =~ /-start=(\d+)/ ) {
        $start=$1;
    }
}

my $usage=0;
if ( ! -d "$volume" ) {
  print STDERR "no volume $volume -- wrong name for disk or no disk\n";
  $usage++;
}

if ( $oroot eq '' ) {
  print STDERR "missing filename root (second argument)\n";
  $usage++;
}

if ( $tracks == 0 ) {
  print STDERR "missing tracks (third argument)\n";
  $usage++;
}

if ( $usage ) {
  print STDERR "Usage: ripper.tool volume fileroot tracks\n";
}

my $sizearg='';
if ( $width != 0 and $height != 0 ) {
    $sizearg="--width $width --height $height";
}

foreach $track ( $start .. $tracks ) {
    if ( ! -f "$oroot.$track.mp4" ) {
        my $cmd = "/Applications/Misc/HandBrakeCLI"
            . " --input '$volume/VIDEO_TS'"
            . " --output $oroot.$track.mp4"
            . " --ab 160"
            . " --aencoder faac"
            . " --arate 48"
            . " --audio 1"
            . " --cpu 16"
            . " --deinterlace"
            . " --drc 0.0"
            . " --encoder x264"
            . " --format mp4"
            . " --large-file"
            . " --loose-anamorphic"
            . " --markers"
            . " --maxWidth 1024"
            . " --mixdown dpl2"
            . " --pfr"
            . " --quality 20.0"
            . " --rate 29.97"
            . " --title $track"
            . " --two-pass"
            . " --vb 1500"
            . $sizearg
            ;

        print STDERR "$cmd\n";
        system($cmd);
    }
}
