#!/usr/bin/perl

$volume=shift @ARGV;
$oroot=shift @ARGV;
$tracks=shift @ARGV;
$width=0;
$height=0;
$start=2;

foreach $arg (@ARGV ) {
    if ( $arg =~ /-width=(\d+)/ ) {
        $width=$1;
    } elsif ( $arg =~ /-height=(\d+)/ ) {
        $height=$1;
    } elsif ( $arg =~ /-wide=(\d+)/ ) {
        $width=$1;
    } elsif ( $arg =~ /-high=(\d+)/ ) {
        $height=$1;
    } elsif ( $arg =~ /-start=(\d+)/ ) {
        $start=$1;
    }
}

my $usage=0;
if ( ! -d "$volume" ) {
  print STDERR "no volume $volume -- wrong name for disk or no disk\n";
  $usage++;
}

if ( $oroot eq '' ) {
  print STDERR "missing filename root (second argument)\n";
  $usage++;
}

if ( $tracks == 0 ) {
  print STDERR "missing tracks (third argument)\n";
  $usage++;
}

if ( $usage ) {
  print STDERR "Usage: ripper.tool volume fileroot tracks\n";
}

my $sizearg='';
if ( $width != 0 and $height != 0 ) {
    $sizearg="--width $width --height $height";
}

foreach $track ( $start .. $tracks ) {
    $offset = ($track - $start) + 1;
    if ( ! -f "$oroot.$offset.m4v" ) {
        my $cmd = "HandBrakeCLI"
            . " --input '$volume/VIDEO_TS'"
            . " --output '$oroot.$offset.m4v'"
            . " -e x264 -q 20 -B 160 -s scan -F "
            . $sizearg
            ;

        print STDERR "$cmd\n";
        system($cmd);
    }
}
