#!/bin/bash

POOL=${1:-tank}

while true; do
    date
    hour=$(($(date +%-H)))
    if (( hour >= 2 && hour < 3 )); then
        b2-restic /Volumes/${POOL} ${POOL}
    else
        sleep 1h
    fi
done
