#!/usr/bin/env bash

POOL=${1:-tank}

while true; do
    date
    hour=$(($(date +%-H)))
    if (( hour >= 4 && hour < 5 )); then
        b2-restic /Volumes/${POOL} ${POOL}
    else
        sleep 1h
    fi
done
