#!/bin/sh

while true
do
    sleep ${1:-10}
    if ping -W 2500 -c 1 -q google.com > /dev/null 2>&1
    then
        echo "\033[32mOn:  $(date)\033[0m"
    else
        echo "\033[31mOFF: $(date)\033[0m"
    fi
done
