#!/usr/bin/env bash
for dir in $buildInputs; do
    file="$dir/share/doc/rust/html/${1:-std}/index.html"
    if [[ -f "$file" ]]; then
        exec open "$file"
    fi
done
echo "${1:-std} Rust documentation not found"
exit 1
