#!/bin/bash

if [[ "$1" == "--core" ]]; then
    /usr/local/stow/sbcl-1.0.11-i386/bin/sbcl "$@"
else
    /usr/local/stow/sbcl-1.0.11-i386/bin/sbcl \
	--core /usr/local/stow/sbcl-1.0.11-i386/lib/sbcl/sbcl.core "$@"
fi
