#!/bin/bash

relink_entries() {
    src="$1"
    tgt="$2"

    ls -a1 "$src" | while read i; do
        if [[ "$i" != "."                            \
           && "$i" != ".."                           \
           && "$i" != ".DS_Store"                    \
           && "$i" != ".Spotlight-V100"              \
           && "$i" != ".Trashes"                     \
           && "$i" != ".fseventsd"                   \
           && "$i" != "Applications"                 \
           && "$i" != "Application Support"          \
           && "$i" != "Library"                      \
           ]]; then
            if [[ ! -h "$src/$i"                     \
               && ! -h "$tgt/$i"                     \
               ]]; then
                echo "Re-linking $src/$i -> $tgt/$i"
                sudo rm -fr "$tgt/$i"
                (cd "$tgt"; ln -sf "$src/$i" .)
            fi
        fi
    done
}

relink_entries "/Volumes/Private" "$HOME"
relink_entries "/Volumes/Data" "$HOME"

relink_entries "/Volumes/Private/Library" "$HOME/Library"
relink_entries "/Volumes/Private/Library/Application Support" \
               "$HOME/Library/Application Support"
