#!/bin/bash

git send-email --compose \
    --from="John Wiegley <johnw@boostpro.com>" \
    --bcc="David Abrahams <dave@boostpro.com>" \
    --to=cfe-commits@cs.uiuc.edu \
    --smtp-server=/opt/local/bin/msmtp \
    "$@"
