#!/bin/bash

zfs list -H -r -t filesystem -o name RAID | tail +2 | \
while read fs rest
do
    echo Sending $fs
    ssh -f -t -t titan 'sudo /root/bin/mbuffer -I 192.168.9.113:10000 -s128k -m1G -P10 | sudo /usr/sbin/zfs recv -d -F data'
    sleep 5
    socat -b131072 -u -T60 PIPE:/tmp/pipe.$$ tcp:192.168.9.133:10000 &
    sleep 2
    zfs send $fs@today > /tmp/pipe.$$
    wait
done
