#!/usr/bin/env python

import sys
import os
import re
import time
import dircache
import email
import rfc822
import email.FeedParser

args = sys.argv[1:]

i = 0
l = len(args)
while i < l:
    dir = args[i]; i += 1
    assert os.path.isdir(dir)

    for entry in dircache.opendir(dir):
        file = os.path.join(dir, entry)

        if not os.path.isfile(file):
            continue
        if os.path.splitext(file)[1] != ".msg":
            continue

        msg = open(file)

        p = email.FeedParser.FeedParser()
        p.feed(msg.read())
        msg.close()
        message = p.close()

        if message.defects:
            sys.stderr.write('ERROR: Defects in message: ' + file + '\n')

        sent = rfc822.parsedate(message['Date'])

        if sent:
            os.utime(file, (time.mktime(sent), time.mktime(sent)))
        else:
            sys.stderr.write('WARNING: No parsable date in message: ' + file + '\n')
