#!/usr/bin/env python

import os
import sys
import time
import email

for path in sys.argv[1:]:
    with open(path, 'r') as fd:
        msg = email.message_from_string(fd.read())

    if 'Date' in msg:
        then = None
        try: then = time.mktime(email.utils.parsedate(msg['Date']))
        except: pass
        if then:
            os.utime(path, (then, then))

### setdate ends here
