#!/bin/bash

DEPS=""
export DEPS

function find_deps() {
    for mod in "$@"; do
	if echo "$DEPS" | grep -vq " $mod"; then
	    DEPS="$DEPS $mod"
	    echo $mod
	    port deps $mod | while read line; do
		if echo "$line" | grep -vq "dependencies"; then
		    find_deps $line
		fi
	    done
	fi
    done
}

find_deps "$@" | sort | uniq
