#!/bin/bash

pid=$(ps axw | grep "8118:localhost:8118" | grep -v grep | awk '{print $1}')

if [[ -n "$pid" ]]; then
    sudo kill $pid
    sleep 60
else
    sudo launchctl unload /Library/LaunchDaemons/org.macports.Privoxy.plist
fi

sudo -u privoxy cp -p /usr/local/etc/privoxy/config.direct /usr/local/etc/privoxy/config
sudo launchctl load -w /Library/LaunchDaemons/org.macports.Privoxy.plist

qknotify "Privoxy tunnel disabled" "socksoff"
