#!/bin/bash

notify=notifyrun
if [[ $1 == ss ]]; then
    notify=exec
fi

args=$(echo $(printf '%q ' "$@") | sed 's/\\/\\\\/g')
command="cd \\\"$(pwd)\\\" && $notify $args"

osascript <<EOF
on replace_chars(txt, srch, repl)
  set AppleScript's text item delimiters to the srch
  set the item_list to every text item of txt
  set AppleScript's text item delimiters to the repl
  set txt to the item_list as string
  set AppleScript's text item delimiters to ""
  return txt
end replace_chars

tell application "iTerm"
  activate
  
  -- talk to the first terminal
  tell the first terminal
    
    -- launch a default shell in a new tab in the same terminal
    launch session "Default Session"
    
    tell the last session
      
      -- write some text
      write text "$command"
      
    end tell
  end tell
end tell
EOF
