#!/bin/bash

open ~/Mirrors/Hackage.sparsebundle
sleep 5

cd /Volumes/Hackage

export PATH=$PATH:/usr/local/tools/hackage-server/cabal-dev/bin

(sleep 300 ; hackage-mirror -v mirror.cfg) &

exec hackage-server run --port=9010
