#!/bin/bash

pgrep -q Emacs || runemacs

if [[ -d ~/Applications/Brave\ Browser\ Apps.localized/Google\ Meet.app ]]; then
    open ~/Applications/Brave\ Browser\ Apps.localized/Google\ Meet.app
fi

exec open -j -g                                                         \
    /Applications/Drafts.app                                            \
    /Applications/Fantastical.app                                       \
    /Applications/Soulver\ 3.app                                        \
    /Applications/Whisper\ Transcription.app                            \
    /Applications/Just\ Press\ Record.app                               \
                                                                        \
    /Applications/Anki.app                                              \
    /Applications/Zotero.app                                            \
                                                                        \
    /Applications/Firefox.app                                           \
    /Applications/Brave\ Browser.app                                    \
    /Applications/Asana.app                                             \
    /Applications/Notion.app                                            \
                                                                        \
    /Applications/iTerm.app                                             \
                                                                        \
    /System/Applications/Messages.app                                   \
    /Applications/Slack.app                                             \
    /Applications/Discord.app                                           \
    /Applications/Signal.app                                            \
    /Applications/Telegram.app                                          \
    /Applications/WhatsApp.app                                          \
    /Applications/Zulip.app
