#!/bin/bash

#cat > /dev/null

function squid_running() {
    PIDFILE=/opt/local/var/run/squid/squid.pid

    started=false

    if [[ -f $PIDFILE ]]; then
	pid=$(cat $PIDFILE)
	
	if ps axwww | grep -q "^ *$pid *.*sbin/squid"; then
	    return 0
	fi
    fi

    return 1
}

if ! squid_running; then
    sudo rm -f /opt/local/var/run/squid/squid.pid
    sudo launchctl unload /Library/LaunchDaemons/org.macports.Squid.plist
    sudo launchctl load -w /Library/LaunchDaemons/org.macports.Squid.plist
    sleep 5
    squid_running || exit 1
    squidclient mgr:offline_toggle
fi

exit 0
