#!/bin/bash

pidgrep -q Emacs || runemacs

if [[ $(hostname) =~ [Vv]ulcan ]]; then
    pidgrep -q ERC || runemacs --alt
fi

exec open                                       \
    /Applications/Discord.app                   \
    /Applications/Drafts.app                    \
    /Applications/Fantastical.app               \
    /Applications/Firefox.app                   \
    /Applications/Signal.app                    \
    /Applications/Slack.app                     \
    /Applications/Soulver\ 3.app                \
    /Applications/Telegram.app                  \
    /Applications/WhatsApp.app                  \
    /Applications/iTerm.app                     \
    /System/Applications/Messages.app
