#!/usr/bin/env bash

CODEX_MODEL=gpt-5.5
CLAUDE_MODEL=claude-fable-5

WORKDIR="$2"
TITLE=${3:-$(basename "$2")}

case $1 in
    codex)
        agent-deck add                                                          \
                   -c "codex --dangerously-bypass-approvals-and-sandbox"        \
                   --model $CODEX_MODEL                                         \
                   -t $TITLE                                                    \
                   "$WORKDIR"
        ;;

    claude)
        agent-deck add                                                          \
                   -c "claude --effort max --dangerously-skip-permissions"      \
                   --model $CLAUDE_MODEL                                        \
                   -t $TITLE                                                    \
                   "$WORKDIR"
        ;;
esac

agent-deck session start $TITLE
