#!/bin/bash
# gpg is in /opt/local/

PATH=/opt/local/bin:$PATH

# Script for ensuring only one instance of gpg-agent is running and if there
# is not one, start an instance of gpg-agent.
if test -f $HOME/.gpg-agent-info && \
    kill -0 `cut -d: -f 2 $HOME/.gpg-agent-info` 2>/dev/null; then
    GPG_AGENT_INFO=`cat $HOME/.gpg-agent-info`
    export GPG_AGENT_INFO
else
    gpg-agent --daemon --use-standard-socket --write-env-file "${HOME}/.gpg-agent-info"
fi

# Imperative that this environment variable always reflects the output of the
# tty command.
GPG_TTY=`tty`
export GPG_TTY
