#!/bin/bash

#cat > /dev/null

function aox_running() {
    PIDFILE=/usr/local/archiveopteryx/lib/pidfiles/archiveopteryx.pid

    started=false

    if [[ -f $PIDFILE ]]; then
	pid=$(cat $PIDFILE)
	
	if ps axwww | grep -q "^ *$pid *.*sbin/archiveopteryx"; then
	    return 0
	fi
    fi

    return 1
}

if ! aox_running; then
    sudo rm -f /usr/local/archiveopteryx/lib/pidfiles/*.pid
    sudo /usr/local/archiveopteryx/bin/aox start
    sleep 5
    aox_running || exit 1
fi

exit 0
