#!/bin/zsh

find . -name .svn -type d | while read dir; do
    (cd "$dir"/.. ; echo "SVN: $dir"; svn -N status)
done

find . -name .git -type d | while read dir; do
    (cd "$dir"/.. ; echo "GIT: $dir"; git status)
done
