#!/bin/sh

case $1 in
    ghc) ver=$2
        brew switch ghc $ver
	if [[ $ver == 7.6.3 ]]; then
	    brew link haskell-platform
	else
	    brew unlink haskell-platform
	fi
        ;;
    *) echo $1 unrecognized ;;
esac
