#!/usr/bin/env bash

cd ~/org; git addremove && gasync

cd ~/doc; changes
cd ~/doc/accounts; changes
cd ~/src/scripts; changes
cd ~/src/nix; changes
cd ~/.config/pushme/conf.d; changes

cd ~/.emacs.d
load-env-emacs29MacPort make init.el
changes
