#!/usr/bin/env bash -xe

if [[ $(hostname) == "Vulcan.local" || $(hostname) == "vulcan.local" ]]; then
    REMOTE=hermes
else
    REMOTE=vulcan
fi

ssh $REMOTE 'cd Archives ; gaadd .'
for i in titan ; do
    ssh $REMOTE "cd Archives ; gacopy $i"
done

((cd /Volumes/My\ Passport/Archives && gaadd . &&
 for i in mybook titan ; do gacopy $i; done) || exit 0)

cd /Volumes/My\ Book/Archives
gaadd .
gaget .
for i in titan ; do gacopy $i; done

ssh titan 'cd /tank/Archives ; git annex sync'
