#!/usr/bin/env bash

set -euo pipefail

card

for dir in                                      \
    ~/.config/pushme                            \
    ~/doc                                       \
    ~/doc/accounts                              \
    ~/Documents/Obsidian                        \
    ~/doc/org                                   \
    ~/src/nix                                   \
    ~/src/scripts
do
    cd $dir
    changes
done

cd ~/doc/org
make store

cd ~/.emacs.d
load-env-emacs$EMACSVER make init.elc && rm -f init.elc

prep

org --config ~/org/org.yaml		\
    --keywords ~/org/org.dot		\
    site build ~/org/newartisans/config.yaml

org --config ~/org/org.yaml		\
    --keywords ~/org/org.dot		\
    site build ~/org/johnwiegley/config.yaml

export RCLONE_PASSWORD_COMMAND="$(which pass) show Passwords/rclone"

rclone sync -v                                                  \
       --checksum                                               \
       --refresh-times                                          \
       --delete-after                                           \
       ~/org/newartisans/_site                                  \
       fastmail:/johnw.newartisans.com/files/newartisans

rclone sync -v                                                  \
       --checksum                                               \
       --refresh-times                                          \
       --delete-after                                           \
       ~/org/johnwiegley/_site                                  \
       fastmail:/johnw.newartisans.com/files/johnwiegley
