#!/bin/bash

git find-fetch "$@"	\
    ~/Archives/Admin	\
    ~/Archives/C++	\
    ~/Archives/CMS	\
    ~/Archives/Chess	\
    ~/Archives/Emacs	\
    ~/Archives/Erlang	\
    ~/Archives/Git	\
    ~/Archives/Groovy	\
    ~/Archives/Java	\
    ~/Archives/Linux	\
    ~/Archives/Projects \
    ~/Archives/Python	\
    ~/Archives/Ruby	\
    ~/Archives/Sources	\
    ~/Archives/XML	\
    ~/Archives/dotNET	\
    ~/Projects ~/Documents ~/Sites \
    ~/Library/Emacs ~/Library/Application\ Support ~/Library/Scripts

echo All repositories synchronized.
