#!/usr/bin/env bash

set -e

cd ~/org

git addremove
git annex sync --no-push --no-pull

for dir in                                      \
    ~/doc                                       \
    ~/doc/accounts                              \
    ~/src/scripts                               \
    ~/src/nix                                   \
    ~/.config/pushme/conf.d
do
    (cd $dir; changes)
done

cd ~/.emacs.d

load-env-emacs29MacPort make
changes
