#!/bin/bash -xe

cd ~/Archives
gaadd .
git annex sync
for i in mybook passport titan ; do gacopy $i; done

if [[ $(hostname) == "Vulcan.local" || $(hostname) == "vulcan.local" ]]; then
    REMOTE=hermes
else
    REMOTE=vulcan
fi

cd ~/Archives
ssh $REMOTE 'cd Archives ; gaadd .'
ssh $REMOTE 'cd Archives ; git annex sync'
for i in titan ; do
    ssh $REMOTE "cd Archives ; gacopy $i"
done

cd /Volumes/My\ Passport/Archives
gaadd .
git annex sync
for i in mybook titan ; do gacopy $i; done

cd /Volumes/My\ Book/Archives
gaadd .
git annex sync
for i in titan ; do gacopy $i; done

ssh titan 'cd /tank/Archives ; git annex sync'
