#!/bin/bash

PATH=$PATH:$HOME/bin
STATUS=0

for archive in "$@"; do
    FILE=$(abspath "$archive")
    BASE=$(basename "$FILE")
    NAME=$(echo "$BASE" | perl -pe 's/\.(tar(\.(7z|gz|bz2))?|tgz|zip|7z|bin|pkg)$//')
    HERE=$(dirname "$FILE")

    cd "$HERE"

    if [[ -e "$NAME" ]]; then
	STATUS=1
    else
	mkdir "$NAME" || (echo "Failed to create directory $NAME"; exit 1)

	cd "$NAME"
	cp -p "$FILE" .

	FILE=$(abspath "$BASE")

	if echo "$BASE" | egrep -q '\.(zip|bin)$'; then
	    osascript <<EOF
    tell application "StuffIt Expander"
	run
	expand {POSIX file "$FILE"}
	quit
    end tell
EOF
	else
	    aunpack "$BASE"
	fi

	cd ..
	if ! hdiutil create -srcfolder "$NAME" "$NAME.dmg"; then
	    STATUS=1
	fi
	/bin/rm -fr "$NAME"
    fi
done

exit $STATUS
