#!/bin/bash

LOCAL=vulcan
REMOTE=hermes

if [[ $1 == --here ]]; then
    function update_direnv() {
        if [[ -d $1 ]]; then
            cd $1
            de
        fi
    }
else
    push hermes

    u $LOCAL rebuild

    ssh $REMOTE "NIX_CONF=$HOME/src/nix CACHE=$LOCAL u $REMOTE rebuild"

    function update_direnv() {
        if [[ -d $1 ]]; then
            cd $1
            de
            ssh $REMOTE "cd $1; CACHE=$LOCAL de"
        fi
    }

    u $LOCAL copy
fi


for dir in                                      \
    ~/src/agda/adders-and-arrows                \
    ~/src/agda/plfa                             \
    ~/src/category-theory                       \
    ~/src/ltl/coq                               \
    ~/src/ltl/simple-ltl                        \
    ~/src/notes/coq                             \
    ~/src/notes/haskell                         \
    ~/src/notes/rust                            \
    ~/src/sitebuilder                           \
    ~/src/trade-journal                         \
    ~/src/wallet                                \
                                                \
    ~/dfinity/master/rs                         \
    ~/dfinity/master/hs/analyzer                \
    ~/dfinity/dissolving/rs                     \
    ~/dfinity/merge/rs                          \
    ~/dfinity/formal-models
do
    echo "Updating direnv for $dir"
    update_direnv $dir
done
