#!/bin/bash
set -e

cd `mktemp -d -t unlaunch`

cat > "$1.plist"<<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0">
<dict>
	<key>Label</key>
	<string>$1</string>
	<key>Program</key><string>echo</string>
</dict>
</plist>
EOF

launchctl unload -w "$1.plist"
