#!/usr/bin/env python

import os
import re
import sys
import imaplib

server, userid = sys.argv[1:]

with open(os.path.join(os.environ['HOME'], '.authinfo'), 'r') as fd:
    for line in fd:
        match = re.match('machine (.+?) login (.+?) ' +
                         'password (.+?)( port ([0-9]+))', line)
        if match:
            machine, login, password, hasport, port = match.groups()
            if machine == server and userid == login:
                break

try:
    if hasport and int(port) == 993:
        imap = imaplib.IMAP4_SSL(machine, int(port) if hasport else 993)
    else:
        imap = imaplib.IMAP4(machine, int(port) if hasport else 143)
except:
    print "IMAP server is not running at this time"
    sys.exit(0)                         # ignore if we can't connect

imap.login(login, password)

imap.select('[Gmail].All Mail')
imap.search(None, '(TEXT "sample")')
imap.close()
imap.logout()

sys.exit(0)

### update-index ends here
