#!/bin/bash

if [[ "$1" == "-a" || "$1" == "--all" ]]; then
    if ! running fetchmail; then
        getmail &
    fi
fi

#
python2.7 ~/src/tools/mirror-hackage/mirror_hackage.py ~/Mirrors/Hackage

#
cabal update

if [[ "$1" == "--all" || "$1" == "-a" ]]; then
    cab outdated | awk '{print $1}' | xargs cabal install -j
    for i in $(seq 0 20); do
        yes | cabal-delete $(cabal-delete -l | tail +3 | awk '{print $1}')
    done > /tmp/cabal-delete.log 2>&1
fi

ghc-pkg check

#
cd /usr/local/Library
git stash && brew update && git stash pop
brew doctor

if [[ "$1" == "-a" ]]; then
    brew upgrade
fi

#
if [[ "$1" == "--all" ]]; then
    rebuild-hoogle &
fi

if [[ "$1" == "-a" ]]; then
    git all fetch ~/Archives/ ~/Projects/ ~/Contracts/ &
fi

wait

exit 0
