#!/bin/bash

cd ~/Messages

find Newsdir -name '.overview' -type f | \
    par -j32 'test -d Mirror/{//} || mkdir -p Mirror/{//}'
find Newsdir -name '[0-9]*' -type f | \
    par -j32 'test -f Mirror/{}.eml || ln ~/Messages/{} Mirror/{}.eml'

find Maildir -name 'cur' -type d | \
    par -j32 'test -d Mirror/{} || mkdir -p Mirror/{}'
find Maildir -name '[0-9]*.*' -type f | \
    par -j32 'test -f Mirror/{}.eml || ln ~/Messages/{} Mirror/{}.eml'
