#!/bin/bash
DIR=${1:-$HOME/src}
exec git each                                           \
     --dir "$DIR"                                       \
     fetch --all --no-tags --no-recurse-submodules -q
