#!/usr/bin/env bash

if [[ -d /etc/nixos ]]; then
    cd /etc/nixos
else
    cd ~/src/nix
fi

nix flake update llm-agents

if [[ -d /etc/srp-next ]]; then
    sudo nixos-rebuild switch --flake '.#ovh-vps'
elif [[ -d /etc/nixos ]]; then
    sudo nixos-rebuild switch --flake '.#vulcan'
else
    u switch
fi
