#!/usr/bin/env bash

update ~/src

for i in                                        \
    ~/src/concat                                \
    ~/src/coq                                   \
    ~/src/coq-equations                         \
    ~/src/emacs                                 \
    ~/src/haskell-infra                         \
    ~/src/proof-general
do
    (cd $i ; echo $i ; git pull)
done
