#!/usr/bin/env bash

cd ~/.config/home-manager

# pull latest nix-config from GitHub
nix flake lock --update-input nix-config
nix build '.#homeConfigurations.jwiegley.activationPackage'

./result/activate
