#!/bin/bash -ex

nix-env --set-flag priority 10 networkTools
nix-env --set-flag priority 100 langTools
nix-env --set-flag priority 500 buildTools
nix-env -q | egrep -v '(langTools)' | sed 's/-[0-9].*//' \
    | xargs nix-env -f '<nixpkgs>' "$@" -u

nix-env --set-flag priority 10 networkTools
nix-env --set-flag priority 100 langTools
nix-env --set-flag priority 500 buildTools

nix-env -q | sed 's/-[0-9].*//' | xargs nix-env -f '<nixpkgs>' "$@" -u
