#!/usr/bin/env bash

set -euo pipefail

update ~/doc ~/src ~/Models ~/Databases

pushme andoria hera
push all

upgrade hera || echo "upgrade hera exited with $?"

(cd ~/src/nix; changes)

sleep 10

push

update-remote
