#!/bin/sh
sudo rsync $1 -aXP --exclude=.TemporaryItems/ --exclude=.Caches/ --exclude=Products/ --exclude=Projects/ --exclude=.fseventsd/ --exclude=.Spotlight-V100/ --exclude=.DS_Store /Volumes/AA1T/ /Volumes/RAID/
