#!/bin/bash

ATTRNAME=checksum

verbose=false
if [[ "$1" == "-v" ]]; then
    verbose=true
    shift 1
fi

setonly=false
if [[ "$1" == "-s" ]]; then
    setonly=true
    shift 1
fi

error=false

for file in "$@"; do
    name=$(basename "$file")
    if [[ -f "$file" && \
	  "$name" != ".DS_Store" && "$name" != ".localized" ]]; then
	CHKSUM=$(xattr -p $ATTRNAME "$file" 2> /dev/null)
	if [[ -z "$CHKSUM" ]]; then
	    if [[ $verbose == true ]]; then
		echo "Warning: No existing checksum for $file, setting..."
	    fi
	    CURSUM=$(md5 -q "$file")
	    xattr -w $ATTRNAME $CURSUM "$file"
	    CHKSUM=$CURSUM
	elif [[ $setonly == false ]]; then
	    CURSUM=$(md5 -q "$file")
	    if [[ $CURSUM != $CHKSUM ]]; then
		echo "Error: Checksum mismatch for $file: $CURSUM != $CHKSUM" \
		    > /dev/stderr
		error=true
	    elif [[ $verbose == true ]]; then
		echo "Verified: $CHKSUM  $file"
	    fi
	fi
    fi
done

[[ $error == true ]] && exit 1
