#!/bin/bash

find . \( \
    -name '*.zip' -o \
    -name '*.ZIP' -o \
    -name '*.tbz' -o \
    -name '*.bz2' -o \
    -name '*.gz' -o \
    -name '*.tgz' -o \
    -name '*.rar' -o \
    -name '*.7z' -o \
    -name '*.iso' -o \
    -name '*.ISO' -o \
    -name '*.dmg' -o \
    -name '*.DMG' -o \
    -name '*.exe' -o \
    -name '*.EXE' -o \
    -name '*.msi' -o \
    -name '*.MSI' \
    \) -type f -print0 | xargs -0 verify "$@"
