#!/bin/bash

# verify, version 1.0
#   by John Wiegley <johnw@newartisans.com>

function sha1() {
    openssl sha1 "$1" | sed 's/.*= //'
}

if [[ -z "$1" ]]; then
    echo "usage: verify [OPTIONS] <FILE ...>"
    echo "options:"
    echo "  -v     be verbose about verification/checksum setting"
    echo "  -s     only set checksums for files which don't have them"
    echo "  -f     force setting the checksum even if file doesn't match"
    exit 1
fi

export ATTRNAME=checksum-sha1

export verbose=false
export setonly=false
export force=false

while [[ "${1:0:1}" == "-" ]]; do
    if [[ "$1" == "-v" ]]; then
        export verbose=true
        shift 1
    elif [[ "$1" == "-s" ]]; then
        export setonly=true
        shift 1
    elif [[ "$1" == "-f" ]]; then
        export force=true
        shift 1
    else
	break
    fi
done

error=false

function compare_checksum() 
{
    CHKSUM=$(xattr -p ${ATTRNAME} "$1" 2> /dev/null)

    if [[ -z "$CHKSUM" ]]; then
	if [[ $verbose == true || $setonly == true ]]; then
	    echo "Note: No existing checksum for $1, setting..."
	fi
	CURSUM=$(sha1 "$1")
	xattr -w ${ATTRNAME} $CURSUM "$1"
        case "$1" in
    	    *.dmg|*.cdr|*.iso|*.sparseimage)
    	        hdiutil checksum -type SHA1 "$1" ;;
        esac
    elif [[ $setonly == false ]]; then
	CURSUM=$(sha1 "$1")
	if [[ $CURSUM != $CHKSUM ]]; then
	    echo "Error: Checksum mismatch for $1: $CURSUM != $CHKSUM" \
		> /dev/stderr
	    if [[ $force == true ]]; then
		xattr -w ${ATTRNAME} $CURSUM "$1"
		case "$1" in
    		    *.dmg|*.cdr|*.iso|*.sparseimage)
    	                hdiutil checksum -type SHA1 "$1" ;;
		esac
	    fi
	    return 1
	elif [[ $verbose == true ]]; then
	    echo "Verified: $CHKSUM  $1"
	fi
    fi
    return 0
}

function validate_file() 
{
    if [[ $setonly == false ]]; then
	case "$1" in
	    *.zip)
		if [[ $verbose == true ]]; then
		    unzip -t "$1"
		else
		    unzip -qqt "$1"
		fi ;;

	    *.bz2|*.tbz)
		if [[ $verbose == true ]]; then
		    bzip2 -tv "$1"
		else
		    bzip2 -tq "$1"
		fi ;;

	    *.gz|*.tgz)
		if [[ $verbose == true ]]; then
		    gzip -tv "$1"
		else
		    gzip -tq "$1"
		fi ;;

	    *.rar)
		unrar t "$1" ;;

	    *.7z)
		7za t "$1" ;;

	    *.dmg|*.sparseimage)
		if [[ $verbose == true ]]; then
		    hdiutil verify "$1"
		else
		    hdiutil verify -quiet "$1"
		fi ;;
	esac
    fi
}

for file in "$@"; do
    name=$(basename "$file")
    if [[ -d "$file" ]]; then
	echo Verifying in directory $file ... > /dev/stderr
    elif [[ -f "$file" && "$name" != ".DS_Store" && \
	  "$name" != ".localized" ]]; then
	if ! compare_checksum "$file"; then
	    error=true
	fi
	if ! validate_file "$file"; then
	    error=true
	fi
    fi
done

[[ $error == true ]] && exit 1

exit 0
