#!/bin/bash

# verify, version 1.0
#   by John Wiegley <johnw@newartisans.com>

function sha1() {
    openssl sha1 "$1" | sed 's/.*= //'
}

if [[ -z "$1" ]]; then
    echo "usage: verify [OPTIONS] <FILE ...>"
    echo "options:"
    echo "  -v     be verbose about verification/checksum setting"
    echo "  -s     only set checksums for files which don't have them"
    echo "  -f     force setting the checksum even if file doesn't match"
    exit 1
fi

export ATTRNAME=checksum-sha1

export verbose=false
export setonly=false
export force=false

while [[ "${1:0:1}" == "-" ]]; do
    if [[ "$1" == "-v" ]]; then
        export verbose=true
        shift 1
    elif [[ "$1" == "-s" ]]; then
        export setonly=true
        shift 1
    elif [[ "$1" == "-f" ]]; then
        export force=true
        shift 1
    else
	break
    fi
done

error=false

function compare_checksum() 
{
    CHKSUM=$(xattr -p ${ATTRNAME} "$1" 2> /dev/null)
    if [[ -z "$CHKSUM" ]]; then
	if [[ $verbose == true || $setonly == true ]]; then
	    echo "Note: No existing checksum for $1, setting..."
	fi
	CURSUM=$(sha1 "$1")
	xattr -w ${ATTRNAME} $CURSUM "$1"
    elif [[ $setonly == false ]]; then
	CURSUM=$(sha1 "$1")
	if [[ $CURSUM != $CHKSUM ]]; then
	    echo "Error: Checksum mismatch for $1: $CURSUM != $CHKSUM" \
		> /dev/stderr
	    if [[ $force == true ]]; then
		xattr -w ${ATTRNAME} $CURSUM "$1"
	    fi
	    return 1
	elif [[ $verbose == true ]]; then
	    echo "Verified: $CHKSUM  $1"
	fi
    fi
    return 0
}

for file in "$@"; do
    name=$(basename "$file")
    if [[ -d "$file" ]]; then
	echo Verifying in directory $file ... > /dev/stderr
    elif [[ -f "$file" && "$name" != ".DS_Store" && \
	  "$name" != ".localized" ]]; then
	if ! compare_checksum "$file"; then
	    error=true
	fi
    fi
done

[[ $error == true ]] && exit 1

exit 0
