#!/bin/bash
exec rsync                                              \
    --exclude=/.Caches/                                 \
    --exclude=/.Spotlight-V100/                         \
    --exclude=/.TemporaryItems/                         \
    --exclude=/.Trash/                                  \
    --exclude=/.Trashes/                                \
    --exclude=/.fseventsd/                              \
    --exclude='/Temporary Items/'                       \
    --exclude='/Network Trash Folder/'                  \
    --filter='-p .DS_Store'                             \
    --filter='-p .localized'                            \
    --filter='-p .AppleDouble/'                         \
    --filter='-p .AppleDB/'                             \
    --filter='-p .AppleDesktop/'                        \
    --filter='-p .com.apple.timemachine.supported'      \
    -Ha "$@"
