#!/bin/bash

if [[ -x "/Library/Application Support/VMware Fusion/vmrun" ]]; then
    FUSION="/Library/Application Support/VMware Fusion"
elif [[ -x "/Applications/VMware Fusion.app/Contents/Library/vmrun" ]]; then
    FUSION="/Applications/VMware Fusion.app/Contents/Library"
else
    echo 'win-clangup: error: Could not find vmwrun'
    exit 1
fi

VM_DIR=/Users/johnw/Machines/Clang

VS2008_upstream="$VM_DIR/Win 7 x64 VS2008 upstream.vmwarevm/Windows 7 Ultimate x64.vmx"
VS2008_work="$VM_DIR/Win 7 x64 VS2008 work.vmwarevm/Windows 7 Ultimate x64.vmx"
VS2010_upstream="$VM_DIR/Win 7 x64 VS2010 upstream.vmwarevm/Windows 7 Ultimate x64.vmx"
VS2010_work="$VM_DIR/Win 7 x64 VS2010 work.vmwarevm/Windows 7 Ultimate x64.vmx"

VS2010_upstream_ip=192.168.192.129
VS2010_work_ip=192.168.192.132
VS2008_upstream_ip=192.168.192.131
VS2008_work_ip=192.168.192.130

build_clang() {
    branch="$1"
    vmx_file="$2"
    ip_addr="$3"

    "$FUSION/vmrun" -T fusion start "$vmx_file"
    osascript -e 'tell application "System Events" to set visible of process "VMware Fusion" to false'

    echo Waiting for virtual machine to start up...
    sleep 60

    mountpoint=${ip_addr}_C
    if [[ ! -d /tmp/$mountpoint ]]; then
        mkdir -p /tmp/$mountpoint
    fi
    mount_smbfs //BoostPro:password@$ip_addr/C\$ /tmp/$mountpoint

    if [[ ! -d /tmp/$mountpoint/Windows ]]; then
        echo Failed to mount C: on $ip_addr
        exit 1
    fi
    rsync -Ltrv --modify-window=2 --exclude='.*' --delete \
        ~/src/llvm/branches/$branch/ /tmp/$mountpoint/src/llvm/

    winexe -U BoostPro --password=password //$ip_addr cmd <<EOF
net use z: "\\\\vmware-host\\Shared Folders"
c:
@rem cd \\src\\llvm
@rem git.exe --no-pager pull --no-progress -q
@rem if errorlevel 1 (
@rem    echo FAILED: Reason Given is %errorlevel%
@rem    exit /b %errorlevel%
@rem )
@rem cd \\src\\llvm\\tools\\clang
@rem git.exe --no-pager pull --no-progress -q
@rem if errorlevel 1 (
@rem    echo FAILED: Reason Given is %errorlevel%
@rem    exit /b %errorlevel%
@rem )
cd \\build
rm -fr llvm\\*
.\\build
if errorlevel 1 (
   echo FAILED: Reason Given is %errorlevel%
   exit /b %errorlevel%
)
exit 0
EOF
    errorlevel=$?

    umount /tmp/$mountpoint

    "$FUSION/vmrun" -T fusion suspend "$vmx_file"
    osascript -e 'tell application "System Events" to set visible of process "VMware Fusion" to false'

    exit $errorlevel
}

status=0

case $1 in
    upstream_2010)
        if ! build_clang upstream "$VS2010_upstream" $VS2010_upstream_ip; then
            echo Windows build of Clang upstream failed on Visual Studio 2010
            status=1
        fi
        ;;
    work_2010)
        if ! build_clang work "$VS2010_work" $VS2010_work_ip; then
            echo Windows build of Clang work failed on Visual Studio 2010
            status=1
        fi
        ;;
    merge_2010)
        if ! build_clang merge "$VS2010_work" $VS2010_work_ip; then
            echo Windows build of Clang work failed on Visual Studio 2010
            status=1
        fi
        ;;
    upstream_2008)
        if ! build_clang upstream "$VS2008_upstream" $VS2008_upstream_ip; then
            echo Windows build of Clang upstream failed on Visual Studio 2008
            status=1
        fi
        ;;
    work_2008)
        if ! build_clang work "$VS2008_work" $VS2008_work_ip; then
            echo Windows build of Clang work failed on Visual Studio 2008
            status=1
        fi
        ;;
    merge_2008)
        if ! build_clang merge "$VS2008_work" $VS2008_work_ip; then
            echo Windows build of Clang work failed on Visual Studio 2008
            status=1
        fi
        ;;
    *)
        status=1
        ;;
esac

exit $status
