#!/bin/sh

if [[ "$1" == "--passwords" ]]; then
    source $2
    shift 2
fi

export GIT_WORKSPACE=/Volumes/ext/Git
if [[ -z "$GITHUB_TOKEN" ]]; then
    export GITHUB_TOKEN=$(pass show api.github.com | head -1)
fi

cd $GIT_WORKSPACE

git workspace update -t 1
git workspace fetch -t 1
git workspace archive
