#!/usr/bin/env bash

if [[ -f .git || -d .git ]]; then
    git worktree add -b johnw/$1 $1 ${2:-upstream}/main
elif [[ -d main/.git ]]; then
    cd main
    git worktree add -b johnw/$1 ../$1 ${2:-upstream}/main
    cd ..
elif [[ -d master/.git ]]; then
    cd master
    git worktree add -b johnw/$1 ../$1 ${2:-upstream}/master
    cd ..
fi

cd $1
git retrack ${2:-upstream}

if [[ -d ../.bare ]]; then
    perl -i -pe 's%gitdir: .+?/.bare/(.+)%gitdir: ../.bare/$1%;' .git
    perl -i -pe "s%.+?/${1}/.git%../../../${1}/.git%;" ../.bare/worktrees/${1}/gitdir
fi

if [[ $PWD =~ /pos(itron)?/ ]]; then
    positron
fi
