#!/usr/bin/env bash

UPSTREAM=upstream

if [[ -f .git || -d .git ]]; then
    if ! git remote $UPSTREAM &> /dev/null ; then
        UPSTREAM=origin
    fi
    git worktree add -b johnw/$1 $1 ${2:-$UPSTREAM}/main
elif [[ -d main/.git ]]; then
    cd main
    if ! git remote $UPSTREAM &> /dev/null ; then
        UPSTREAM=origin
    fi
    git worktree add -b johnw/$1 ../$1 ${2:-$UPSTREAM}/main
    cd ..
elif [[ -d master/.git ]]; then
    cd master
    if ! git remote $UPSTREAM &> /dev/null ; then
        UPSTREAM=origin
    fi
    git worktree add -b johnw/$1 ../$1 ${2:-$UPSTREAM}/master
    cd ..
fi

cd $1
git retrack ${2:-$UPSTREAM}

if [[ -d ../.bare ]]; then
    perl -i -pe 's%gitdir: .+?/.bare/(.+)%gitdir: ../.bare/$1%;' .git
    perl -i -pe "s%.+?/${1}/.git%../../../${1}/.git%;" ../.bare/worktrees/${1}/gitdir
fi

if [[ $PWD =~ /pos(itron)?/ ]]; then
    positron
elif [[ $PWD =~ /tron/ ]]; then
    positron
fi
