#!/usr/bin/env bash

ARGS=""
if [[ "$1" == "-f" ]]; then
    ARGS="--force"
    shift 1
fi

BRANCH="$1"
if [[ $BRANCH =~ johnw/(.+) ]]; then
    BRANCH="${BASH_REMATCH[1]}"
fi

git worktree remove $ARGS work/$BRANCH

git branch -D johnw/$BRANCH || exit 0
git branch -D -r origin/johnw/$BRANCH || exit 0
