#!/usr/bin/env bash

set -e

ARGS="--force"
if [[ "$1" == "-i" ]]; then
    ARGS=""
    shift 1
elif [[ "$1" == "-f" || "$1" == "--force" ]]; then
    shift 1
fi

for branch in "$@"; do
    if [[ $branch =~ johnw/(.+) ]]; then
        branch="${BASH_REMATCH[1]}"
    fi

    DIR="$PWD"

    if [[ -f .git ]]; then
        git worktree remove $ARGS $branch
    elif [[ -d master ]]; then
        cd master
        git worktree remove $ARGS $branch
    else
        cd main
        git worktree remove $ARGS $branch
    fi

    if ! git branch -D johnw/$branch
    then
        git branch -D $branch
    fi

    cd "$DIR"
done
