#!/bin/bash

PIPE=/tmp/pipe.$$

incr=""
if [[ "$1" == "-i" ]]; then
    incr="-i $2"
    shift 2
fi

mkfifo $PIPE

echo zfs send $incr $1; zfs send $incr $1 > $PIPE &
echo zfs recv -v -d $2; ssh titan sudo /usr/sbin/zfs recv -v -d $2 < $PIPE &

wait

/bin/rm -f $PIPE
