#!/bin/bash

if [[ -z "$1" ]]; then
    echo "usage: zfs-transfer <SNAPSHOT> <FROM> <TO> <SIZE>"
    exit 1
fi

snapshot="$1"
from="$2"
to="$3"
size="$4"

shift 4

zfs send -cLR ${from}@${snapshot}                                               \
    | pv -B 4G -s ${size}                                                       \
    | sudo zfs recv -F "$@" ${to}
