#!/usr/bin/env python

# zipdir: makes multiple <2Mb ZIPs out of a directory

import sys
import os
import string

from os.path import *
from stat import *

def process_chunk(dir, chunk_files, index):
    os.system("zip \"%s-%d.zip\" %s" %
              (basename(dir), index,
               "\"" + string.join(chunk_files, "\" \"") + "\""))

for dir in sys.argv[1:]:
    index       = 1
    total_size  = 0
    chunk_files = []

    for file in os.listdir(dir):
        path = join(dir, file)
        if not isfile(path): continue

        size = os.stat(path)[ST_SIZE]
        if total_size + size < 2097152:
            chunk_files.append(path)
            total_size += size
            continue
        
        process_chunk(dir, chunk_files, index)

        index      += 1
        total_size  = 0
        chunk_files = []

    if chunk_files:
        process_chunk(dir, chunk_files, index)
