#!/bin/bash -xe

HDIR=$HOME/Library/HoogleNix

test -d $HDIR || mkdir -p $HDIR
cd $HDIR

function import_dbs() {
    find $1 -name '*.txt' \
        | parallel 'cp -p {} .; perl -i -pe "print \"\@url file://{//}/index.html\n\" if /^\@version/;" {/}; hoogle convert {/}'
}

import_dbs $(which ghc)/../../share/doc/ghc-7.6.3/html/libraries
for i in $propagatedNativeBuildInputs ; do
    import_dbs $i/share/doc
done

rm -f default.hoo rehoo*
find . -type f | xargs chmod 644

time hoogle data -d $HDIR --redownload -l $(echo *.txt | sed 's/\.txt//g')
time rehoo -j4 -c64 .
