#!/bin/bash

cp -p ~/.emacs.el ~/Library/Emacs

(cd ~/bin; git addremove; git commit -a -m changes)
#(cd ~/doc; git addremove; git commit -a -m changes)
(cd ~/Dropbox; git addremove; git commit -a -m changes)

if ping -q -t 5 -c 1 cegsvn > /dev/null; then
    (cd ~/Contracts/CEG; bin/svn-mirror.sh)
fi

#if [ -d /Volumes/Alpha ]; then
#    backup-games
#fi

#ssh -t jw sudo chown -R johnw Backup &
#ssh -t jw sudo chmod -R u+w Backup &

#wait

#~/bin/backup/backup "$@" vps &
#~/bin/backup/backup "$@" vps-archives &

hdiutil attach ~/Archives/Backups/VPS.sparsebundle
sudo chmod -R u+w /Volumes/VPS
~/bin/backup/backup "$@" vps-snapshot

counter=0
while [[ -d /Volumes/VPS && $counter != 20 ]]; do
    hdiutil detach /Volumes/VPS
    sleep 60
    counter=$((counter + 1))
done

#wait
