#!/bin/bash

cp -p ~/.emacs.el ~/Library/Emacs
(cd ~/Library/Emacs; git addremove; git commit -a -m changes)

(cd ~/bin; git addremove; git commit -a -m changes)
(cd ~/doc; git addremove; git commit -a -m changes)

backup-games

~/bin/backup/backup "$@" vps &
~/bin/backup/backup "$@" vps-archives &

sudo chmod -R u+w ~/Archives/Backups/VPS
~/bin/backup/backup "$@" vps-snapshot &

wait
