# Cache files

- /.cpan/
- /.java/
- /Library/Safari/Icons/
- /Library/Lisp/sbcl*
- /Library/Icons/
- Cache/
- Caches/
- /Products/

# Temporary files

- #*#
- lib*.a
- lib*.la
- lib*.lo
- *.aux
- *.bak
- *.dvi
- *.elc
- *.log
- *.fasl
- *.fas
- *.xfasl
- *.fsl
- *.x86f
- *.o
- *.orig
- *.pyc
- *.pyo
- *.rej
- *~
- .#*
- .*~

- /Projects/ledger/.deps/
- /Projects/ledger/.libs/
- /Projects/ledger/AUTHORS
- /Projects/ledger/COPYING
- /Projects/ledger/ChangeLog
- /Projects/ledger/INSTALL
- /Projects/ledger/Makefile
- /Projects/ledger/Makefile.in
- /Projects/ledger/TAGS
- /Projects/ledger/acconf.h
- /Projects/ledger/acconf.h.in
- /Projects/ledger/aclocal.m4
- /Projects/ledger/autom4te.cache/
- /Projects/ledger/config.guess
- /Projects/ledger/config.log
- /Projects/ledger/config.status
- /Projects/ledger/config.sub
- /Projects/ledger/configure
- /Projects/ledger/configure.in
- /Projects/ledger/depcomp
- /Projects/ledger/elc-stamp
- /Projects/ledger/elisp-comp
- /Projects/ledger/install-sh
- /Projects/ledger/ledger
- /Projects/ledger/ledger.info
- /Projects/ledger/libtool
- /Projects/ledger/ltmain.sh
- /Projects/ledger/missing
- /Projects/ledger/stamp-h1
- /Projects/ledger/system.hh.gch
- /Projects/ledger/texinfo.tex
