# Cache files

- /.cpan/
- /.ccache/
- /.java/
- /Library/Safari/Icons/
- /Library/Lisp/sbcl*
- /Library/Icons/
- /Library/Application Support/WhatSize/
- Cache/
- Caches/
- /Products/

# Temporary files

- #*#
- lib*.a
- lib*.la
- lib*.lo
- *.aux
- *.bak
- *.dvi
- *.elc
- *.log
- *.fasl
- *.fas
- *.xfasl
- *.fsl
- *.x86f
- *.o
- *.orig
- *.pyc
- *.pyo
- *.rej
- *~
- .#*
- .*~

- /Projects/**/.deps/
- /Projects/**/.libs/
- /Projects/**/AUTHORS
- /Projects/**/COPYING
- /Projects/**/ChangeLog
- /Projects/**/INSTALL
- /Projects/**/Makefile
- /Projects/**/Makefile.in
- /Projects/**/TAGS
- /Projects/**/acconf.h
- /Projects/**/acconf.h.in
- /Projects/**/aclocal.m4
- /Projects/**/autom4te.cache/
- /Projects/**/config.guess
- /Projects/**/config.log
- /Projects/**/config.status
- /Projects/**/config.sub
- /Projects/**/configure
- /Projects/**/configure.in
- /Projects/**/depcomp
- /Projects/**/elc-stamp
- /Projects/**/elisp-comp
- /Projects/**/install-sh
- /Projects/**/ledger
- /Projects/**/ledger.so
- /Projects/**/ledger.info
- /Projects/**/libtool
- /Projects/**/ltmain.sh
- /Projects/**/missing
- /Projects/**/src/system.hh.gch
- /Projects/**/stamp-h1
- /Projects/**/system.hh.gch
- /Projects/**/texinfo.tex
