- /.cvs
- /.cvspass
- /.gnupg
- /.ledger-cache
- /.authinfo
- /.sitecopyrc
- /.ssh/id_dsa
- /.ssh/id_rsa
- /.ssh/identity
- /.ssh/known_hosts
- /.subversion
- /.netrc

- /Library/Keychains/
- /Library/Application Support/1Password/
- /Library/openvpn/
- /Contracts/
