- /.cvs
- /.cvspass
- /.gnupg
- /.ledger-cache
- /.sitecopyrc
- /.ssh/id_dsa
- /.ssh/id_rsa
- /.ssh/identity
- /.ssh/known_hosts
- /.subversion
- /.netrc

- /Library/openvpn/
- /Library/Keychains/
- /Private/Keys.dmg
- /Private/CEG.sparsebundle/
- /Private/Misc.sparseimage
