#!/bin/sh
echo ======================================== >> /var/log/backup-aws.log
date >> /var/log/backup-aws.log
echo ======================================== >> /var/log/backup-aws.log
while true; do
/usr/bin/rsync -aPz --no-D --delete --delete-excluded \
    --exclude=/dev/ \
    --exclude=/proc/ \
    --exclude=/sys/ \
    --exclude=/var/named/chroot/proc/ \
    --exclude=/srv/wordpress/wp-content/cache/ \
    --exclude=/srv/wordpress/wp-content/cache/supercache/ \
    aws.entic.net:/ /tank/Backups/BoostPro/aws/ #>> /var/log/backup-aws.log
done
